Crown-Commercial-Service/crown-marketplace

- Dockerfile
- README.md
- app/views/home/index.html.erb
- bin/docker-entrypoint.sh
- config/database.yml
To allow the app to be deployed to the AWS infrastructure.
> Add Dockerfile

- data/facilities_management/services.csv
- data/facilities_management/work_packages.csv
- spec/models/facilities_management/service_spec.rb
- spec/models/facilities_management/work_package_spec.rb
All work package and service names inside the .csv files in the data folder has been updated. Everything is in sentence case now.
> changed all work package and service names to sentence case

- app/assets/stylesheets/components/header/_header.scss
- app/views/layouts/application.html.erb
- spec/features/authentication.feature_spec.rb
Moved the logout button to the header. Styled the button to look like a link too.
> move logout to header

- app/views/facilities_management/home/index.html.erb
Content of FM homepage is updated.
> update FM homepage copy

- config/locales/en.yml
- spec/models/supply_teachers/branch_spec.rb
- spec/models/supply_teachers/rate_spec.rb
- spec/views/layouts/application.html.erb_spec.rb
Content of Supply Teachers updated including:
- Suppliers list > Suppliers list
- Job Type > Job type
- Mark up / markup > Mark-up
> Supply teachers content update

- app/assets/stylesheets/components/mc-supplier-record/_mc-supplier-record.scss
- app/views/management_consultancy/suppliers/_supplier.html.erb
https://trello.com/c/UDs7fKws/203-style-the-supplier-list-for-management-consultancy
- Contact details are styled
- Services are styled
> Styling the MC supplier list

- app/views/supply_teachers/journey/payroll_provider.html.erb
- config/locales/en.yml
- spec/features/supply_teachers/workers_on_agency_payroll.features_spec.rb
- spec/features/supply_teachers/workers_on_school_payroll.features_spec.rb
https://trello.com/c/zrnUwPmj/268-amend-question-asking-do-you-want-to-put-the-worker-on-the-schools-payroll
- Updated label of the school payroll question
- Updated labels for the answers
- Swapped the Yes and No logic for the answers
> (fix) Updated label and swapped answers for the school payroll question

- .gitignore
- config/locales/en.yml
Change the wording on the "What are you looking for?" page to refer to a school, not an individual.
> (chore) 2.1 Wording consistently needs to refer to a school rather than an individual

- config/locales/en.yml
Update text to  read ‘contact the supplier of your choice from the list below to find a suitable, available worker and their daily rate’.
> (chore) Amend text in the 'What to do next' section of the supplier list

- app/views/supply_teachers/gateway/index.html.erb
- config/locales/en.yml
Trello card: https://trello.com/c/FTyPaO0X/918-update-guidance-on-start-page-for-users-with-no-dfe-login
> (chore) Update the guidance text on the service Start page

- app/models/login/dfe_login.rb
> (bugfix) Temporary logging of OmniAuth response

- app/views/supply_teachers/home/index.html.erb
- config/locales/en.yml
This page had not been internationalised. As a Welsh version of the site may be needed in future, everything should be internationalised.
> (chore) Internationalise supply teachers home page

- data/supply_teachers/organisation_categories.csv
As per request from product owner - make all organisation categories "non-profit" except for establishment, multi-academy trust and single-academy trust.
> (chore) Amend organisation categories' statuses

- app/views/supply_teachers/gateway/index.html.erb
- config/locales/en.yml
https://trello.com/c/V6x5MtPB/973-revisit-guidance-for-accessing-to-agreement-without-existing-dfe-account
- Change content of the sign-in page
> (chore) update content of sign-in page

- app/models/supply_teachers/branch.rb
Trello: https://trello.com/c/bV236Dtp/953-tuning-of-the-service-in-time-for-the-handover
> (chore) Consolidate supplier search query to reduce db calls by 1

- app/helpers/supply_teachers/temp_to_perm_calculator_helper.rb
- app/views/supply_teachers/home/_after_12_weeks_and_not_enough_notice.html.erb
- app/views/supply_teachers/home/_between_9_and_12_weeks_and_enough_notice.html.erb
- app/views/supply_teachers/home/_between_9_and_12_weeks_and_no_notice_date.html.erb
- app/views/supply_teachers/home/_between_9_and_12_weeks_and_not_enough_notice.html.erb
- app/views/supply_teachers/home/_within_first_8_weeks.html.erb
- app/views/supply_teachers/home/temp_to_perm_fee.html.erb
- config/locales/en.yml
- spec/views/supply_teachers/home/temp_to_perm_fee.html.erb_spec.rb
https://trello.com/c/nH8HcMgs/923-62-content-of-calculation-page-is-wordy-and-likely-to-be-misunderstood
- Details of content changes in all 7 scenarios can be found in https://docs.google.com/document/d/1JX3S1ueq2FgTjRjRlODs7PeEPrppS5j3pYdBTpREPMg/edit#
> (chore) content update on temp-to-perm calculator

- app/models/login.rb
- app/models/login/base_login.rb
- app/models/login/dfe_login.rb
- spec/models/login/cognito_login_spec.rb
- spec/models/login/dfe_login_spec.rb
- spec/models/login_spec.rb
Before: user@example.com
After: u___@example.com
> (chore) Redact email address from login-related log lines

- app/views/supply_teachers/home/_avoid_paying_fees.html.erb
- spec/views/supply_teachers/home/_avoid_paying_fees.html.erb_spec.rb
reverting the change.
Julia Kondor says we need better clarification.
> Revert "https://pushback.atlassian.net/browse/ST-11"

- bin/docker-entrypoint.sh
https://pushback.atlassian.net/browse/FM-38
> fix the Docker command

- app/assets/stylesheets/_settings.scss
- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/views/home/landing_page.html.erb
- app/views/layouts/application.html.erb
- config/routes.rb
Framework Landing Page: jira CP-3
> C mp landing page cp 3

- Gemfile.lock
In attempt to fix CodePipeline build
> Switched bundle version back

- app/models/supply_teachers/spreadsheet.rb
- spec/models/supply_teachers/spreadsheet_spec.rb
Changed name from 'Suppliers' to 'Agency shortlist'
> Changed name of the tab of the downloaded xlsx file

- app/helpers/application_helper.rb
- app/views/layouts/_header-banner.html.erb
- app/views/layouts/application.html.erb
- spec/views/layouts/application.html.erb_spec.rb
> Feature/CP-32 Set back to start link dynamically for each service

- app/assets/apprenticeships/apprenticeships.scss
- app/views/apprenticeships/home/find_apprentices.html.erb
- app/views/apprenticeships/home/find_apprentices2.html.erb
- app/views/apprenticeships/home/find_apprentices5.html.erb
- app/views/apprenticeships/home/index.html.erb
- app/views/apprenticeships/home/requirement.html.erb
- app/views/apprenticeships/home/requirements.html.erb
- app/views/apprenticeships/home/search_results.html.erb
- config/locales/en.yml
AT-69 ticket: Apprenticeship Requirements (single location).
http://localhost:3000/apprenticeships/requirement
https://sketch.cloud/s/7bv58/092LM40
> Apprenticeships

- app/views/supply_teachers/home/index.html.erb
- app/views/supply_teachers/journey/looking_for.html.erb
- config/locales/en.yml
Updated copy to show that we now have new functionality.
- Start page bullet point: 
View a list of all agencies
- Radio button label:
A list of all the agencies
- Removed the 'or' that is floating around on the looking_for page.
Also updated DfE logo size from 125 to 145px on Alaric's request.
> Feature/ST-44 Content changes

- app/views/management_consultancy/suppliers/index.html.erb
- config/i18n-tasks.yml
- config/locales/en.yml
- spec/features/management_consultancy/management_consultancy.feature_spec.rb
Closes MC47
Text now matches design on this page https://sketch.cloud/s/5PQDP/m1GpogL
> Change text for suppliers found  results on supllier results page

- lib/tasks/quiet_rspec.rake
fixes the 
rake spec
task on master
> for rspec to load static data into test db

- app/services/postcode/postcode_checker.rb
- spec/controllers/postcode/postcodes_controller_spec.rb
- spec/services/postcode/postcode_checker_spec.rb
https://pushback.atlassian.net/browse/FM-75
returns status code
> postcode is in London

- app/views/management_consultancy/suppliers/index.html.erb
- config/locales/en.yml
- spec/features/management_consultancy/management_consultancy.feature_spec.rb
@DH02 just content changes to match this page here https://sketch.cloud/s/5PQDP/MyJkn3m/play
> feature/MC47 Change heading on supplier results page

- app/controllers/supply_teachers/branches_controller.rb
Added back button in on the show branch page (supply teachers)
> Added back button in on the show branch page (supply teachers)

- app/assets/javascripts/global/global.js
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/controllers/application_controller.rb
- app/controllers/ccs_patterns/framework_controller.rb
- app/controllers/ccs_patterns/home_controller.rb
- app/controllers/ccs_patterns/requirements_controller.rb
- app/views/ccs_patterns/_link_to_start_page.html.erb
- app/views/ccs_patterns/home/dynamic_accordian.html.erb
- app/views/ccs_patterns/home/index.html.erb
- config/routes.rb
Fixed the syntax issue for robocop in it home file
> Dynamic accordian at 98

- app/controllers/application_controller.rb
- app/controllers/ccs_patterns/framework_controller.rb
- app/controllers/ccs_patterns/home_controller.rb
- app/controllers/ccs_patterns/requirements_controller.rb
- app/views/ccs_patterns/_link_to_start_page.html.erb
- app/views/ccs_patterns/home/dynamic_accordian.html.erb
- app/views/ccs_patterns/home/index.html.erb
- config/routes.rb
Created a new directory (with a landing page and one pattern page) for files to show new HTML ccs patterns. (I shall create a new feature branch for any pattern development moving forward).
> New ccs patterns directory created

- app/assets/stylesheets/_settings.scss
- app/views/layouts/_footer.html.erb
URL and style of html footer links updated
> footer url CP-30

- app/assets/apprenticeships/apprenticeships.scss
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/views/apprenticeships/home/_provider_filters.html.erb
- app/views/apprenticeships/home/find_apprentices4.html.erb
- app/views/apprenticeships/home/search_results.html.erb
- app/views/ccs_patterns/home/small_checkboxes.html.erb
Completion of checkbox styles example created in ccs-global.
> checkbox styles in global AT-92

- app/assets/javascripts/global/global.js
small amount of js in js file to resolve IE11 menu bug (on later IE11 > 11.5).
> IE11 menu fix CP-47

- app/controllers/legal_services/home_controller.rb
- app/views/legal_services/home/service_not_suitable.html.erb
- config/locales/en.yml
- config/routes.rb
USER STORY
As a user I want to be presented with a page notifying me when I am searching for a service that is not appropriate.So that I can review guidance and proceed
(link to prototype page can be found here - https://sketch.cloud/s/rGDea/zxR0o2e)
Acceptance Criteria
1. When selecting the link provided the user is directed to an alternative window providing guidance.
2. When selecting ‘back to start’ I am returned to the start page
> LS-53 Service isn't suitable

- app/controllers/ccs_patterns/home_controller.rb
- app/views/apprenticeships/home/search_results.html.erb
- app/views/apprenticeships/home/supplier_search.html.erb
- app/views/apprenticeships/home/supplier_search2.html.erb
- app/views/ccs_patterns/home/index.html.erb
- app/views/ccs_patterns/home/supplier_results_v1.html.erb
- app/views/ccs_patterns/home/supplier_results_v2.html.erb
- app/views/supply_teachers/home/index.html.erb
- config/routes.rb
another com for global html/css styles
> Html search results at 116

- app/assets/javascripts/facilities_management/buildings.js
- app/services/facilities_management/fm_buildings_data.rb
- app/views/facilities_management/buildings/_building_list.html.erb
- db/schema.rb
Tariq,
Moved to jsonb, no issues.
Removed unnecessary "true" from the service.
Fixed a bug (your postcode lookup changes) to read status and data from ajax calls.
Could you do the honours please.
> FM52 review changes and bug fixes

- app/assets/apprenticeships/apprenticeships.scss
- app/assets/javascripts/global/global.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/components/supplier-record/_supplier-record.scss
Remove a js snippet no longer required for an old ie11 bug + corrected minor scss syntax issue.
> minor CP scss syntax errors corrected

- app/controllers/legal_services/suppliers_controller.rb
- app/views/legal_services/suppliers/_supplier.html.erb
- app/views/legal_services/suppliers/index.html.erb
- config/locales/en.yml
- config/routes.rb
Added supplier-results page with mocked data
> LS-44 Supplier results

- app/assets/javascripts/global/global.js
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/controllers/ccs_patterns/home_controller.rb
- app/views/apprenticeships/home/find_apprentices.html.erb
- app/views/apprenticeships/home/find_apprentices2.html.erb
- app/views/apprenticeships/home/find_apprentices3.html.erb
- app/views/ccs_patterns/home/dynamic_accordian.html.erb
- app/views/ccs_patterns/home/index.html.erb
- app/views/ccs_patterns/home/small_checkboxes.html.erb
- app/views/ccs_patterns/home/supplier_results_v2.html.erb
- app/views/ccs_patterns/home/titles_checkboxes.html.erb
- config/routes.rb
New CCS global pattern for FM/CP and some minor snagging.
> New pattern and snags

- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/controllers/ccs_patterns/home_controller.rb
- app/views/apprenticeships/home/search_results.html.erb
- app/views/ccs_patterns/home/index.html.erb
- app/views/ccs_patterns/home/numbered_pagination.html.erb
- app/views/ccs_patterns/home/supplier_results_v1.html.erb
- config/routes.rb
> pagination pattern created

- app/assets/apprenticeships/apprenticeships.scss
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/views/ccs_patterns/home/table_5050.html.erb
Final, additional, update to global scss (moving css across).
> updated global ccs css

- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/controllers/facilities_management/contract_controller.rb
- app/views/facilities_management/contract/start_of_contract.html.erb
- app/views/facilities_management/long_list/long_list.html.erb
- config/routes.rb
HTML form page created, with new 'contract' directory with router. /contract-start/
> Starting your contract html fm 57

- app/views/facilities_management/contract/start_of_contract.html.erb
Start your contract HTML form with error message added.
> Start your contract HTML: error state added

- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/controllers/management_consultancy/html_controller.rb
- app/views/ccs_patterns/home/titles_checkboxes.html.erb
- app/views/management_consultancy/html/select_lot.html.erb
- app/views/management_consultancy/html/select_services.html.erb
- config/routes.rb
MC Select Lot page added (with controller and route).
> Html select lot details MC 93

- app/views/management_consultancy/html/download_the_supplier_list.html.erb
- config/locales/en.yml
Final updates to the HTML page for MC Supplier List.
> Download supplier list mc 97

- app/controllers/management_consultancy/suppliers_controller.rb
- app/models/management_consultancy/supplier.rb
- app/views/management_consultancy/suppliers/index.html.erb
- spec/factories/management_consultancy_supplier.rb
> Order management consultancy suppliers by average daily rate

- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
minor edit to css to resolve heading padding issue.
> updated with media q

- .travis.yml
- pipeline_pre_build_tests.sh
> Switched to version 2.4 of postgis

- app/controllers/postcode/postcodes_controller.rb
- app/services/postcode/postcode_checker.rb
- spec/controllers/postcode/postcodes_controller_spec.rb
invoked by curl command or through URL copied into web browser
> controller action that starts rake db:postcodes

- app/assets/javascripts/facilities_management/fm-buildings.js
- app/controllers/api/postcodes_controller.rb
- app/controllers/api/v1/postcodes_controller.rb
- app/controllers/api/v1/uploads_controller.rb
https://pushback.atlassian.net/browse/CP-68
> [CRITICAL] Reported vuln's in github application / repo

- app/controllers/supply_teachers/suppliers_controller.rb
- config/locales/en.yml
- spec/controllers/supply_teachers/suppliers_controller_spec.rb
Fixed login page title.
Also ordered all suppliers by name.
> feature/ST-82 Fixed login page title

- app/controllers/supply_teachers/suppliers_controller.rb
- spec/controllers/supply_teachers/suppliers_controller_spec.rb
Fixed all suppliers page. Ordering now happens by slug as it works better than by name
> Order all suppliers

- app/models/legal_services/journey/check_suitability.rb
> Ls 38 select legal services

- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/views/apprenticeships/journey/find_apprentices.html.erb
- app/views/legal_services/journey/check_suitability.html.erb
- config/locales/en.yml
- db/schema.rb
(Updated my feature branch schema from master: but isn't listed as one of the file changes).
> Require transactional property LS-98 html

- app/models/legal_services/journey/choose_services_area2.rb
- app/models/legal_services/journey/lot2_full_service.rb
- config/locales/en.yml
> LS-85-services-total

- app/models/legal_services/journey/regional_legal_service.rb
- app/views/legal_services/journey/regional_legal_service.html.erb
error message regional_legal_service
> regional_legal_service error

- app/views/legal_services/journey/lot1_regional_service.html.erb
lot1_regional_service unique id
> lot1_regional_service unique id

- config/locales/en.yml
> typo correction

- app/models/legal_services/journey/legal_jurisdiction.rb
- app/models/legal_services/journey/supplier_results2.rb
- app/views/legal_services/journey/supplier_results2.html.erb
- config/locales/en.yml
> new html, file, txt

- app/assets/javascripts/legal_services/ls_form_validation.js
- app/models/legal_services/journey/lot1_regional_service2.rb
- app/models/legal_services/journey/select_lot.rb
- app/views/legal_services/journey/lot1_regional_service2.html.erb
- config/locales/en.yml
This branch completes the work required in a different ticket number. This work relates to ticket: LS-145.
> New file, journey amended, txt

- config/locales/en.yml
> Select the legal services you need

- app/controllers/facilities_management/buildings_controller.rb
- app/controllers/facilities_management/cache_controller.rb
- app/controllers/facilities_management/contract_controller.rb
- app/controllers/facilities_management/direct_award_controller.rb
- app/controllers/facilities_management/select_locations_controller.rb
- app/controllers/facilities_management/select_services_controller.rb
- app/helpers/application_helper.rb
- app/models/ability.rb
- app/models/user.rb
- app/services/cognito/sign_in_user.rb
- app/services/cognito/update_user.rb
- config/initializers/cognito_authenticable.rb
- config/routes.rb
- db/schema.rb
- spec/features/authentication.feature_spec.rb
- spec/services/cognito/update_user.rb
- spec/services/cognito/update_user_spec.rb
ccs_employee can now access MC and ST admin, user groups get updated when user signs in, all fm now inherits from FrameworkController
> User sign in fixes

- app/models/management_consultancy/admin/upload.rb
- lib/tasks/management_consultancy/data.rake
- lib/tasks/management_consultancy/scripts/add_rate_cards_to_suppliers.rb
- lib/tasks/management_consultancy/scripts/add_region_availability_per_lot_per_supplier.rb
- lib/tasks/management_consultancy/scripts/add_service_offerings_per_supplier.rb
- lib/tasks/management_consultancy/scripts/add_suppliers.rb
This should be the last one. I cleared out all of the files in storage/.../input to ensure it was getting fresh uploads every time.
> Bring MC upload scripts into line with ST

- config/environments/development.rb
- config/environments/production.rb
- config/environments/test.rb
Tariq I have switched off making gz copies of assets, could you please review the changes for me.
This is associated with ticket SEC-32.
> Switched off compressed copies of assets

- app/models/legal_services/lot3.rb
- app/models/legal_services/lot4.rb
- data/legal_service/lots3.csv
- data/legal_service/lots4.csv
- lib/tasks/legal_services/legal_services/data.rake
- lib/tasks/legal_services/legal_services/scripts/@
- lib/tasks/legal_services/legal_services/scripts/\
- lib/tasks/legal_services/legal_services/scripts/add_lots_and_services.rb
- lib/tasks/legal_services/legal_services/scripts/add_rate_cards_to_suppliers.rb
- lib/tasks/legal_services/legal_services/scripts/add_region_availability_per_lot_per_supplier.rb
- lib/tasks/legal_services/legal_services/scripts/add_service_offerings_per_supplier.rb
- lib/tasks/legal_services/legal_services/scripts/add_suppliers.rb
just a wip push - still needs work
> Ls 154 temporary upload

- app/controllers/supply_teachers/uploads_controller.rb
Added skip verify_authenticity_token in ST uploads_controller as it raises a Can't verify CSFR token authenticity error
> ST uploader fix

- app/models/legal_services/admin/upload.rb
- app/models/supply_teachers/admin/upload.rb
- app/workers/supply_teachers/data_script_worker.rb
- config/initializers/carrierwave.rb
- lib/tasks/management_consultancy/data.rake
- lib/tasks/supply_teachers/data.rake
Also files should be uploaded as private rather than public-read
> Fixed Admin cancel and fail

- app/controllers/base/users_controller.rb
- app/controllers/management_consultancy/admin/uploads_controller.rb
- app/services/cognito/create_user_from_cognito.rb
- config/locales/en.yml
- spec/services/cognito/create_user_from_cognito_spec.rb
- Fixed create_user_from_cognito to update user if already exists in db
- Fixed not authorised page for apprenticeships and access for MC admin tool
- Fixed registration screen symbol
> Cognito bug fixes

- app/controllers/base/sessions_controller.rb
- app/controllers/facilities_management/sessions_controller.rb
- app/controllers/legal_services/sessions_controller.rb
- app/controllers/management_consultancy/sessions_controller.rb
- app/controllers/supply_teachers/sessions_controller.rb
- app/services/cognito/sign_in_user.rb
- config/locales/en.yml
- spec/services/cognito/sign_in_user_spec.rb
Also fixed copy for not on whitelist page
> User is now redirected to confirmation page if required. 

- app/assets/javascripts/common/common.js
- app/assets/javascripts/facilities_management/fm-locations.js
Added the getCodes method in the submission to long-list...
long-list supplies data now
> Corrected Code Values for submission

- app/views/facilities_management/beta/buildings_management/_building_list.html.erb
- app/views/facilities_management/beta/buildings_management/_buildings_management_controller.html.erb
- app/views/layouts/_footer.html.erb
- config/locales/en.yml
Added back button, corrected cosmetic and textual issues and change footer text
> FM-172 - Buildings Management QA changes

- spec/features/supply_teachers/fta_to_perm_calculator.features_spec.rb
Removing failing test so we can deploy. @iceraluk not sure what's going on, it suddenly started failing. Will need to look at it when you're back.
> Comment out failing test on FTA to perm calculator

- app/assets/javascripts/facilities_management/beta/building_management/building_address.js
- spec/features/supply_teachers/fta_to_perm_calculator.features_spec.rb
@kennyevil (Chris) has noted the test is failing on the 29th of August
The test might assume that the end of the month is August 28
> removal of buggy Supply Teacher test

- app/assets/javascripts/facilities_management/fm-locations.js
- app/assets/javascripts/facilities_management/fm-services.js
- app/views/facilities_management/long_list/long_list.html.erb
I have corrected the logic in select locations and services to remove the errors list in the ticket.
Also, the formatting of text in the long-list page.
> Corrected javascript logic errors and rendering in the long-list.

- app/controllers/facilities_management/beta/buildings_management_controller.rb
- app/services/facilities_management/fm_buildings_data.rb
- app/views/facilities_management/beta/buildings_management/_building_list.html.erb
Update to JSON parse parameter taken from database results.
Updated model class for DB access
Corrected failed logic to prevent selection of Other in security-type screen when no option selected.
> Updated JSON field name from dataset

- app/assets/javascripts/facilities_management/beta/building_management/new_building_steps.js
- app/controllers/facilities_management/beta/buildings_management_controller.rb
- app/services/facilities_management/fm_buildings_data.rb
Skip this step link functionality added
Further repair to JSON column name
> Skip this step link functions

- app/assets/javascripts/facilities_management/beta/building_management/building_security_type.js
- app/assets/javascripts/facilities_management/beta/building_management/new_building_steps.js
Added functions to prevent multi-clicking.
Added improved re-entrant validation for required fields.
> Multi-click of Save button causes duplicate buildings

- app/views/facilities_management/buildings/_building_list.html.erb
Corrected JSON parse issue with building data
> Private Beta broken at building list

- app/views/facilities_management/long_list/_filters.html.erb
> Remove the link in the filter header

- app/controllers/auth_controller.rb
> Temporarily writing to logger the response from dfe

- .travis.yml
- config/initializers/omniauth_dfe.rb
In order to view full backtrace of error
> Temporarily added rescue NoMethodError in omniauth_dfe

- .travis.yml
- app/assets/stylesheets/facilities_management/beta/procurement_building_services.scss
- app/controllers/facilities_management/beta/procurement_buildings_controller.rb
- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/facilities_management/beta/procurement_buildings_helper.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building.rb
- app/models/facilities_management/procurement_building_service.rb
- app/services/facilities_management/procurement_router.rb
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
- app/views/facilities_management/beta/procurements/_about_the_work.html.erb
- app/views/facilities_management/beta/procurements/edit.html.erb
- app/views/facilities_management/beta/procurements/edit/_contract_dates.html.erb
- app/views/facilities_management/beta/procurements/index.html.erb
- app/views/facilities_management/beta/procurements/shared/_backlink_header.html.erb
- app/views/facilities_management/beta/procurements/show.html.erb
- config/locales/views/facilities_management.en.yml
- config/routes.rb
- db/migrate/20191018180155_add_building_id_to_facilities_management_procurement_buildings.rb
- db/migrate/20191018183421_create_facilities_management_procurement_building_service.rb
- db/schema.rb
- spec/models/facilities_management/procurement_building_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/services/facilities_management/procurement_router_spec.rb
> Procurement building services done

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/application_helper.rb
- app/models/concerns/procurement_validator.rb
- app/views/facilities_management/beta/procurements/_procurement_building_services.html.erb
- app/views/facilities_management/beta/procurements/edit/_services.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_services_spec.rb
Rendering bug in the procurement_buildings_services partial
Addition of error message to the locales collection
Addition of validation rule and rspecs for the services context
Rendering of error message in the view
> Updates to the branch:

- app/views/facilities_management/beta/procurements/edit/_contract_dates.html.erb
Required classname for validation is missing
> Missing classname that acts as an anchor

- app/controllers/facilities_management/beta/buildings_management_controller.rb
- app/models/facilities_management/security_types.rb
- app/services/facilities_management/fm_buildings_data.rb
- app/views/facilities_management/beta/buildings_management/_buildings_steps_header.html.erb
- config/database.yml
- db/migrate/20190829114901_add_security_type_table.rb
- db/migrate/20191023113909_create_security_types.rb
- db/migrate/20191023114416_populatesecuritytypes.rb
- db/schema.rb
Integration of schema changes.
Reapplication of security-types table and data
Removal of ccsdev connection string from database yml
New SecurityTypes model class
Repairs to buildings management issues prevent creation of building, building status...
> FM-450 buildings bugs

- config/locales/views/facilities_management.en.yml
Missing the validation message for uniqueness on the name property
> Missing validation messages for name property uniqueness

- app/controllers/facilities_management/beta/procurement_buildings_controller.rb
- app/helpers/application_helper.rb
- app/helpers/facilities_management/beta/procurement_buildings_helper.rb
- app/models/facilities_management/procurement_building_service.rb
- app/views/facilities_management/beta/procurement_buildings/_ppm_standards.html.erb
- app/views/facilities_management/beta/procurement_buildings/_volume.html.erb
- app/views/facilities_management/beta/procurement_buildings/edit.html.erb
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
- app/views/facilities_management/beta/procurements/_services.html.erb
- app/views/facilities_management/beta/procurements/edit/_services.html.erb
- app/views/facilities_management/journey/choose_services.html.erb
- app/views/shared/_error_summary_nested_attributes.html.erb
- config/application.rb
- config/i18n-tasks.yml
- config/locales/views/facilities_management.en.yml
- db/migrate/20191030173705_add_service_standards_to_procurement_building_services.rb
- db/migrate/20191031153244_change_procurement_building_service_primary_key.rb
- db/schema.rb
- spec/models/facilities_management/procurement_building_service_spec.rb
PPM service standards fully working. Just need the copy
Added copy in, fixed validation messages and switched ProcurementBuildingService id to uuid
Rubocop fixes
Fixed locales
Schema fix
> Added PM standards partial

- app/assets/javascripts/facilities_management/beta/procurement_buildings_services_lifts.js
- app/helpers/application_helper.rb
- app/models/facilities_management/procurement_building_service.rb
- app/views/facilities_management/beta/procurement_buildings_services/_lifts.html.erb
- config/locales/views/facilities_management.en.yml
Changes to prevent non-integers from reaching the DB
> Added floating-point validations to restrict poor integers

- app/assets/javascripts/facilities_management/beta/procurement_buildings_services_lifts.js
- app/models/facilities_management/procurement_building_service.rb
- app/views/facilities_management/beta/procurement_buildings_services/_lifts.html.erb
- spec/models/facilities_management/procurement_building_service_spec.rb
This change adjusted the Rails backend so really should go for review....
> Extending the range of allowed numbers into the lift data section

- app/controllers/facilities_management/beta/procurement_buildings_services_controller.rb
- app/models/facilities_management/procurement_building_service.rb
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
Remove some redundant code
Remove issue with validation
> FM-409 - Removed 'Standard' from services output if the value is blank

- app/services/facilities_management/direct_award_spreadsheet.rb
number format change for the calculation excel
FM-551 FM-548
example, 1500.45  should be displayed as 1,500.45
.00 should be displayed as 0.00
> FM-551 FM-548 fix for spreadsheet format

- data/facilities_management/work_packages.json
Chris
Can you give these data changes a quick once-over...?
> Application of changes by Chee required for others to build-on

- app/calculators/fm_calculator/calculator.rb
- spec/calculators/fm_calculator/fm_calculators_spec.rb
- spec/models/facilities_management/summary_report2_spec.rb
- spec/models/facilities_management/summary_report3_spec.rb
- spec/models/facilities_management/summary_report4_spec.rb
- spec/models/facilities_management/summary_report_spec.rb
This change was verified by Atkin
> FM-554 TUPE was not used in the calculations

- app/assets/javascripts/facilities_management/beta/procurement/ChooseServicesBuildings.js
As we did in the huddle, I copied the javascript into the click function so that it would run when all the boxes are clicked.
> Moved Javascript so that it functions on click

- config/locales/views/facilities_management.en.yml
Added the word "Regulations" on line 369 and 371.
> Description for TUPE amended

- app/models/facilities_management/service_hour_choice.rb
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
This fixes layout and display of the change/answer question text
> Repair of display of service summary information

- app/models/facilities_management/service_hour_choice.rb
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
- app/views/facilities_management/beta/procurement_buildings_services/_lifts.html.erb
> Release2 04-12-19

- app/assets/javascripts/facilities_management/beta/building_management/building_security_type.js
- app/views/facilities_management/beta/buildings_management/building_security_type.html.erb
**Character counter when page loads issue:**
Within the Javascript file I moved the part which does the character count into its own function (`findCharsLeft`) so that it could also be used when the page loads. I then added JavaScript to read the text box and find the text in it (as 'value') and then put the 'value' into the function to display the characters remaining. I also removed the hard coded 'You have 150 characters remaining' from the html as this was now redundant.
**Other not saving when nothing is typed in:**
I found this issue which I have described in the ticket. It occurred because by typing in the text box it reassigns its value but if this is reduced to an empty box then it won't revert back to the default text 'other'. To solve this I updated the `findCharsLeft` function …
> Added JavaScript so character counter functions on page load

- config/locales/views/facilities_management.en.yml
Changed the word un-done in delete_message to undone.
> Fixed delete warning message

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/beta/procurements/_errors_on_show.html.erb
- spec/models/facilities_management/procurement_spec.rb
Procurement show page does not validate straight away when procurement is created - now it validates only on click on continue.
> FM-459 procurement page bug

- lib/tasks/facilities_management/fm_suppliers.rake
Added marketplace.preview to list of environments where we need to load dummy supplier data
> feature/FM-381 Upload anonymised data to Preview environment

- lib/tasks/facilities_management/fm_suppliers.rake
Added logic to remove everything in fm_suppliers table before adding the new dummy data
> feature/FM-381 anonymised data on Preview

- app/assets/javascripts/facilities_management/beta/procurement/contract_dates.js
removed 'pattern' case from mobilisation period and replaced with number case
> CSI-49-Duplicate-errors

- data/facilities_management/work_packages.json
I changed the names of the services so that only the first word is capitalised to bring it up to GDS standards.
> Brought-Service-Headings-Inline-With-GDS

- data/facilities_management/work_packages.json
Changed "re-Lamping" to "re-lamping"
> Fixed uncaught capital

- config/locales/views/facilities_management.en.yml
Re-worded for lift data to meet expected values
> Corrected metric in relevant places in .yml file

- app/views/facilities_management/beta/procurements/contract_period/_contract_extension_section.html.erb
- app/views/facilities_management/beta/procurements/contract_period/_contract_period_section.html.erb
- app/views/facilities_management/beta/procurements/contract_period/_mobilisation_section.html.erb
- app/views/facilities_management/beta/procurements/show.html.erb
- config/locales/views/facilities_management.en.yml
Adds an error for if there are unanswered questions in the contract period section in the detail summary page.
> Added an error for contract period section

- app/views/facilities_management/beta/procurements/contract_period/_contract_period_section.html.erb
- app/views/facilities_management/beta/procurements/show.html.erb
The lines between the table cells are back and I've removed the line below the table header
> fixed table issue

- app/views/legal_services/sessions/new.html.erb
- app/views/management_consultancy/sessions/new.html.erb
- config/routes.rb
Reverts Crown-Commercial-Service/crown-marketplace#1131
> Revert "Removed ability to register in MC and LS"

- app/controllers/ccs_patterns/prototype_controller.rb
- app/views/ccs_patterns/prototype/new_notices_contact_details.html.erb
> FM-595 Fixed typos on the New notices contact details page

- app/controllers/ccs_patterns/prototype_controller.rb
- Added the word details to a title
> FM-592-HTML-New-Authorised-Representative-Details

- app/controllers/ccs_patterns/prototype_controller.rb
changed capitalisation to adhere to design standards
> FM-597 local government pension scheme page 

- app/controllers/ccs_patterns/prototype_controller.rb
- app/models/facilities_management/new_procurement_data.rb
- app/views/ccs_patterns/prototype/notices.html.erb
- Changed "select a notice" to "select a contact for notices"
- Changed "Enter a new notices contact" to "Enter a new contact for notices"
- Changed "This person to whom contract notices should be communicated to." to "The person to whom contract notices should be communicated."
> FM-594-HTML-Notices-Page

- app/controllers/facilities_management/beta/supplier/framework_controller.rb
- app/controllers/facilities_management/beta/supplier/offer_controller.rb
- app/helpers/application_helper.rb
- app/models/facilities_management/supplier/offer.rb
- app/views/facilities_management/beta/supplier/_link_to_start_page.html.erb
- app/views/facilities_management/beta/supplier/offer/declined.html.erb
- app/views/layouts/_header-banner.html.erb
- config/routes.rb
- spec/controllers/facilities_management/beta/supplier/offer_controller_spec.rb
- Set up routes for the supplier journey files
- Created a controller with the required code so that it can work with the view layout helper
- Created a Model for the supplier offer
- Created a spec for the controller
- Changed the content of the header for the supplier pages
> Configuration of the project for the supplier journey

- app/controllers/facilities_management/beta/supplier/offer_controller.rb
- app/views/facilities_management/beta/supplier/offer/accepted.html.erb
- config/routes.rb
put placeholder in for back button url
> developed html for contract accepted supplier page

- app/controllers/facilities_management/beta/supplier/home_controller.rb
- app/controllers/facilities_management/beta/supplier/offer_controller.rb
- app/controllers/facilities_management/beta/supplier/supplier_account_controller.rb
- app/helpers/application_helper.rb
- app/models/facilities_management/supplier/supplier_account.rb
- app/views/facilities_management/beta/supplier/supplier_account/_accepted_offers.html.erb
- app/views/facilities_management/beta/supplier/supplier_account/_closed_contracts.html.erb
- app/views/facilities_management/beta/supplier/supplier_account/_live_contracts.html.erb
- app/views/facilities_management/beta/supplier/supplier_account/_received_offers.html.erb
- app/views/facilities_management/beta/supplier/supplier_account/index.html.erb
- app/views/layouts/_header-banner.html.erb
- config/routes.rb
- Created new controller, model and view for the supplier dashboard page (model to be added later)
- In the controller added the content to be sent to the page
- Updated the helper so that the dashboard has the right content in the header
- Created the content view using partials with the functionality (but cannot be tested yet).
- Updated the dashboard links so they go to the correct place on other pages
> Supplier dashboard (HTML)

- app/controllers/facilities_management/beta/supplier/contract_summary_controller.rb
- app/views/facilities_management/beta/supplier/contract_summary/_procurement_requirements.html.erb
- app/views/facilities_management/beta/supplier/contract_summary/contract_withdrawn.html.erb
- config/routes.rb
- Fixed the date formatting in the requirements partial
> Contract Withdrawn Supplier (HTML)

- app/controllers/facilities_management/beta/supplier/offer_controller.rb
- app/controllers/facilities_management/beta/supplier/supplier_account_controller.rb
- app/models/ability.rb
- A user can now see both supplier and buyer journeys if user belongs to both groups
> A user can now be both a buyer and a supplier

- app/views/layouts/_beta-banner.html.erb
- app/views/layouts/application.html.erb
I wanted to avoid having multiple roles within the template so I did the following:
- Moved the beta banner into the main banner and gave it a white background
- Moved the main landmark to be at a the same level as the previous devision
> All page sections within html landmarks

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/facilities_management/beta/procurements_helper.rb
- app/helpers/layout_helper.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/beta/procurements/index.html.erb
- app/views/facilities_management/beta/procurements/results.html.erb
Applied state-changes appropriately
Changed navigation buttons (secondary)
> FM-645 Results part 4

- app/views/facilities_management/beta/direct_award_contract/_da_contract_details.html.erb
- app/views/facilities_management/beta/direct_award_contract/review_and_generate_documents.html.erb
- Observation 2 and 3 in ticket FM-678
- Fixed content issues
> FM-678 observation corrections

- db/migrate/20200113193447_change_fm_rates_attributes.rb
Changed migration to remove index on :code in fm_rates whatever the name of the index might be
> Bug/Migrations Broken On Cmpdev

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/facilities_management/beta/procurements_helper.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/beta/procurements/dashboard_tables/_contracts.html.erb
- db/migrate/20200120153957_add_contract_start_date_to_facilities_management_procurements.rb
- db/schema.rb
- Added a contract start date column to the procurements table (as this will be needed)
- Created the table for the live contracts on the dashboard
> FM-696 procurement dashboard da contracts

- app/services/facilities_management/direct_award_spreadsheet.rb
Add nil for empty cells on DA prices spreadsheet so they have correct format
> FM-707 - Remove all colours from DA spreadsheet

- app/controllers/facilities_management/beta/summary_controller.rb
- app/models/facilities_management/summary_report.rb
- app/services/facilities_management/direct_award_spreadsheet.rb
- spec/models/facilities_management/summary_report2_spec.rb
- spec/models/facilities_management/summary_report_spec.rb
Needed to add a row in the direct_award excel ,contract rate card worksheet, table 2 for cafm and help. a requirement was to not add a row for cafm if no service selected cafm, same for help ; this functionality took most of the code changes.
> FM-682 add cafm, help to table 1,contract rate card

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/facilities_management/beta/procurements_helper.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/beta/procurements/dashboard_tables/_closed.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_contracts.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_in_draft.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_searches.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_sent_offers.html.erb
Dashboard shows correct contract name not quick search name
Sorted the searches and fixed formatting
> Buyer dashboard additional content formatting

- app/controllers/facilities_management/beta/procurements_controller.rb
- config/locales/views/facilities_management.en.yml
The last issues from Akin are repaired:
These are copy changes for button/links and the title
> feature/FM-404 Correction of issues for Akin

- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_supplier.rb
- app/services/facilities_management/contract_number_generator.rb
- db/migrate/20200123101511_add_contract_number_to_facilities_management_procurement_suppliers.rb
- db/schema.rb
- spec/factories/facilities_management_procurement.rb
- spec/factories/facilities_management_procurement_supplier.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- spec/services/facilities_management/contract_number_generator_spec.rb
Add contract number to procurement supplier records
Modify contract number generator to have single method
Finish contract number generation
> Provide a contract number generator for FM

- app/services/facilities_management/contract_number_generator.rb
- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- spec/services/facilities_management/contract_number_generator_spec.rb
Also left aligns dates on contact details sheet on the deliverable matrix spreadsheet
> Use correct framework number for FM contract numbers

- app/assets/javascripts/facilities_management/beta/procurement/ProcurementPensionFunds.js
- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/application_helper.rb
- app/views/facilities_management/beta/procurements/edit/_procurement_pension_fund.html.erb
- Error messages are now clickable and will link to the first error in the list
- If a row has the only error on it, then that error will be removed from the error summary
> Changes for the validation error messages

- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- spec/services/facilities_management/deliverable_matrix_spreadsheet_creator_spec.rb
FM 339 add service periods worksheet
> FM 339 add service periods worksheet

- app/assets/javascripts/facilities_management/beta/procurement/procurement_buildings_services_lifts.js
- app/models/facilities_management/procurement_building_service.rb
- app/views/facilities_management/beta/procurement_buildings_services/_lifts.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_building_service_spec.rb
- Limited number of lifts on the front end
- Limited number of lifts in the back end
- Added tests to validate backend
> Limited the number of lifts that can be added

- app/assets/stylesheets/facilities_management/buildings.scss
- app/views/facilities_management/beta/buildings_management/_buildings_steps_header.html.erb
- app/views/facilities_management/beta/buildings_management/building_type.html.erb
- Added title to building page
- Added 'or' to manage building page
- Changed the alignment of the char count
> Manage building content chenges

- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- spec/services/facilities_management/deliverable_matrix_spreadsheet_creator_spec.rb
added the nuts region name to the, buildings information, worksheet
> FM-734 ,nuts region value was not correct

- app/models/facilities_management/summary_report.rb
- spec/models/facilities_management/summary_report2_spec.rb
add london flag logic,  the nuts region is nor stored with the building info , so I had to look it up directly:
PostcodesNutsRegion.find_by
not the best for performance
> FM-703 add london flag functionality

- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- app/assets/javascripts/facilities_management/beta/procurement/ContractDetails.js
- app/views/facilities_management/beta/buyer_details/edit.html.erb
- app/views/facilities_management/beta/buyer_details/edit_address.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_authorised_representative_address.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_authorised_representative_details.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_invoicing_address.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_invoicing_contact_details.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_notices_address.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_notices_contact_details.html.erb
- Added ids to the forms
- javascript to keep names from page to page
- details saved when passing between add address page for buyer details
> Temporarily store data to fill in address forms

- app/controllers/concerns/further_competition_concern.rb
- app/controllers/facilities_management/beta/procurements_controller.rb
- app/views/facilities_management/beta/procurements/_further_competition.html.erb
- config/routes.rb
Added a link on the procurement page to down the new excel, for the dummy just a dummy excel is downloaded to prove the flow is working. Downloaded as a single excel.
next steps is to get each worksheet working.
I should have maybe done a new controller for this action, but rushed to get it done.
> outline for further competition excel,just link to download a dummy excel

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/api_test_notifications_controller.rb
- app/services/facilities_management/gov_notify_notification.rb
- config/routes.rb
- spec/services/facilities_management/gov_notify_notification_spec.rb
Gov Notify intergration service
> Gov notify

- app/helpers/facilities_management/buildings_helper.rb
- app/helpers/facilities_management/standard_contract_questions_helper.rb
- app/views/facilities_management/journey/choose_locations.html.erb
- We are now showing nuts 3 for devolved regions when choosing location
- Also removed unneeded helpers
> bug/FM-367 Nuts Regions

- app/helpers/layout_helper.rb
- app/views/facilities_management/beta/procurements/da_buyer/_contract_details.html.erb
- Invoic contact details
- Add the other parts of the page
- Refactor and make page clearer
> Contract details summary page when details completed

- app/views/facilities_management/beta/buyer_account/buyer_account.html.erb
- app/views/facilities_management/beta/sessions/new.html.erb
- app/views/facilities_management/beta/supplier/sessions/new.html.erb
- app/views/facilities_management/sessions/new.html.erb
- config/locales/views/facilities_management.en.yml
Added heading on procurement index page
> Added heading on log in for accesability testing

- app/helpers/application_helper.rb
- app/helpers/errors_helper.rb
- app/views/facilities_management/beta/procurements/long_list/_lot1a.html.erb
- app/views/facilities_management/beta/procurements/long_list/_lot1b.html.erb
- app/views/facilities_management/beta/procurements/long_list/_lot1c.html.erb
- Remove unnecessary error id from application helper 
- Reorganise table
> Remove unnecessary error id from application helper 

- app/controllers/concerns/further_competition_concern.rb
- app/controllers/facilities_management/beta/procurements_controller.rb
- app/services/facilities_management/contract_number_generator.rb
- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- app/services/facilities_management/further_competition_spreadsheet_creator.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- spec/models/facilities_management/summary_report_futher_competition_spec.rb
- spec/services/facilities_management/contract_number_generator_spec.rb
- spec/services/facilities_management/further_competition_spreadsheet_creator_spec.rb
for the generator, the FC is for 3 digits, DA 4 digits.
I will write more unit tests this week, pushing so Akin can test.
> added shortlist worksheet

- app/views/facilities_management/beta/procurement_buildings/show.html.erb
added dl tags to detailed search summary service information page
> added dl tags to the show page of detailed search summary

- app/views/facilities_management/beta/procurement_buildings/_service_hour_summary.html.erb
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
- app/views/facilities_management/beta/procurement_buildings_services/_day_section.html.erb
- app/views/facilities_management/beta/procurements/_about_the_contract.html.erb
- app/views/facilities_management/beta/procurements/_detailed_search_summary.html.erb
- app/views/facilities_management/beta/procurements/contract_period/_contract_period_section.html.erb
- config/locales/views/facilities_management.en.yml
Refactored service information table
Refactored contract period table
> Refactored service information table

- app/services/facilities_management/contract_number_generator.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- spec/services/facilities_management/contract_number_generator_spec.rb
RM3830-FC1843-2020 - 21/02/2020 - 11:15am
> changed back to 4 nights in the shortlist first cell

- app/helpers/facilities_management/beta/procurements_helper.rb
- app/views/facilities_management/beta/procurements/da_buyer/_review_and_generate_documents.html.erb
- spec/helpers/facilities_management/beta/procurements_helper_spec.rb
- Remove back link
- Update to_lower_case method
> Update to_lower_case method

- app/views/facilities_management/beta/supplier/contracts/_accepted_contract_offer.html.erb
- app/views/facilities_management/beta/supplier/contracts/show.html.erb
> FM-249 Supplier Accepted contract summary

- app/controllers/facilities_management/beta/supplier/contracts_controller.rb
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/beta/procurements/contracts/_contract_offer_details.html.erb
- app/views/facilities_management/beta/supplier/contracts/_contract_offer_details.html.erb
- app/views/facilities_management/beta/supplier/contracts/edit.html.erb
- config/locales/views/facilities_management.en.yml
- db/migrate/20200309111231_add_additional_reason_for_closing_contract.rb
- db/schema.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- adding 2 fields on the procurement supplier table
- sent email to buyer when supplier have made a action
> FM-667, GOV notify

- app/controllers/facilities_management/beta/procurements/contracts_controller.rb
- app/helpers/facilities_management/beta/procurements/contracts_helper.rb
- app/helpers/facilities_management/beta/supplier/contracts_helper.rb
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/beta/procurements/contracts/_contract_offer_details.html.erb
- app/views/facilities_management/beta/procurements/contracts/edit.html.erb
- app/views/facilities_management/beta/procurements/contracts/show.html.erb
- Small changes to make pages meet design
- Refactored the procurement_contract page
- Added try catch to stop crashing on local due to not running sidkiq
> FM-526 Closed contract summaries

- app/assets/javascripts/facilities_management/beta/procurement/contract_dates.js
- app/models/concerns/procurement_validator.rb
- config/locales/views/facilities_management.en.yml
locale change, JS validation removal and back-end validations added for contract call off extension periods
> FM-655-call-off-validations

- app/views/facilities_management/beta/supplier/contracts/_contract_offer_details.html.erb
- config/locales/views/facilities_management.en.yml
- Fix content and moved text to translation file
> FM-360 Supplier - Not responded (contract summary)

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/models/concerns/procurement_validator.rb
- app/views/facilities_management/beta/procurement_buildings/_building_standards.html.erb
- app/views/facilities_management/beta/procurement_buildings/_cleaning_standards.html.erb
- app/views/facilities_management/beta/procurement_buildings/_ppm_standards.html.erb
- app/views/facilities_management/beta/procurement_buildings/_volume.html.erb
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
- app/views/facilities_management/beta/procurement_buildings_services/edit.html.erb
- app/views/facilities_management/beta/procurement_buildings_services/show.html.erb
- app/views/facilities_management/beta/procurements/_detailed_search_summary.html.erb
- app/views/facilities_management/beta/procurements/_quick_search_form.html.erb
- app/views/facilities_management/beta/procurements/contracts/_confirmation_of_signed_contract.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_searches.html.erb
- app/views/facilities_management/beta/procurements/edit.html.erb
- app/views/facilities_management/beta/procurements/further_competition/_further_competition_partial.html.erb
- app/views/facilities_management/beta/procurements/shared/_procurement_name_header.html.erb
- db/migrate/20200318140756_merge_quick_search_and_contract_name.rb
- db/migrate/20200318142425_delete_quick_search_name_from_procurements_table.rb
- db/schema.rb
- spec/controllers/facilities_management/beta/procurements_controller_spec.rb
- spec/factories/facilities_management_procurement.rb
- spec/models/facilities_management/procurement_dates_spec.rb
- spec/models/facilities_management/procurement_spec.rb
updated contract names to be quick search names and removed unnecessary columns
replaced quick search name with contract name
altered spec files to match contract name
> FM-853 Merge Quick search and contract name

- app/controllers/facilities_management/beta/procurements/contracts_controller.rb
- app/helpers/application_helper.rb
- app/helpers/facilities_management/beta/procurements/contracts_helper.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/beta/procurements/contracts/_next_supplier.html.erb
- app/views/facilities_management/beta/procurements/contracts/edit.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_spec.rb
- Add tests for contract number and closed date
- Get the contract closed date to save
- Update method to correctly generate contract number
> Update offer_to_next_supplier to set closed date and generate contract number

- app/helpers/facilities_management/beta/procurements/contracts_helper.rb
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/beta/procurements/contracts/_contract_summary_head.html.erb
- app/views/facilities_management/beta/procurements/contracts/edit.html.erb
- app/views/facilities_management/beta/procurements/contracts/show.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_spec.rb
Copy changes for contract summary warnings
Changes to how last offer works
Moved the button to the correct place
> Contract summary and no supplier fixes

- app/assets/stylesheets/application.css
- Update to meet new GDS guidelines
> CSI-73-Radio-Button-Focus

- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- app/assets/javascripts/facilities_management/beta/procurement/ContractDetails.js
- app/assets/javascripts/facilities_management/beta/procurement/FormValidationComponent.js
- app/views/layouts/_init-js.html.erb
- app/views/layouts/errors.html.erb
- public/404.html
- public/422.html
- public/500.html
- public/maintenance.html
Wait on firing JS until the page has loaded
Update JavaScript to remove scripting errors from when the page loads
> Changes to JS to remove errors on IE 11 pages

- app/views/legal_services/admin/uploads/new.html.erb
- app/views/legal_services/admin/uploads/show.html.erb
- app/views/legal_services/gateway/index.html.erb
- app/views/legal_services/home/index.html.erb
- app/views/legal_services/home/service_not_suitable.html.erb
- app/views/legal_services/journey/check_suitability.html.erb
- app/views/legal_services/journey/choose_jurisdiction.html.erb
- app/views/legal_services/journey/choose_organisation_type.html.erb
- app/views/legal_services/journey/choose_regions.html.erb
- app/views/legal_services/journey/choose_services.html.erb
- app/views/legal_services/journey/select_lot.html.erb
- app/views/legal_services/journey/sorry.html.erb
- app/views/legal_services/passwords/edit.html.erb
- app/views/legal_services/passwords/new.html.erb
- app/views/legal_services/passwords/password_reset_success.html.erb
- app/views/legal_services/registrations/domain_not_on_whitelist.html.erb
- app/views/legal_services/registrations/new.html.erb
- app/views/legal_services/sessions/new.html.erb
- app/views/legal_services/suppliers/index.html.erb
- app/views/legal_services/users/_new_password_required.html.erb
- app/views/legal_services/users/_sms_mfa.html.erb
- app/views/legal_services/users/confirm_new.html.erb
buttons on LS have names associated with them to reflect the button text
> ACCESSIBILITY/CSI-88-LS button-names

- app/views/legal_services/home/index.html.erb
- app/views/legal_services/home/service_not_suitable.html.erb
- app/views/legal_services/journey/check_suitability.html.erb
- app/views/legal_services/journey/choose_jurisdiction.html.erb
- app/views/legal_services/journey/choose_organisation_type.html.erb
- app/views/legal_services/journey/choose_regions.html.erb
- app/views/legal_services/journey/choose_services.html.erb
- app/views/legal_services/journey/select_lot.html.erb
- app/views/legal_services/journey/sorry.html.erb
- app/views/legal_services/sessions/new.html.erb
- app/views/legal_services/suppliers/show.html.erb
- Add titles to home and journey
- Add titles to sessions and suppliers
> Page titles for LS

- app/assets/javascripts/facilities_management/beta/procurement/FormValidationComponent.js
- app/assets/stylesheets/components/error-message/_error-message.scss
- app/controllers/facilities_management/beta/admin/supplier_rates_controller.rb
- app/helpers/facilities_management/beta/supplier/supplier_rates_helper.rb
- app/models/facilities_management/admin/rates.rb
- app/views/facilities_management/beta/admin/supplier_rates/supplier_framework_rates.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/facilities_management/beta/admin/supplier_rates_controller_spec.rb
- spec/models/facilities_management/admin/rates_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-862
> Add update and validate to average framework rates page

- app/controllers/facilities_management/beta/buildings_management_controller.rb
- app/controllers/facilities_management/beta/procurement_buildings_controller.rb
- app/controllers/facilities_management/beta/procurements_controller.rb
- app/controllers/facilities_management/buildings_controller.rb
- app/models/facilities_management/building.rb
- app/services/facilities_management/fm_buildings_data.rb
- spec/models/facilities_management/building_spec.rb
Adjusted old model and buildings-management to support new table (use…r_id association, not new fields), so that old site can still operate and no buildings need to be recreated during the transition period.
> FM-869 Legacy buildings-management adjustment to suit new model (user_id)

- app/services/facilities_management/fm_buildings_data.rb
> FM-869-Missing-Code-Changes

- app/controllers/facilities_management/beta/admin/supplier_rates_controller.rb
- app/views/facilities_management/beta/admin/supplier_rates/supplier_benchmark_rates.erb
- app/views/facilities_management/beta/admin/supplier_rates/supplier_framework_rates.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/facilities_management/beta/admin/supplier_rates_controller_spec.rb
Ticket: https://pushback.atlassian.net/secure/RapidBoard.jspa?rapidView=3&projectKey=FM&modal=detail&selectedIssue=FM-871
> FM-871: Add update and validate to call-off benchmarks rates page

- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/components/_all.scss
- app/assets/stylesheets/components/back-link/_back-link.scss
- app/assets/stylesheets/components/button/_button.scss
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/assets/stylesheets/components/checkboxes/checkboxes.scss
- app/assets/stylesheets/components/details/_details.scss
- app/assets/stylesheets/components/footer/_footer.scss
- app/assets/stylesheets/components/header/_header.scss
- app/assets/stylesheets/components/input/input.scss
- app/assets/stylesheets/components/link/link.scss
- app/assets/stylesheets/components/radios/radios.scss
- app/helpers/application_helper.rb
- app/views/facilities_management/beta/procurements/contracts/edit.html.erb
- app/views/facilities_management/beta/procurements/contracts/sent/_no_suppliers.html.erb
- app/views/facilities_management/beta/procurements/contracts/show.html.erb
- app/views/facilities_management/beta/procurements/da_buyer/_contract_details.html.erb
- app/views/facilities_management/beta/procurements/da_buyer/_contract_summary.html.erb
- app/views/facilities_management/beta/supplier/contracts/show.html.erb
Updated assets for backlink
Updated button scss
Update details scss
Update the link and change the link css on some pages
add missing govuk-link to pages
Update the checkboxes css
Update the css for radios
Undo changes to files
Update css for banner links
Updated css for the navigation link
Update css for header and footer links
Input changes
Log the changes and final refactor
> Updated assets to use more up to date GDS CSS

- app/controllers/facilities_management/beta/admin/sublot_services_controller.rb
- app/controllers/facilities_management/beta/admin/supplier_rates_controller.rb
- app/controllers/facilities_management/beta/framework_controller.rb
- app/models/facilities_management/admin/suppliers_admin.rb
- app/views/facilities_management/beta/admin/sublot_services/index.html.erb
- config/routes.rb
- spec/controllers/facilities_management/beta/admin/sublot_services_controller_spec.rb
- spec/models/facilities_management/admin/suppliers_admin_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-874?atlOrigin=eyJpIjoiY2JhNmUyYzUzOGMxNDEyNWE2ZDlhNDk0NzRlYTk1YjYiLCJwIjoiaiJ9
> FM 874 admin sub lot1b services update action

- app/views/auth/_header-banner.html.erb
- app/views/ccs_patterns/_header-banner.html.erb
- app/views/facilities_management/_header-banner.html.erb
- app/views/facilities_management/beta/procurements/_header-banner.html.erb
- app/views/facilities_management/beta/procurements/contracts/_header-banner.html.erb
- app/views/facilities_management/beta/supplier/_header-banner.html.erb
- app/views/layouts/_back-to-start.html.erb
- app/views/layouts/_header-banner.html.erb
- app/views/layouts/admin/_header-banner.html.erb
- app/views/layouts/admin/_header-dashboard-link.html.erb
- app/views/legal_services/_header-banner.html.erb
- app/views/legal_services/admin/_header-banner.html.erb
- app/views/legal_services/sessions/new.html.erb
- app/views/management_consultancy/_header-banner.html.erb
- app/views/management_consultancy/admin/_header-banner.html.erb
- app/views/management_consultancy/sessions/new.html.erb
- app/views/supply_teachers/_header-banner.html.erb
- app/views/supply_teachers/admin/_header-banner.html.erb
Change the location of the navigation role and label
Put the errors in if statement
> CSI-109 accessibility fixes

- app/models/facilities_management/summary_report.rb
- spec/models/facilities_management/summary_report_futher_competition_spec.rb
new logic for assessed value when both framework and benchmark pricing are missing for any services (acceptance criteria B)
> feature/FM-116 further comp logic 1 B

- app/models/facilities_management/admin/rates.rb
- config/locales/en.yml
- spec/models/facilities_management/admin/rates_spec.rb
Tickets:
* https://pushback.atlassian.net/browse/FM-862
* https://pushback.atlassian.net/browse/FM-871
> Allow single digits on rates

- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- app/views/facilities_management/beta/procurements/edit/_invoicing_contact_details.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_authorised_representative_address.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_authorised_representative_details.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_invoicing_address.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_invoicing_contact_details.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_notices_address.html.erb
- app/views/facilities_management/beta/procurements/edit/_new_notices_contact_details.html.erb
accessibility test all passed on Authorised representative details pages
accessibility test all passed on Notices contact details pages
accessibility cover when postcode was enter but no address was selected
> accessibility test all passed on invoicing contact detail pages

- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- app/views/facilities_management/beta/_header-banner.html.erb
- Remove class which caused problem
- Add missing JS that fills in Buyer details
> Fix some issues with links and JS

- app/assets/javascripts/facilities_management/beta/procurement/ProcurementPensionFunds.js
- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/layout_helper.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_pension_fund.rb
- app/views/facilities_management/beta/procurements/edit/_pension_funds.html.erb
- app/views/facilities_management/beta/procurements/edit/_procurement_pension_fund.html.erb
- Fixing of pension page
- The update pension method should function properly
- Capture more of the errors properly
> Fixing of various issues with duplication of pension funds

- app/models/concerns/working_days.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- spec/models/facilities_management/working_days_spec.rb
- Better at take into account BST and fix tests
- Update failing tests
> Consider BST time changes

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/beta/procurements/_results.html.erb
- config/i18n-tasks.yml
- config/locales/views/facilities_management.en.yml
- Added The change copy to the language file
- Generate the correct copy
- make it up to date with 495
- Add the function of the change button
> Copy for the FC results page when un-priced

- app/controllers/facilities_management/beta/procurements_controller.rb
- app/helpers/application_helper.rb
- app/models/concerns/procurement_validator.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/summary_report.rb
- app/views/facilities_management/beta/procurements/_choose_contract_value.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/procurement_validations_spec.rb
- Initial merge of 567 with 495
- Further refinement of page
- Combine pages and add navigation
- Calculate value and validate page
- Finish off the routing and for choose contract value
- Add tests for the validation
- Rubocop fixes and refactoring
- Update exsisitng tests
- Fix routing problem
> FM-567 Further Competition Logic 3

- app/models/ccs/fm/supplier.rb
- app/views/facilities_management/beta/procurements/_filter_data_section.erb
- app/views/facilities_management/beta/procurements/_filter_details.erb
- config/locales/views/facilities_management.en.yml
- spec/models/ccs/fm/supplier_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-857?atlOrigin=eyJpIjoiYzA3NThlNDRlZDk3NDg3MDkzN2U3ZTNkMDI1Zjc1OGYiLCJwIjoiaiJ9
> FM 857 simplify filtering

- app/controllers/ccs_patterns/dbdata_controller.rb
- app/helpers/facilities_management/beta/buildings_helper.rb
- app/views/ccs_patterns/dbdata/index.html.erb
- app/views/facilities_management/beta/buildings/show.html.erb
This is a repair of a change for buildings display for Darren....
> Added robustness to the buildings display for unknown building data

- app/views/facilities_management/beta/procurements/_filter_data_section.erb
Caused by https://github.com/Crown-Commercial-Service/crown-marketplace/pull/1789
> FM-857 Fix regression where service and region codes are not saved

- app/models/facilities_management/procurement_building_service.rb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_building_service_spec.rb
added maximum value logic to procurement building services pages
refactored volume validation method and added tests to service spec
> FM-669 Upper Boundary Validation 

- app/assets/javascripts/facilities_management/beta/procurement/contract_extensions.js
- app/controllers/facilities_management/beta/procurements_controller.rb
- app/models/concerns/procurement_validator.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/beta/procurements/_call_off_extensions.html.erb
- app/views/facilities_management/beta/procurements/_initial_call_off_period.html.erb
- app/views/facilities_management/beta/procurements/_mobilisation_period.html.erb
- app/views/facilities_management/beta/procurements/contract_period/_mobilisation_section.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_dates_spec.rb
- spec/models/facilities_management/procurement_spec.rb
test added
adding condition
refactor mobilisation_start_date_validation
baseline validation for call off extension period, JS inclusive
additional validation, movement of params into controller
testing for validity of call off extensions
more test added
> backend validation fully added for contract period

- app/controllers/facilities_management/beta/admin/sublot_data_services_prices_controller.rb
- app/views/facilities_management/beta/admin/sublot_data_services_prices/index.html.erb
- spec/controllers/facilities_management/beta/admin/sublot_data_services_prices_controller_spec.rb
Fix issue 1 with error banner
Fix issue 2 red bar on the row with errors
Issue 3, able to add null values
Issue 4 validation fixes
I have taken out my changes for issue 5 because I found it didn't work so:
Issue 5 and 6 are still unresolved
> Fix various issues with the admin sublot 1a services page

- app/models/concerns/procurement_validator.rb
- config/locales/views/facilities_management.en.yml
corrected error messages for initial call off start date
> FM-652 Error Messages

- app/views/facilities_management/beta/buyer_details/edit.html.erb
added autocomplete attribute to buyer details page
> FM-982 Autocomplete on Buyer Details

- app/controllers/facilities_management/beta/procurements_controller.rb
Ticket: https://pushback.atlassian.net/browse/FM-952?atlOrigin=eyJpIjoiZjhhNGE3OTI3ZmIxNDU4N2FjNTFhNDYzZTUyYjQ5MWUiLCJwIjoiaiJ9
> Add correct routing for service and region procurement updates

- app/controllers/facilities_management/beta/admin/supplier_rates_controller.rb
Ticket: https://pushback.atlassian.net/browse/FM-921?atlOrigin=eyJpIjoiNDU2ZWEwNzNiNTdjNDczNThkMzE0NjI4NjdjYTAyMDgiLCJwIjoiaiJ9
> Improve efficiency of rate saving

- app/assets/stylesheets/components/header/_header.scss
- app/assets/stylesheets/components/step-by-step-nav/_step-by-step-nav.scss
- app/assets/stylesheets/facilities_management/long_list.scss
- app/views/facilities_management/beta/procurements/_filter_details.erb
- app/views/facilities_management/beta/procurements/long_list/_lot1a.html.erb
- app/views/facilities_management/beta/procurements/long_list/_lot1c.html.erb
Add CSS to enable text when zoomed in
CSS changes for the WHN expandable sections
And media queries for when the page is zoomed
> Various CSS changes for when the text is zoomed

- app/views/layouts/_footer.html.erb
- config/locales/en.yml
- spec/models/facilities_management/procurement_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-1028?atlOrigin=eyJpIjoiY2NmNmM3NTM0YTA0NGI2ODkyMzM3NmE4ZTQ0MzhiYTEiLCJwIjoiaiJ9
> FM 1028: Re-instate missing tel number in footer

- config/locales/views/facilities_management.en.yml
altered error messages for volumes and lifts
> FM-669-Services-Volume-Validation

- app/models/facilities_management/building.rb
- spec/models/facilities_management/building_spec.rb
- Update standard building type text
- Add tests for standard and non standard building types
> FM-1013 Buildings Types are correct for DA

- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- app/views/facilities_management/beta/procurement_buildings/show.html.erb
- app/views/facilities_management/beta/procurements/_call_off_extensions.html.erb
- app/views/facilities_management/beta/procurements/_initial_call_off_period.html.erb
- app/views/facilities_management/beta/procurements/_mobilisation_period.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_closed.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_contracts.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_further_competition.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_in_draft.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_searches.html.erb
- app/views/facilities_management/beta/procurements/dashboard_tables/_sent_offers.html.erb
- app/views/facilities_management/beta/procurements/edit/_contract_name.html.erb
- app/views/facilities_management/beta/procurements/edit/_services.html.erb
- app/views/facilities_management/journey/choose_services.html.erb
- Change the aria tags so they are implemented properly
- Add aria described by to contract name
- Remove method call which deleted data too soon
- Fix issues on the contract period pages
- Remove empty headings on the services page
- Fix issues on the dashboard
> FM-988: Name, Role, Value – Markup To Aid Accessibility

- app/assets/javascripts/facilities_management/beta/procurement/contract_extensions.js
- app/models/concerns/procurement_validator.rb
- app/views/facilities_management/beta/procurements/_call_off_extensions.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_dates_spec.rb
- Update JavaScript to work better
- Add backend validation to prevent any nil values
- Add validation for the period in special cases
- Add tests for the new validations
> Contract period validation error messages

- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/helpers/layout_helper.rb
- app/views/facilities_management/beta/buildings/gia.html.erb
- app/views/facilities_management/beta/buildings/index.html.erb
- app/views/facilities_management/beta/buildings/security.html.erb
- app/views/facilities_management/beta/buildings/type.html.erb
- config/locales/views/facilities_management.en.yml
- data/facilities_management/security_types.csv
Changes for test iteration 2. FM-1018, FM-902, FM-792.
GIA max field length
Layout of other_building and other_security type messages
Layout of index page table
Content adjustment and correction of a typ~e~o
> Buildings test iteration 2

- app/views/facilities_management/beta/procurements/edit/_local_government_pension_scheme.html.erb
- app/views/facilities_management/beta/procurements/edit/_procurement_pension_fund.html.erb
remove duplicated id for name and percentage error
> used display_error for the radio buttons

- app/controllers/facilities_management/beta/procurements_controller.rb
- data/facilities_management/security_types.csv
Also change apostrophes in security types static data to allow for correct static data loading
> Redirect to correct page if user updates services

- yarn.lock
updated yarn.lock after upgarding some new versions of babel
> FM-961-updated-lock-files

- app/views/facilities_management/beta/buildings/index.html.erb
- config/locales/views/facilities_management.en.yml
Updated buildinsg listing page
> FM-1035-FM-Managed-Buildings-Page-Various-content-issues

- app/assets/javascripts/facilities_management/beta/admin/management-report.js
- app/controllers/facilities_management/beta/admin/management_report_controller.rb
- app/models/facilities_management/admin/management_report.rb
- app/views/facilities_management/beta/admin/management_report/index.html.erb
- config/locales/views/facilities_management.en.yml
corrected error messages on management report page and removed errors on valid submit
> FM-929 Management Report Validation 

- app/models/facilities_management/building.rb
- app/views/facilities_management/beta/buildings/type.html.erb
- db/migrate/20200430131751_update_building_types_in_the_db.rb
- db/schema.rb
- spec/factories/facilities_management_building.rb
- spec/models/facilities_management/building_spec.rb
Update building types to use id
Update tests for changes in building type
Add migration to update the building types already in the database
> Update building types to mach rates

- app/assets/stylesheets/application.css
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/assets/stylesheets/facilities_management/beta/building_services.scss
- app/views/facilities_management/beta/procurements/edit/_building_services.html.erb
Update CSS for building button
Change the word break CSS from being global
Update the CSS for the building services secondary buttons
> FM-981 Focus Visible – Visible Tab Focus Indicator 

- Gemfile
- Gemfile.lock
- app/views/supply_teachers/gateway/index.html.erb
- spec/features/authentication.feature_spec.rb
Added omniautth-rails_csrf_protection and upgraded omniauth_openid_connect. Also changed link_to to button_to as it needs to be a post request
> FM-1023 snyk omniauth

- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
on offer being sent
Ticket: https://pushback.atlassian.net/browse/FM-1040?atlOrigin=eyJpIjoiZDE0NTU2NGQ4Zjc2NDFjMzk4ODFjNTgzY2NhYjdjNDAiLCJwIjoiaiJ9
> Bug FM-1040 Make display of contract number and timestamp conditional

- app/models/facilities_management/procurement.rb
- app/models/facilities_management/summary_report.rb
- app/views/facilities_management/beta/procurements/_results.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/summary_report_procurements_spec.rb
- Add logic for the calculation of the assessed value
- Update the results copy
- Add test for Further logic 4
> FM-1039 FC New Logic 4

- app/models/facilities_management/admin/management_report.rb
altered year field on management report to allow years 1-9999
> BUG/FM-929 Audit UI 

- app/services/procurement_csv_export.rb
- spec/services/procurement_csv_export_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-895?atlOrigin=eyJpIjoiZGI4YTZlZGRlNmEzNDEzOWEzMGMxOWY2NzE0ZWJmMGIiLCJwIjoiaiJ9
> Bug FM 895 presentation bugs

- app/assets/stylesheets/components/button/_button.scss
- app/assets/stylesheets/components/typography/_typography.scss
reflow fixed on continuation buttons and buyer account header
> ACCESSIBILITY/FM-971-reflow 

- app/assets/stylesheets/components/button/_button.scss
- app/assets/stylesheets/components/typography/_typography.scss
> reflow fixed on continuation buttons and buyer account header

- app/controllers/facilities_management/beta/admin/supplier_rates_controller.rb
Ticket: https://pushback.atlassian.net/browse/FM-921?atlOrigin=eyJpIjoiNDhlNTc4ZTYwM2I0NGFlYjhmZDQyMDVmMTcwMjlhNDUiLCJwIjoiaiJ9
> FM 921 Apply further performance optimisations to rates update

- app/controllers/facilities_management/beta/admin/suppliers_framework_data_controller.rb
Removed sort by which is depreciated in rails 6
> fix-jsonb-search-depreciated-in-rails-6-method

- app/assets/javascripts/cp/cp-sign-in.js
- app/services/cognito/confirm_password_reset.rb
- app/views/apprenticeships/passwords/edit.html.erb
- app/views/layouts/_password-strength.html.erb
- app/views/legal_services/passwords/edit.html.erb
- app/views/management_consultancy/admin/passwords/edit.html.erb
- app/views/management_consultancy/passwords/edit.html.erb
- app/views/shared/passwords/_edit.html.erb
- app/views/supply_teachers/admin/passwords/edit.html.erb
- app/views/supply_teachers/passwords/edit.html.erb
- config/locales/en.yml
- config/locales/views/facilities_management.en.yml
updated forgot password pages to include number validation
> FM-1042 CP-Login-Hint

- app/services/procurement_csv_export.rb
- spec/services/procurement_csv_export_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-895?atlOrigin=eyJpIjoiYzVjYmUwYWIxZjFlNDNhMmJiNDIxN2Y0YjQ0MWQ3ZmIiLCJwIjoiaiJ9
> FM 895 Refactor line creation to separate, testable methods

- app/assets/javascripts/facilities_management/beta/procurement/contract_extensions.js
- app/assets/stylesheets/application.css
- app/assets/stylesheets/components/_all.scss
- app/assets/stylesheets/components/accordions/accordions.scss
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/assets/stylesheets/components/error-summary/_error-summary.scss
- app/assets/stylesheets/components/input/input.scss
- app/views/facilities_management/beta/procurements/_call_off_extensions.html.erb
- app/views/facilities_management/beta/procurements/_initial_call_off_period.html.erb
- app/views/facilities_management/beta/procurements/_mobilisation_period.html.erb
Add update error CSS for the project
Add textarea CSS focus
Add input error on contract dates page
Add CSS for govuk-select focus
Update accordian CSS
Remove button on the basket CSS
> Add update error and accordion CSS

- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- app/services/facilities_management/further_competition_spreadsheet_creator.rb
Fixed spreadsheet generation for further competition.
> fixed spreadsheet further competition

- app/views/facilities_management/beta/procurements/_no_buildings.html.erb
Removed some erroneous CSS causing a negative margin on layout
> Adjust layout of missing buildings page

- app/services/procurement_csv_export.rb
- spec/services/procurement_csv_export_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-895?atlOrigin=eyJpIjoiYjVjZDQyMGRkM2QyNGRkNGI1N2JmNTU2MzFiNWRlMjUiLCJwIjoiaiJ9
This resolves issues 1, 2, & 3 of the May 5th issues. Remaining issues to be addressed in separate PR(s).
> Bug FM 895 further issues 1

- app/assets/javascripts/facilities_management/beta/contract/copy_procurement.js
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/beta/procurements/copy_procurement/new.html.erb
Fix problem with the validation
Fix JS issue
> FM-1074 Error messages issue

- app/services/procurement_csv_export.rb
Ticket: https://pushback.atlassian.net/browse/FM-895
This resolves issues 5, 6 & 7 of the May 5th issues.
> Bug FM 895 further issues 2

- app/helpers/facilities_management/beta/procurements/documents_procurement_helper.rb
Now security doc only show if yes selected for security policy
> FM-907 Update fix for security policy document downloads even if user selects no

- lib/tasks/ordnance_survey.rb
Ensured OrdanceSurvey tasks, db:postcode, db:update_postcode and db:p…ctable create correct views by dropping existing views first
> FM-1015 Repair postcode views

- app/controllers/facilities_management/supplier/contracts_controller.rb
- app/controllers/facilities_management/supplier/dashboard_controller.rb
- app/controllers/facilities_management/supplier/sent_controller.rb
Make sure the constant is initialised properly
Change how contracts are accessed if the supplier is nil
> Fixes for the Supplier side

- app/services/procurement_csv_export.rb
- spec/services/procurement_csv_export_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-895
This fixes issue 1 & 2 of the May 7th issues.
> Bug FM 895 Further issues 3

- app/services/procurement_csv_export.rb
- spec/services/procurement_csv_export_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-895
> Bug FM 895 further issues 4

- db/migrate/20200508085015_change_record_id_to_be_uuid_in_change_active_storage_attachments.rb
- db/schema.rb
Updated column to UUID active storage
> Updated column record_id to UUID for active storage

- bin/docker-entrypoint.sh
- lib/tasks/migrate_ignore_concurrent.rake
run migration with existing cocurent
> run migration with existing migration

- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- app/views/facilities_management/beta/procurements/contract_period/_contract_extension_section.html.erb
- app/views/facilities_management/beta/procurements/contracts/documents/call_off_schedule.docx.caracal
Remove mobilisation period from deliverable matrix if user selects no
Remove mobilisation period from order form if user selects no
> FM-1106 Mobilisation period not on documents if user selects no

- db/migrate/20200501001023_updatepostcodeviews.rb
Added drop-views to a migration
> Migration Repair for Postcode lookups

- app/assets/stylesheets/components/link/link.scss
- app/controllers/facilities_management/admin/sublot_data_services_prices_controller.rb
- app/views/facilities_management/admin/management_report/index.html.erb
- app/views/facilities_management/admin/sublot_data_services_prices/index.html.erb
- app/views/facilities_management/admin/sublot_regions/sublot_region.html.erb
- app/views/facilities_management/admin/supplier_rates/supplier_benchmark_rates.html.erb
- app/views/shared/sessions/_new.html.erb
- config/locales/views/facilities_management.en.yml
- Update breadcrumb css
- Fix the issues on the benchmark rate page
- Add aria labels to checkboxes
- Update the supplier sublot 1a serives page
- Only show error summary if there are errors
-Fix merge conflicts
> Fix accessibility issue on other admin pages

- db/migrate/20200501001023_updatepostcodeviews.rb
Hotfix added to release/2.1.0, needs merging into master also
> Added drop-views to a migration

- app/assets/javascripts/common/common.js
- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- Updated the JavaScript for the address lookup on the buyer details and the 4 contract details pages to use the v2 API which is the same as buildings.
- Made a change with the JavaScript to prevent an error (as this JS is only for the buyer details page and was being run on the contract details pages)
> Update JS to use the v2 postcode api

- app/views/facilities_management/users/confirm_new.html.erb
- config/locales/views/facilities_management.en.yml
> FM-1069 Change text buyer activate screen

- app/models/facilities_management/procurement_building_service.rb
fixed max limit validation on volumes page
> FM-669 Upper Boundary Limit

- app/helpers/facilities_management/procurements/documents_procurement_helper.rb
Showing original uploaded security policy file.
> Update documents_procurement_helper.rb to return users uploaded file name

- app/controllers/facilities_management/admin/suppliers_framework_data_controller.rb
fix for called with non-attribute argument(s): "data ->'supplier_name' ASC".
> Fix for jsonb now should work on rails 6

- app/models/concerns/procurement_validator.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/beta/procurements/_about_the_work.html.erb
- app/views/facilities_management/beta/procurements/contract_period/_contract_extension_section.html.erb
- app/views/facilities_management/beta/procurements/contract_period/_contract_period_section.html.erb
- app/views/facilities_management/beta/procurements/contract_period/_mobilisation_section.html.erb
- spec/factories/facilities_management_procurement.rb
- spec/models/facilities_management/procurement_spec.rb
Fix issues that caused the page to crash
Fix formatting issues
Update failing specs
> Resolving issues with detailed search summary

- app/assets/javascripts/facilities_management/beta/buildings/buildings.js
FM-1101 Update buildings.js to display regions in text format when user creates a new building
> FM-1101 Update buildings.js to display regions in text format when user creates a new building

- app/models/facilities_management/procurement_supplier.rb
> Hot fix for preview email url address for preview

- app/models/facilities_management/procurement_supplier.rb
Fixes urls should point towards the correct environment in gov notify.
> FM-1119 *Preview Env* Links on email is wrong, it is still pointing to dev env

- app/assets/javascripts/facilities_management/beta/procurement/contract_extensions.js
- app/views/facilities_management/procurements/_initial_call_off_period.html.erb
- app/views/facilities_management/procurements/edit/_estimated_annual_cost.html.erb
- app/views/facilities_management/procurements/edit/_procurement_buildings.html.erb
- config/locales/views/facilities_management.en.yml
made copy changes to various detailed search summary pages
> FM-1125, 1126, 1127, 1133

- app/views/facilities_management/procurements/da_buyer/_contract_details_summary.html.erb
- app/views/facilities_management/procurements/da_buyer/_review_and_generate_documents.html.erb
- app/views/facilities_management/procurements/da_buyer/_review_contract.html.erb
- app/views/facilities_management/procurements/edit/_pension_funds.html.erb
- config/locales/views/facilities_management.en.yml
added copy changes to DA buyer journey
> FM-1153, 1154, 1155

- config/locales/en.yml
- db/schema.rb
Changed confirmation code to verification code. for all
> FM-1069 Changed confirmation code to verification code

- config/locales/views/facilities_management.en.yml
changed email error messages to include valid example to users
> FM-1160 Contact Details Error Copy 

- app/views/facilities_management/procurements/edit/_procurement_buildings.html.erb
- config/locales/views/facilities_management.en.yml
rearranged copy on building allocation page to meet expectations
> FM-1133 Detailed Search Copy Changes

- app/assets/stylesheets/components/step-by-step-nav/_step-by-step-nav.scss
- app/views/facilities_management/admin/sublot_data_services_prices/index.html.erb
- app/views/facilities_management/admin/supplier_rates/supplier_benchmark_rates.html.erb
- app/views/facilities_management/buildings/index.html.erb
- app/views/facilities_management/procurements/da_buyer/_contract_details.html.erb
- app/views/facilities_management/procurements/da_buyer/_contract_details_summary.html.erb
- app/views/facilities_management/procurements/da_buyer/_did_you_know.html.erb
- app/views/facilities_management/procurements/da_buyer/_pricing.html.erb
- app/views/facilities_management/procurements/da_buyer/_procurement_requirements.html.erb
- app/views/facilities_management/procurements/da_buyer/_review_contract.html.erb
- app/views/facilities_management/procurements/da_buyer/_what_next.html.erb
- app/views/facilities_management/procurements/edit/_authorised_representative.html.erb
- app/views/facilities_management/procurements/edit/_invoicing_contact_details.html.erb
- app/views/facilities_management/procurements/edit/_new_authorised_representative_address.html.erb
- app/views/facilities_management/procurements/edit/_new_authorised_representative_details.html.erb
- app/views/facilities_management/procurements/edit/_new_invoicing_address.html.erb
- app/views/facilities_management/procurements/edit/_new_invoicing_contact_details.html.erb
- app/views/facilities_management/procurements/edit/_new_notices_address.html.erb
- app/views/facilities_management/procurements/edit/_new_notices_contact_details.html.erb
- app/views/facilities_management/procurements/edit/_notices_contact_details.html.erb
- app/views/facilities_management/procurements/edit/_procurement_pension_fund.html.erb
- app/views/facilities_management/procurements/edit/_security_policy_document.html.erb
- app/views/facilities_management/supplier/dashboard/_accepted_offers.html.erb
- app/views/facilities_management/supplier/dashboard/_received_offers.html.erb
- Fix the html on the supplier dashboard
- Admin pages html validation
- Contract details part 1
- Pension funds page
- Notices pages html validation
- Authorised pages html validation
- Invoice pages html validation
- Security policy document
- Contract details ii html validation
- Review and generate html validation
- Review contract html validation
- Manage buildings html validation
- Pricing page HTML validation
- What happens next html validation
> FM-1141 HTML Validation

- app/assets/javascripts/common/common.js
- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- Remove county from address lookup JS
- Prevent error when no address selected
> Update how the postcode lookup presents the data

- data/postcode/chunk_postcodes.sh
- lib/tasks/ordnance_survey.rb
Updated script file to parse PISL (PLUS Islands) data as well as the normal PLUS data
Changed the postcode tasks to not truncate the tables anymore.
The data files are up on S3 and will be imported the next time it is run.
> FM-1107 Islands Postcode data

- app/models/facilities_management/service_hour_choice.rb
- app/views/facilities_management/procurement_buildings/_service_hour_summary.html.erb
- config/locales/views/facilities_management.en.yml
shortened days on service requirements page
> FM-1210 Service Hours on Requirements page

- app/assets/javascripts/facilities_management/beta/buildings/buildings.js
- app/views/facilities_management/buildings/_details_form.html.erb
- app/views/facilities_management/buildings/index.html.erb
- app/views/facilities_management/buildings/security.html.erb
- config/locales/views/facilities_management.en.yml
- Fixing the tabbing for add building
- Other building accessibility issues
> FM-1165 Part 1: Buildings Management Tabbing and Accessibility

- app/assets/javascripts/facilities_management/beta/procurement/ChooserComponent.js
- app/views/facilities_management/journey/choose_locations.html.erb
- app/views/facilities_management/journey/choose_services.html.erb
- app/views/facilities_management/procurements/_regions.html.erb
- app/views/facilities_management/procurements/_services.html.erb
- app/views/facilities_management/procurements/edit/_services.html.erb
- config/locales/views/facilities_management.en.yml
> updated regions and services FM-1214

- app/assets/javascripts/facilities_management/beta/procurement/FormValidationComponent.js
- app/controllers/concerns/buildings_controller_regions.rb
- app/views/shared/_error_summary.html.erb
- spec/controllers/facilities_management/buildings_controller_spec.rb
- Fix IE11 issue with the error summary
- Fix error with postcode matches
- Add tests for the method
> Fix IE11 issue with the error summary

- app/assets/javascripts/ccs_character-count/ccs-character-count.js
- app/assets/javascripts/common/common.js
- app/assets/javascripts/common/step-by-step-nav.js
- app/assets/javascripts/cp/cp-sign-in.js
- app/assets/javascripts/cp/old-cp-sign-in.js
- app/assets/javascripts/facilities_management/beta/buildings/buildings.js
- app/assets/javascripts/facilities_management/beta/contract/contract_forms.js
- app/assets/javascripts/facilities_management/beta/contract/copy_procurement.js
- app/assets/javascripts/facilities_management/beta/procurement/ChooseLocationsAssistant.js
- app/assets/javascripts/facilities_management/beta/procurement/ChooseServicesAssistant.js
- app/assets/javascripts/facilities_management/beta/procurement/ChooserComponent.js
- app/assets/javascripts/facilities_management/beta/procurement/FormValidationComponent.js
- app/assets/javascripts/facilities_management/beta/procurement/ProcurementPensionFunds.js
- app/assets/javascripts/facilities_management/beta/procurement/QuickSearchResultsAssistant.js
- app/assets/javascripts/facilities_management/beta/procurement/contract_dates.js
- app/assets/javascripts/facilities_management/beta/procurement/procurement_buildings_services_lifts.js
- app/assets/javascripts/facilities_management/beta/procurement/procurement_buildings_services_volumes.js
- app/assets/javascripts/facilities_management/fm-address.js
- app/assets/javascripts/facilities_management/fm-buildings.js
- app/assets/javascripts/facilities_management/fm-locations.js
- app/assets/javascripts/facilities_management/fm-longList.js
- app/assets/javascripts/facilities_management/fm-services.js
- app/assets/javascripts/facilities_management/fm-standard_contract_questions.js
- app/assets/javascripts/global/global.js
- app/assets/javascripts/legal_services/ls_form_validation.js
- Remove comments from JS pages
- Remove other comments for the JS
- Removed unsued variable and method and comments from code
> Remove comments from JS pages

- app/views/facilities_management/buyer_details/edit.html.erb
- app/views/facilities_management/procurements/edit/_new_contact_details.html.erb
- config/locales/views/facilities_management.en.yml
- Update view for buyer details
- Copy changes for adding address
> Update view for buyer details

- app/models/facilities_management/procurement.rb
method to find building addresses has been made safe
> FM 1086 Management Report Error#500

- app/views/facilities_management/procurements/dashboard_tables/_closed.html.erb
- app/views/facilities_management/procurements/dashboard_tables/_contracts.html.erb
- app/views/facilities_management/procurements/dashboard_tables/_further_competition.html.erb
- app/views/facilities_management/procurements/dashboard_tables/_in_draft.html.erb
- app/views/facilities_management/procurements/dashboard_tables/_searches.html.erb
- app/views/facilities_management/procurements/dashboard_tables/_sent_offers.html.erb
- app/views/facilities_management/procurements/edit/_procurement_buildings.html.erb
- app/views/facilities_management/sessions/new.html.erb
- Change the error banner rendered on the log in page
- Remove scope from table cells that shouldn't have it
- Remove unused id
> Fix accessibility issues on various pages

- app/assets/javascripts/facilities_management/beta/procurement/procurement_buildings_services_service_hours.js
- app/models/facilities_management/service_hour_choice.rb
- spec/models/facilities_management/service_hours_spec.rb
- Change how the time is calculated to take account of midnight
- Update calculation to account for late finishes
- Finessing, addition of test  suite to check daily time calcs
- Fix rubocop issues
- Refactor test suite
- Service hour calculation spec tests
- Refactor and add some new tests
> Service hour refactoring and updates

- app/assets/javascripts/facilities_management/beta/buildings/buildings.js
- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
This enables the full and correct user-interface for the select box on all devices and should be platform-consistent without any Jquery getting in the way.
> FM-1183-Changed the event handler to be on blur, and not change

- app/services/procurement_csv_export.rb
- db/migrate/20200521153053_changeosaddressview2.rb
- db/schema.rb
Added ranked and price csv
and maybe a fix for migration issue.
> FM-1109 Added ranked and price csv

- app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
- app/controllers/facilities_management/buyer_details_controller.rb
Guard against overwriting original postcode if no address is submitted
Added enter-key on postcode box to enable address search
> FM-1193 Protect postcode from be overwritten when no address is selected

- app/assets/javascripts/facilities_management/beta/procurement/procurement_buildings_services_service_hours.js
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/models/facilities_management/service_hour_choice.rb
- app/models/facilities_management/service_hours.rb
- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- app/views/facilities_management/procurement_buildings/_service_hour_summary.html.erb
- app/views/facilities_management/procurement_buildings_services/_day_section.html.erb
- app/views/facilities_management/procurement_buildings_services/_service_hours.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/service_hours_spec.rb
- Write test cases for new validation logic
- Add validation for length of time
- Add validation to make sure the days do not cross over
- Get correct error messages to show
- Updated layout to match sketch
- Rubocop and translation file fixes
- Remove outdated front end validation and update translation
- Update the service times summary
- Update validation on service choice
- Update error messages
- Reconfigure validation process
- Error messages appear in header and link
- Error message tweaks
- Spreadsheet updating
> FM-1228 Service Hours Changes

- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- app/views/facilities_management/procurement_buildings/show.html.erb
- app/views/facilities_management/procurement_buildings_services/_day_section.html.erb
- app/views/facilities_management/procurement_buildings_services/_service_hours.html.erb
- app/views/facilities_management/procurement_buildings_services/edit.html.erb
- app/views/facilities_management/procurements/_about_the_work.html.erb
- app/views/facilities_management/procurements/contract_period/_contract_extension_section.html.erb
- app/views/facilities_management/procurements/contract_period/_contract_period_section.html.erb
- app/views/facilities_management/procurements/contract_period/_mobilisation_section.html.erb
- config/locales/views/facilities_management.en.yml
- Update the style of spread sheet
- HTML Validation for accessibility
- Fix back links on service pages
- HTML validation and accessibility on service summary
> Service hour spreadsheet format and accessibility issues

- app/views/facilities_management/admin/admin_account/admin_account.html.erb
- app/views/facilities_management/admin/supplier_rates/supplier_benchmark_rates.html.erb
- app/views/facilities_management/admin/supplier_rates/supplier_framework_rates.html.erb
Admin dashboard
Average framework rates
> HTML validation on admin pages

- app/controllers/facilities_management/procurements_controller.rb
- app/views/facilities_management/procurements/edit/_building_services.html.erb
also includes fix for 1114 - clear stored services and use the selected ones
> FM-1206 fix

- app/controllers/facilities_management/supplier/sent_controller.rb
- app/views/facilities_management/procurements/contracts/_procurement_requirements.html.erb
- app/views/facilities_management/supplier/contracts/_procurement_requirements_head.html.erb
- app/views/facilities_management/supplier/contracts/edit.html.erb
- app/views/facilities_management/supplier/dashboard/_accepted_offers.html.erb
- app/views/facilities_management/supplier/dashboard/_closed_contracts.html.erb
- app/views/facilities_management/supplier/dashboard/_live_contracts.html.erb
- app/views/facilities_management/supplier/dashboard/_received_offers.html.erb
- Update supplier dashboard
- received offer
- Respond to offer
- Sent validation
- Fix tabbing issue
> Supplier accessibility fixes

- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/components/input-type/_input_type.scss
- config/locales/views/facilities_management.en.yml
- Update CSS for GIA in buildings management to bring it up to date
- Update errors messages translation
> CSS and error message translation update

- app/models/facilities_management/service_hour_choice.rb
- spec/models/facilities_management/service_hours_spec.rb
- Added new tests for specs
- Updated code for new case
> FM-1228 Fix late time issue

- app/controllers/facilities_management/procurements_controller.rb
- app/helpers/facilities_management/procurements_helper.rb
- app/models/facilities_management/procurement_building.rb
- app/views/facilities_management/procurements/edit.html.erb
- app/views/facilities_management/procurements/edit/_building_services.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_building_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- Add tests for exceptions in service code selection
- Add method to do the validation on service selection
- Integrate the model validation into the procurement validation
- Move the validation out of the controller
- Update the views for the change in error
- Update the model and specs for the validation
> FM 1254 Error messages on building services page

- app/views/facilities_management/procurements/da_buyer/_sending_the_contract.html.erb
- config/locales/views/facilities_management.en.yml
> Updated grammar

- app/helpers/facilities_management/procurement_buildings_services_helper.rb
- app/models/facilities_management/service_hour_choice.rb
- app/models/facilities_management/service_hours.rb
- app/views/facilities_management/procurement_buildings_services/_service_hours.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/service_hours_spec.rb
- Not required error is over all periods
- Update validation message on service_period too long
- Update error message on overlap
- Add link helper
- Update views for new error messages
- Change approach for the validation
- Add tests for the error messages and summary
> Update error messages and add tests

- app/helpers/application_helper.rb
- app/views/facilities_management/procurements/_results.html.erb
- config/locales/en.yml
- spec/views/layouts/application.html.erb_spec.rb
updated feedback link and further competition text
> updated feedback link and further competition text FM-1272, FM-1275

- app/views/facilities_management/procurement_buildings/edit.html.erb
Ticket: https://pushback.atlassian.net/browse/FM-637
> Render explicit link back to Service Requirements

- app/models/facilities_management/procurement_supplier.rb
- app/workers/facilities_management/change_state_worker.rb
Reverts Crown-Commercial-Service/crown-marketplace#2191
> Revert "Add Logging for sidekiq issue"

- app/controllers/facilities_management/procurement_buildings_services_controller.rb
- spec/controllers/facilities_management/procurement_buildings_services_controller_spec.rb
- Add tests for show and remove unused method
- Tests for the update method in the controller
> FM 1293 tests for the procurement_building_services controller

- spec/controllers/facilities_management/supplier/dashboard_controller_spec.rb
- spec/controllers/facilities_management/supplier/home_controller_spec.rb
- spec/controllers/facilities_management/supplier/sent_controller_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-1284
> FM 1284: Add more supplier controller specs

- app/views/facilities_management/procurements/edit/_procurement_buildings.html.erb
- config/locales/views/facilities_management.en.yml
added singular building selected reference in manifest and this is translated on front-end
> building selected changes

- app/controllers/facilities_management/procurements_controller.rb
- app/views/facilities_management/procurements/new.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/procurements_controller_spec.rb
- Added the button to the results page
- Add tests for the routing
> Hot fix for missing button on results page

- app/controllers/facilities_management/procurements_controller.rb
- app/views/facilities_management/procurements/new.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/procurements_controller_spec.rb
Added the button to the results page
Add tests for the routing
> FM-1297 Add missing button to QS results page for master

- config/locales/views/facilities_management.en.yml
global name change for service information to service requirements
> name change

- app/services/facilities_management/direct_award_spreadsheet.rb
- spec/services/facilities_management/direct_award_spreadsheet_spec.rb
Ticket: https://pushback.atlassian.net/browse/FM-1274
> FM 1274 Add footnotes to DA spreadsheet

- app/views/facilities_management/home/index.html.erb
- config/locales/views/facilities_management.en.yml
added inset on start page, copy change to bullets.
> copy and layout changes

- app/views/facilities_management/procurement_buildings/_volume.html.erb
- app/views/facilities_management/procurements/edit/_building_services.html.erb
- Add building name to list class
- Add CSS for the volume input
> Add CSS to help with testing

- app/views/facilities_management/buildings/index.html.erb
- config/locales/views/facilities_management.en.yml
Ticket: https://pushback.atlassian.net/browse/FM-1255
> FM 1255: Add procurements dashboard link to manage buildings page

- spec/controllers/facilities_management/buildings_controller_spec.rb
Add new validation tests at view-level
> FM-1282-Improve-Functional-Testing

- spec/controllers/facilities_management/procurements/contracts_controller_spec.rb
- spec/controllers/facilities_management/supplier/contracts_controller_spec.rb
- spec/factories/facilities_management_procurement_supplier.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
> Updated contracts_controller_spec.rb

- app/assets/stylesheets/components/details/_details.scss
- app/assets/stylesheets/components/error-summary/_error-summary.scss
- app/assets/stylesheets/components/table/_table.scss
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building_service.rb
- app/models/facilities_management/service.rb
- app/views/facilities_management/procurements/_about_the_work.html.erb
- app/views/facilities_management/procurements/_detailed_search_summary.html.erb
- spec/models/facilities_management/procurement_spec.rb
- Update css and change some logic on the formatting
- Update error message
- Add the non da services to the calculation methods
- Abstarct the method for if sercie missing rate
- Add tests for the changes
- Add tests for the service code checking methods
- Update model and spec after discussion
> Add the extra unpriced services to the logic

- app/controllers/facilities_management/procurements_controller.rb
- spec/controllers/facilities_management/procurements_controller_spec.rb
> Remove repeated method call

- app/views/facilities_management/procurements/da_buyer/_pricing.html.erb
- app/views/facilities_management/procurements/da_buyer/_what_next.html.erb
- config/locales/views/facilities_management.en.yml
Pricing copy changes
What happens next copy change
> FMFR 85 - DA Copy Changes

- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_building_spec.rb
- Add missing translation
- Add tests for procurement_building_services_present
> BUG - Missing Translation Error

- app/controllers/facilities_management/procurements_controller.rb
- app/models/concerns/procurement_validator.rb
- app/views/facilities_management/procurements/_regions.html.erb
- app/views/facilities_management/procurements/_service_codes_basket.html.erb
- app/views/facilities_management/procurements/_service_codes_checkboxes.html.erb
- app/views/facilities_management/procurements/_services.html.erb
- app/views/facilities_management/procurements/edit.html.erb
- app/views/facilities_management/procurements/edit/_services.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/procurements_controller_spec.rb
- spec/models/facilities_management/procurement_validations_spec.rb
- Update validation to remove error
- Move shared html to partial
- Fix routing and update controller
- Add tests for the model
- Add tests to the procurements controller
> FMFR - 95/109 Service codes issues

- app/views/facilities_management/procurements/contracts/_confirmation_of_signed_contract.html.erb
resolved margin issues to conform with sketch
> FMFR-107-padding

- app/helpers/layout_helper.rb
- app/views/facilities_management/procurements/_choose_contract_value.html.erb
- app/views/facilities_management/procurements/_results.html.erb
- config/locales/views/facilities_management.en.yml
> FMFR-113 detailed search change copy to warning

- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/views/facilities_management/_header-banner.html.erb
- app/views/facilities_management/admin/_header-banner.html.erb
- app/views/facilities_management/supplier/_header-banner.html.erb
- app/views/home/accessibility_statement_fm.html.erb
- app/views/layouts/_footer.html.erb
- config/locales/en.yml
- config/routes.rb
- Add accessibility statement link to page footer
- Create page and update link on footer
- Put text in translation part 1
- Put text in translation part 2
- Put text in translation part 3
- Put text in translation part 4
- Put text in translation part 5
- Put text in translation part 6
- Put text in translation part 7
- Adjust html and routes
- Remove unneeded link
- Update the header banner
> Master: Add accessibility statement link to page footer

- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/views/facilities_management/_header-banner.html.erb
- app/views/facilities_management/admin/_header-banner.html.erb
- app/views/facilities_management/supplier/_header-banner.html.erb
- app/views/home/accessibility_statement_fm.html.erb
- app/views/layouts/_footer.html.erb
- config/locales/en.yml
- config/routes.rb
- Add accessibility statement link to page footer
- Create page and update link on footer
- Put text in translation part 1
- Put text in translation part 2
- Put text in translation part 3
- Put text in translation part 4
- Put text in translation part 5
- Put text in translation part 6
- Put text in translation part 7
- Adjust html and routes
- Remove unneeded link
- Update the header banner
> Hotfix: Add accessibility statement link to page footer

- Gemfile
- Gemfile.lock
- app/controllers/auth_controller.rb
- app/controllers/home_controller.rb
- app/helpers/application_helper.rb
- app/views/facilities_management/_header-banner.html.erb
- app/views/facilities_management/admin/_header-banner.html.erb
- app/views/facilities_management/supplier/_header-banner.html.erb
- app/views/home/accessibility_statement_fm.html.erb
- app/views/layouts/_footer.html.erb
- app/views/supply_teachers/gateway/index.html.erb
- config/locales/en.yml
- config/routes.rb
- data/buyer-email-domains.txt
- spec/features/authentication.feature_spec.rb
- Reverts changes to dfe sign in
- buyer email domains updated with 'wmca.org.uk'
- Accessibility statement added for FM
> Release 3.0.3

- app/helpers/facilities_management/procurements_helper.rb
- app/views/facilities_management/procurements/_detailed_search_summary.html.erb
- app/views/facilities_management/procurements/contract_period/_contract_extension_section.html.erb
- app/views/facilities_management/procurements/contract_period/_contract_period_section.html.erb
- app/views/facilities_management/procurements/contract_period/_mobilisation_section.html.erb
- Update detailed search summary
- Update optional call off html
- Update copy for mobilisation period
- Update copy for initial call off period
> FMFR-125 Contract Period Copy Change

- app/assets/javascripts/facilities_management/beta/procurement/ChooseServicesBuildings.js
- app/assets/javascripts/facilities_management/fm-number-sections.js
- app/assets/stylesheets/_settings.scss
- app/assets/stylesheets/components/input/input.scss
- app/assets/stylesheets/facilities_management/beta/building_services.scss
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/procurements/edit.html.erb
- app/views/facilities_management/procurements/edit/_building_services.html.erb
- app/views/facilities_management/procurements/edit/_estimated_annual_cost.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_spec.rb
- Add new component for pounds
- Add services when a building is selected
- Add JS so the commas become separated when typing in
> FMFR-130/131 Buildings services and EAC changes

- app/services/facilities_management/further_competition_spreadsheet_creator.rb
- spec/services/facilities_management/further_competition_spreadsheet_creator_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-132
> FMFR-132 Add suppliers contact details to FC procurement summary 

- app/views/facilities_management/supplier/contracts/_accepted_contract_offer.html.erb
- app/views/facilities_management/supplier/contracts/_received_contract_offer.html.erb
- app/views/facilities_management/supplier/sent/_accepted_offer.html.erb
- config/locales/views/facilities_management.en.yml
- Add new copy for supplier accepted page
- Add copy for supplier received contract summary
> FMFR-142 New Copy For supplier Contract Summary Pages

- app/assets/stylesheets/facilities_management/service_specification.scss
- app/controllers/facilities_management/service_specification_controller.rb
- app/services/facilities_management/service_specification_parser.rb
- app/views/facilities_management/procurements/_service_codes_checkboxes.html.erb
- app/views/facilities_management/service_specification/_clause.html.erb
- app/views/facilities_management/service_specification/show.html.erb
- config/locales/views/facilities_management.en.yml
- config/routes.rb
- data/facilities_management/service_specifications.csv
- spec/services/facilities_management/service_specification_parser_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-1
> FMFR 1: Service specification links

- app/views/facilities_management/journey/choose_services.html.erb
- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-1
> FMFR 1: Add specification link to choose services screen (to correct omission)

- app/models/facilities_management/procurement.rb
- app/services/procurement_csv_export.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-156
> FMFR 156: Change services column, add type and GIA columns

- app/services/facilities_management/service_specification_parser.rb
- spec/services/facilities_management/service_specification_parser_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-1
> FMFR 1: Service specifications: Improve parsing of poorly formatted data

- app/services/facilities_management/further_competition_spreadsheet_creator.rb
- spec/services/facilities_management/further_competition_spreadsheet_creator_spec.rb
> - Update style and content on FC spreadsheet
> - Add link and remove unused variables
> - Update tests for FC Spreadsheet changes
> FMFR-193 Remove supplier details from shortlist

- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-205
> Bug FMFR 205: Add the word: week

- app/models/ccs/fm/service.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building.rb
- app/views/facilities_management/procurements/_about_the_work.html.erb
- app/views/facilities_management/procurements/_errors_on_show.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_building_spec.rb
- spec/models/facilities_management/procurement_spec.rb
> - Add tests for building area
> - Further tests on required gia
> - Add functionality to model
> - Functionality for the validation
> - Update the validation to stop journey
> - Add the copy for the error messages page
> - Add tests for validating buildings on continue
> - Rearrange the html to make it nicer
> - Only have error message at top as link
> FMFR 204 - Add validations to prevent £0 cost when area 0

- bin/docker-entrypoint.sh
Reverts Crown-Commercial-Service/crown-marketplace#2354
> Revert "Remove concurrent migrations"

- app/helpers/facilities_management/summary_helper.rb
- spec/helpers/facilities_management/summary_helper_spec.rb
> - Remove unused parts of method
> - Update tests
> Fix for 500 error

- app/assets/stylesheets/facilities_management/buyer-account.scss
- app/views/facilities_management/buyer_account/buyer_account.html.erb
- config/locales/views/facilities_management.en.yml
copy and design changes
updated design
> updated design

- app/controllers/facilities_management/procurements_controller.rb
- app/helpers/facilities_management/procurements_helper.rb
- app/services/facilities_management/delete_procurement.rb
- app/views/facilities_management/procurements/_continue_button_footer.html.erb
- app/views/facilities_management/procurements/_delete_procurement.html.erb
- app/views/facilities_management/procurements/_detailed_search_summary.html.erb
- app/views/facilities_management/procurements/dashboard_tables/_in_draft.html.erb
- app/views/facilities_management/procurements/dashboard_tables/_searches.html.erb
- app/views/facilities_management/procurements/edit.html.erb
- app/views/facilities_management/procurements/index.html.erb
- app/views/facilities_management/procurements/show.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/procurements_controller_spec.rb
- spec/services/facilities_management/delete_procurement_spec.rb
> - Add functionality to delete procurement
> - Add functionality to delete procurement
> - amended pages to show error summary, yaml fix
> - updated copy
> - tests
> - updating tests
> - Further test updates
> - Update tests further for coverage
> FMFR 190 Add functionality to delete procurement

- app/assets/stylesheets/application.css
- app/assets/stylesheets/components/tag/_tag.scss
- app/helpers/application_helper.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/procurements/_about_the_contract.html.erb
- app/views/facilities_management/procurements/_detailed_search_summary.html.erb
- config/i18n-tasks.yml
- config/locales/en.yml
- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-212
> FMFR 212: Restyle first section of detailed search summary page

- app/models/facilities_management/procurement.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-212
> FMFR 212: Remove conditionality between tasks

- app/views/legal_services/journey/choose_services.html.erb
> CSI-101-LS-Accessibility

- app/helpers/application_helper.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-212
> FMFR 212 Change colour of 'not started' tag

- app/controllers/facilities_management/admin/sublot_data_services_prices_controller.rb
- app/controllers/facilities_management/admin/sublot_services_controller.rb
- app/models/facilities_management/admin/suppliers_admin.rb
- db/migrate/20200807080425_convert_nil_supplier_data_to_empty_array.rb
- db/schema.rb
- spec/models/facilities_management/admin/suppliers_admin_spec.rb
> - Add methods to replace nil with []
> - Add tests for the saving the sublot data
> - Solve similar issue for lot 1a
> - Add migration to fix broken data
> FMFR 231 error when all services or regions unticked

- app/controllers/facilities_management/admin/sublot_data_services_prices_controller.rb
- app/controllers/facilities_management/admin/sublot_services_controller.rb
- app/models/facilities_management/admin/suppliers_admin.rb
- db/migrate/20200807080425_convert_nil_supplier_data_to_empty_array.rb
- db/schema.rb
- spec/models/facilities_management/admin/suppliers_admin_spec.rb
> - Add methods to replace nil with []
> - Add tests for the saving the sublot data
> - Solve similar issue for lot 1a
> - Add migration to fix broken data
> PRODUCTION - FMFR-232 error when all services or regions unticked

- app/assets/javascripts/ccs_character-count/ccs-character-count.js
- app/controllers/facilities_management/procurements/spreadsheet_imports_controller.rb
- app/models/facilities_management/building.rb
- app/services/facilities_management/spreadsheet_importer.rb
- spec/factories/spreadsheet_imports.rb
- spec/models/facilities_management/building_spec.rb
- spec/rails_helper.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
- spec/support/spreadsheet_import_helper.rb
> - Create the methods to import and save the building data
> - Add tests for duplication of building names
> - Do initial set up for the tests
> - Further preparation for the tests
> - Tests for the first describe method
> - Add tests for the building_name
> - Add the tests for description address_line_1
> - Add tests for postcodes and for address_line_1
> - Add tests and updates for building type
> - Add additional tests for building type and security
> - Add tests for security type
> - Adjustment for gia and external area
> - Add tests for changing regions
> - fix issues with rubocop
> - Refactor of methods
> - Refactor and reorder spec and methods
> - Refactor and add tests for completeness
> - Change method for security types
> - Update tests to create tmp file
> - Change method for …
> Create the methods to import and save the building data

- app/models/facilities_management/building.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
Add tests for the building type
> FMFR 218 - Fix for the issue with building types

- app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb
- spec/services/facilities_management/deliverable_matrix_spreadsheet_creator_spec.rb
> - Fix issue for when there a procurement with services other than service_hours
> - Add tests for when the service hours are many
> - Allow stuck procurements to return to results
> Issue with spreadsheet creation

- app/models/facilities_management/procurement_building.rb
- app/services/facilities_management/spreadsheet_importer.rb
- app/views/facilities_management/procurements/_spreadsheet.html.erb
- spec/models/facilities_management/procurement_building_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
- spec/support/spreadsheet_import_helper.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-219
> FMFR 219 Import services matrix

- app/models/facilities_management/procurement_building_service.rb
- app/services/facilities_management/spreadsheet_importer.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
- spec/support/spreadsheet_import_helper.rb
> - Add import of service hours
> - Check validations of procurement building services
> - Setup for testing the service hours import
> - Update how data is saved
> - Add tests for importing service hours
> - Sanatize the input string that will be formatted
> - Add tests for the validation of the data
> - Add validations for service volumes and refactor
> - Update the tests for lifts
> - Test that the data is saved correctly
> FMFR-222 Service Hours Import

- app/assets/stylesheets/components/tag/_tag.scss
- app/helpers/application_helper.rb
- app/models/facilities_management/spreadsheet_import.rb
- app/views/facilities_management/procurements/spreadsheet_imports/_importing.html.erb
- app/views/facilities_management/procurements/spreadsheet_imports/_upload_status.html.erb
- app/views/facilities_management/procurements/spreadsheet_imports/show.html.erb
> - Update status tags
> - Update the css for the buildings
> FMFR-216 Import in progress page

- app/services/facilities_management/spreadsheet_importer.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-246
> FMFR 246: Unexpected template error when duplicate building

- spec/controllers/facilities_management/procurement_buildings_services_controller_spec.rb
> - Add tests for the controller for Number of tonnes
> - Add tests for the controller for Number of units
> FMFR-237/238 - Service Volume - Number of tonnes/units

- spec/controllers/facilities_management/procurement_buildings_services_controller_spec.rb
Add tests for Number of consoles
Add tests for Number of occupants
> FMFR-235/236 - Service Volume - Number of occupants/consoles

- app/models/facilities_management/procurement_building_service.rb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_building_service_spec.rb
Change error messages
Add and refactor tests to clean up spec
> FMFR - 234 - Service Volume Error Messages

- app/assets/stylesheets/facilities_management/procurement_summary.scss
- app/helpers/application_helper.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/procurements/_about_the_contract.html.erb
- app/views/facilities_management/procurements/_about_the_work.html.erb
- app/views/facilities_management/procurements/_continue_button_footer.html.erb
- app/views/facilities_management/procurements/_detailed_search_summary.html.erb
- app/views/facilities_management/procurements/summary/_procurement_buildings.html.erb
- app/views/facilities_management/procurements/summary/_service_requirements.html.erb
- app/views/facilities_management/procurements/summary/_services.html.erb
- config/locales/en.yml
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-264
> FMFR 264 Restyle procurement summary page (part 2)

- app/assets/javascripts/facilities_management/beta/procurement/ChooseServicesBuildings.js
- app/helpers/facilities_management/procurements_helper.rb
- app/models/facilities_management/procurement.rb
- app/services/facilities_management/procurement_router.rb
- app/views/facilities_management/procurements/_about_the_work.html.erb
- app/views/facilities_management/procurements/edit.html.erb
- app/views/facilities_management/procurements/edit/_buildings_and_services.html.erb
- app/views/facilities_management/procurements/summary.html.erb
- app/views/facilities_management/procurements/summary/_buildings_and_services.html.erb
- app/views/facilities_management/procurements/summary/_contract_period.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/procurements_controller_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/services/facilities_management/procurement_router_spec.rb
> - Set up the routing
> - Create the summary page
> - Move text to the translation file
> - Update the edit page for adding services to buildings
> - Change buttons
> - Add tests for the controller and router
> - Rebase with master
> FMFR-175 - Assigning Services to procurement's Buildings

- app/controllers/facilities_management/procurements_controller.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building.rb
- app/services/facilities_management/procurement_router.rb
- app/views/facilities_management/procurements/edit.html.erb
- app/views/facilities_management/procurements/summary/_buildings_and_services.html.erb
- spec/controllers/facilities_management/procurements_controller_spec.rb
- spec/models/facilities_management/procurement_building_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/services/facilities_management/procurement_router_spec.rb
> - Change building_services to buildings_and_services
> - Change building_services to buildings_and_services in specs
> - Fix spec with router
> FMFR-175 - Fix issues with validations and routing

- app/controllers/facilities_management/procurements/spreadsheet_imports_controller.rb
- app/controllers/facilities_management/procurements_controller.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/spreadsheet_import.rb
- app/views/facilities_management/procurements/dashboard_tables/_searches.html.erb
- app/views/facilities_management/procurements/spreadsheet_imports/_upload.html.erb
- app/views/facilities_management/procurements/spreadsheet_imports/show.html.erb
- db/migrate/20200827112653_remove_extra_spreadsheet_imports.rb
- db/schema.rb
- spec/controllers/facilities_management/procurements_controller_spec.rb
- spec/models/facilities_management/spreadsheet_import_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Add extra state and refactor errors
> - Change from has_many to has_one
> - Add migration to remove excess imports
> - Delete spreadsheet_import when a new one is started
> - Change routes for one upload is not in progress
> - Change routing so pages are not repeated
> - Add tests for new controller routing
> - Change so state only changes on save
> - Fix spreadsheet importer test
> FMFR-233 Change to has_one and other routing changes

- app/controllers/facilities_management/procurement_buildings_services_controller.rb
- app/helpers/facilities_management/procurement_buildings_services_helper.rb
- app/views/facilities_management/buildings/_area.html.erb
- app/views/facilities_management/buildings/gia.html.erb
- app/views/facilities_management/procurement_buildings_services/_area.html.erb
- app/views/facilities_management/procurement_buildings_services/edit.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/procurement_buildings_services_controller_spec.rb
> - Create layout for page
> - Add validation of the area
> - Add tests for validating the areas
> - Move text to translation file
> - Removal of incorrect method
> - Add tests in the controller
> - Add error messages
> FMFR-195 - Add or edit procurement's Building size

- app/controllers/facilities_management/procurements_controller.rb
- app/views/facilities_management/procurements/_service_codes_checkboxes.html.erb
- app/views/facilities_management/procurements/edit.html.erb
- app/views/facilities_management/procurements/edit/_services.html.erb
- app/views/facilities_management/procurements/summary/_services.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/procurements_controller_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-243
> FMFR 243 add edit procurement services

- app/services/facilities_management/spreadsheet_importer.rb
- spec/controllers/facilities_management/procurements/spreadsheet_imports_controller_spec.rb
- spec/factories/facilities_management_procurement_spreadsheet_import.rb
- spec/models/facilities_management/spreadsheet_import_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Add the ability to import with gaps
> - Abstract some of the building validation
> - Abstract the import method loop DRY
> - Clean up method to find last complete
> - Add tests for uploading with gaps
> - Set up controller spec for spreadsheet_import
> - Add tests for the controller on create
> - Add tests for the importing method
> FMFR-260 - Allow upload of spreadsheet containing unused Building columns

- app/helpers/application_helper.rb
- app/helpers/facilities_management/buildings_helper.rb
- app/models/facilities_management/building.rb
- app/views/facilities_management/buildings/type.html.erb
- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-2
> FMFR 2 Add building type help text

- app/models/facilities_management/procurement_building.rb
- spec/models/facilities_management/procurement_building_spec.rb
When Uploading 400 buildings, I noticed that some services said incomplete despite that not being the case.
This PR updates the method to check first to see if any services need a service question and then ask if all the service questions are answered
> Fix issue with 'complete?' method when services did not require service question

- app/helpers/layout_helper.rb
- app/views/facilities_management/buildings/security.html.erb
- app/views/facilities_management/buildings/type.html.erb
- app/views/facilities_management/procurement_buildings_services/_service_hours.html.erb
- app/views/facilities_management/procurements/_call_off_extensions.html.erb
- app/views/facilities_management/procurements/edit/_contract_name.html.erb
- app/views/facilities_management/procurements/spreadsheet_imports/_upload.html.erb
> - Add missing form labels
> - Fix issues with aria
> FMFR-271/273 - Various accessibility issues

- app/models/facilities_management/procurement_building.rb
- app/models/facilities_management/procurement_building_service.rb
- spec/models/facilities_management/procurement_building_service_spec.rb
- spec/models/facilities_management/procurement_building_spec.rb
Take account of services without unit of measure
Create test for the new method
> FMFR-288 - Issue when some service didn't require a unit of measure

- app/assets/javascripts/facilities_management/beta/procurement/procurement_buildings_services_lifts.js
- app/controllers/facilities_management/procurement_buildings_services_controller.rb
- app/helpers/facilities_management/procurement_buildings_services_helper.rb
- app/models/facilities_management/procurement_building_service.rb
- app/models/facilities_management/procurement_building_service_lift.rb
- app/services/facilities_management/spreadsheet_importer.rb
- app/views/facilities_management/procurement_buildings_services/_lift.html.erb
- app/views/facilities_management/procurement_buildings_services/_lifts.html.erb
- app/views/facilities_management/procurement_buildings_services/edit.html.erb
- config/locales/views/facilities_management.en.yml
- db/migrate/20200901103422_add_lifts_as_nested_attribute.rb
- db/migrate/20200901105149_migrate_lift_data_to_new_model.rb
- db/schema.rb
- db/seeds.rb
- spec/controllers/facilities_management/procurement_buildings_services_controller_spec.rb
- spec/factories/facilities_management_lift.rb
- spec/models/facilities_management/procurement_building_service_lift_spec.rb
- spec/models/facilities_management/procurement_building_service_spec.rb
- spec/models/facilities_management/procurement_building_spec.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- spec/models/facilities_management/summary_report_futher_competition_spec.rb
- spec/models/facilities_management/summary_report_procurements_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Create a nested lifts model
> - Add migration for lifts nested attribute
> - Create initial layouts
> - Add JS for the lifts page
> - Add validation and saving for lifts
> - Adjust lift_data
> - Add test for lifts
> - Update tests for changes in lift data
> - Adjust migration to restore deleted data
> - Update tests for changes to lift data
> - Fix other broken specs
> - Update JS and change Lift_data
> FMFR-292 - Migrate lift_data to use nested attributes

- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-264
> Bug FMFR 264 Change title of former procurements summary page

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/components/pagination/_pagination.scss
- app/controllers/concerns/buildings_controller_definitions.rb
- app/controllers/facilities_management/buildings_controller.rb
- app/models/facilities_management/building.rb
- app/views/facilities_management/buildings/_details_form.html.erb
- app/views/facilities_management/buildings/index.html.erb
- app/views/facilities_management/buildings/show.html.erb
- config/initializers/pagination.rb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/building_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
- spec/views/supply_teachers/suppliers/all_suppliers.html.erb_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-275
> FMFR 275 Design updates and copy changes for buildings page

- app/models/facilities_management/procurement_building.rb
- spec/models/facilities_management/procurement_building_spec.rb
- Issue with valid on continue because of lifts
> FMFR-297 User cannot progress to results

- db/migrate/20200908110404_set_governing_law.rb
- db/schema.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-277
> Feature FMFR 277 Retrospectively set governing law

- db/migrate/20200908144817_add_other_building_type_and_other_security_type_to_procurement_buildings.rb
Pulling procurement buildings in batches rather than all at once to perform the update
> Migration fix

- app/helpers/application_helper.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/procurements/_about_the_work.html.erb
- config/locales/en.yml
- spec/models/facilities_management/procurement_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-300
> FMFR 300 Detailed search summary as a task list IV - Service requirements not required

- app/views/facilities_management/procurements/summary/_buildings.html.erb
number of buildings in separate div
> automation fix

- app/assets/javascripts/facilities_management/beta/buildings/buildings.js
- app/views/facilities_management/buildings/_building_details.html.erb
> - Add id for find address link
> FMFR-318 - Address/Region dropdown is visible after user selects an address

- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/building_spec.rb
- spec/models/facilities_management/procurement_building_service_lift_spec.rb
> - Add error messages for lifts
> - Add error messages for the gia and external area
> FMFR-298-299 - Error messages for not a number

- app/controllers/concerns/buildings/buildings_controller_definitions.rb
- app/controllers/concerns/journey_controller_actions.rb
- app/controllers/facilities_management/procurements_controller.rb
- app/helpers/facilities_management/procurements/contracts_helper.rb
- app/helpers/facilities_management/supplier/contracts_helper.rb
- app/models/generic_journey.rb
- app/views/facilities_management/buyer_details/edit.html.erb
- app/views/facilities_management/buyer_details/edit_address.html.erb
- app/views/facilities_management/procurements/da_buyer/_contract_details.html.erb
- app/views/facilities_management/procurements/da_buyer/_did_you_know.html.erb
- app/views/facilities_management/procurements/da_buyer/_pricing.html.erb
- app/views/facilities_management/procurements/da_buyer/_what_next.html.erb
- app/views/layouts/_back-link.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/buildings_controller_spec.rb
- spec/controllers/facilities_management/procurements_controller_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-303
> FMFR 303 Normalise building backlinks

- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/building_spec.rb
- spec/models/facilities_management/procurement_building_service_lift_spec.rb
> - Add missing error for lifts
> - Correct error for external area
> FMFR-298-299 - Add some missing errors

- app/controllers/concerns/buildings/buildings_controller_definitions.rb
- app/controllers/facilities_management/procurements_controller.rb
- app/views/facilities_management/procurements/_quick_search.html.erb
- app/views/facilities_management/procurements/index.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/buildings_controller_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-303
> Feature FMFR 303 Add further backlink normalisations

- app/models/concerns/procurement_validator.rb
- app/models/facilities_management/building.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building.rb
- app/views/facilities_management/procurements/summary/_buildings_and_services.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/building_spec.rb
- spec/models/facilities_management/procurement_building_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/procurement_validations_spec.rb
> - Incomplete based on selection
> - Add tests for the building and services completeness
> - Add validations for the service code selection in services
> - Change address used for buildings and services
> FMFR-301 - Validations on service selection

- app/views/facilities_management/journey/choose_locations.html.erb
- app/views/facilities_management/journey/choose_services.html.erb
- app/views/facilities_management/procurements/edit.html.erb
- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-322
> Feature FMFR 322 Quick view journey copy changes

- app/views/facilities_management/procurements/edit/_buildings.html.erb
- config/locales/views/facilities_management.en.yml
> - Add detail text for how it works
> FMFR-328 - Procurement buildings how it works

- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/controllers/facilities_management/procurements_controller.rb
- app/views/facilities_management/procurements/kaminari/_page.html.erb
- app/views/facilities_management/procurements/summary/_service_requirements.html.erb
- app/views/shared/kaminari/_page.html.erb
> - Add pagination to the service requirements summary page
> - Tweek pagination for accessibility
> FMFR-334 - Pagination of Service requirements summary page 

- app/models/facilities_management/procurement_building_service.rb
- spec/factories/facilities_management_procurement.rb
- spec/factories/facilities_management_procurement_building_services.rb
- spec/factories/facilities_management_procurement_buildings.rb
- spec/models/facilities_management/procurement_copy_spec.rb
> - Add test for copying lifts
> - Add copying of lifts
> - Small refactor of factory
> FMFR-335 - loss of lift data when copying requirements

- app/views/facilities_management/procurement_buildings/show.html.erb
- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-337
> Feature FMFR 337 Service requirements page when Service standards section is empty

- app/models/facilities_management/building.rb
- app/models/facilities_management/spreadsheet_import.rb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/building_spec.rb
- spec/models/facilities_management/spreadsheet_import_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Allow upload to transition from other states
> - Add test for size of gia and external_area
> - Add validation for the area size
> FMFR-201 - Issues with the spreadsheet import

- app/models/facilities_management/spreadsheet_import.rb
- app/services/facilities_management/spreadsheet_importer.rb
- spec/models/facilities_management/spreadsheet_import_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Re-impliment spreadsheet template validation
> - Refactor tests for template validation
> FMFR-399 - Move template validation back to front end

- app/services/procurement_csv_export.rb
Tickets:
- https://crowncommercialservice.atlassian.net/browse/FMFR-340
- https://crowncommercialservice.atlassian.net/browse/FMFR-341
> Feature 340/341 Admin management report: Status changes. New bulk upload status column

- app/models/facilities_management/spreadsheet_import.rb
- app/views/facilities_management/procurements/spreadsheet_imports/error_partials/_service_volume_errors.html.erb
- config/locales/views/facilities_management.en.yml
- spec/helpers/facilities_management/procurements/spreadsheet_imports_helper_spec.rb
- spec/models/facilities_management/spreadsheet_import_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Fix copy error and add small functionality
> - Fix tests for bulk upload
> - Add tests to view errors and correct error copy
> FMFR-201 - fix error copy issues

- app/services/procurement_csv_export.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-341
> Feature FMFR 341: Show historical upload status for any procurement stage

- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building.rb
- app/services/facilities_management/services_and_questions.rb
- app/services/procurement_csv_export.rb
- spec/models/facilities_management/procurement_spec.rb
> - Add some optimisation for the csv export
> - Add some tests for building_data_frozen
> - Further improvements for supplier name
> FMFR-349 - Improvements to CSV export

- app/controllers/concerns/buildings/buildings_controller_navigation.rb
- app/controllers/concerns/buildings/buildings_controller_regions.rb
- app/controllers/concerns/facilities_management/procurements/edit_buildings_controller_navigation.rb
- app/controllers/concerns/shared_buildings_controller_methods.rb
- app/controllers/facilities_management/buildings_controller.rb
- app/controllers/facilities_management/procurements/edit_buildings_controller.rb
> - Fix issue where single region does not resolve
> - Move shared methods into single class
> - Remove unused methods form controllers
> Fix issue where single region does not resolve

- app/controllers/facilities_management/procurements_controller.rb
- app/views/facilities_management/procurements/spreadsheet_imports/new.html.erb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-351
> Bug FMFR 351 Fix circular routing for failed and in progress bulk uploads

- Dockerfile
- bin/docker-entrypoint.sh
Running ngnx from docker-entrypoint.sh with 'daemon on;'
> Applying working ngnx changes

- app/models/facilities_management/spreadsheet_import.rb
- app/services/facilities_management/spreadsheet_importer.rb
- spec/models/facilities_management/spreadsheet_import_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Account for when there are gaps in the building
> - Update test for new way of import
> FMFR-201 - collect errors for gaps in buildings

- app/models/facilities_management/procurement.rb
- app/services/procurement_csv_export.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-357
> Feature FMFR 357 Include standards with unpriced services

- app/controllers/facilities_management/buyer_details_controller.rb
- app/helpers/layout_helper.rb
- app/models/facilities_management/buyer_detail.rb
- app/models/facilities_management/procurement_contact_detail.rb
- app/views/facilities_management/buyer_details/edit.html.erb
- app/views/facilities_management/buyer_details/edit_address.html.erb
- config/routes.rb
- spec/controllers/facilities_management/buyer_details_controller_spec.rb
- spec/controllers/facilities_management/procurements_controller_spec.rb
- spec/models/facilities_management/buyer_detail_spec.rb
> - Fix some issues with the controller and error order
> - Use form filed to reduce some complexity
> - Refactor tests and controller
> - Add some validations to limit size of input
> FMFR-361 - Fix some issues with the controller and error order

- app/controllers/facilities_management/buyer_details_controller.rb
- app/controllers/facilities_management/framework_controller.rb
- app/models/user.rb
- spec/controllers/facilities_management/buildings_controller_spec.rb
- spec/controllers/facilities_management/buyer_account_controller_spec.rb
- spec/controllers/facilities_management/buyer_details_controller_spec.rb
- spec/controllers/facilities_management/gateway_controller_spec.rb
- spec/controllers/facilities_management/procurement_buildings_controller_spec.rb
- spec/controllers/facilities_management/procurement_buildings_services_controller_spec.rb
- spec/controllers/facilities_management/procurements/contracts/sent_controller_spec.rb
- spec/controllers/facilities_management/procurements/contracts_controller_spec.rb
- spec/controllers/facilities_management/procurements/edit_buildings_controller_spec.rb
- spec/controllers/facilities_management/procurements/spreadsheet_imports_controller_spec.rb
- spec/models/user_spec.rb
> - Change how we redirect to fill out buyer details
> - Add some tests for when logging on without details
> - Add some more tests for when logging on without details
> - Add some tests for when logging on without details under procurements
> Change how we redirect to fill out buyer details

- app/services/facilities_management/spreadsheet_importer.rb
- config/locales/views/facilities_management.en.yml
- spec/helpers/facilities_management/procurements/spreadsheet_imports_helper_spec.rb
> - Change way of checking for missing lifts
> - Change the error message
> FMFR-201 - bulk upload failed - change lift error

- app/services/facilities_management/spreadsheet_importer.rb
> - Convert to_i to take account of nil
> FMFR-201 - fix error and catch any errors

- app/views/facilities_management/procurements/edit/_tupe.html.erb
- config/locales/views/facilities_management.en.yml
> - FMFR-364 - change copy on links
> - FMFR-365 - copy change on requirements
> - FMFR-366 re add link on TUPE
> FMFR-364/5/6 - BAT various changes

- app/helpers/facilities_management/procurements_helper.rb
- app/models/concerns/procurement_validator.rb
- app/models/facilities_management/building.rb
- app/models/facilities_management/procurement.rb
- app/services/facilities_management/spreadsheet_importer.rb
- app/views/facilities_management/procurements/show.html.erb
- app/views/facilities_management/procurements/spreadsheet_imports/new.html.erb
- spec/helpers/facilities_management/procurements_helper_spec.rb
- spec/models/facilities_management/building_spec.rb
- spec/models/facilities_management/procurement_spec.rb
> - Make sure checking of building regions is done on continue
> - Add test for valid on continue
> - Make sure the region code is validated
> FMFR-367 - prevent procurements with missing regions from continuing

- config/locales/views/facilities_management.en.yml
> - FMFR-373 - fix copy on service requirements
> - FMFR-374 - fix copy on buildings page
> - FMFR-375 - fix copy on lifts page
> FMFR-373/4/5 - Copy changes from BAT

- app/helpers/facilities_management/procurement_buildings_helper.rb
- app/models/facilities_management/procurement_building.rb
- app/models/facilities_management/procurement_building_service.rb
- app/views/facilities_management/procurement_buildings/_errors_on_show.html.erb
- app/views/facilities_management/procurement_buildings/show.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_building_spec.rb
- spec/services/facilities_management/procurement_router_spec.rb
> - Change how errors are displayed for gia and external area
> - Update specs and page layout
> - Refactor some tests for new method
> FMFR-371 - Fix issue with GIA errors showing and preventing save

- app/models/facilities_management/building.rb
- spec/models/facilities_management/building_spec.rb
> - Fix issue with error wrong error message
> - Add tests to make sure correct error message appears
> FMFR-367 - fix issue with error message

- app/services/procurement_csv_export.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-358
> Bug FMFR 358 Fix bug where procurement building has no building type

- config/locales/views/facilities_management.en.yml
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-391
> Bug FMFR 391 Correct wrong case in file name

- app/views/facilities_management/_header-banner.html.erb
- app/views/facilities_management/buyer_details/edit.html.erb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-397
> Feature FMFR 397 Hide links to account while buyer details incomplete

- app/views/facilities_management/_header-banner.html.erb
- app/views/facilities_management/buyer_details/edit.html.erb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-397
> Bug FMFR 397 Allow for nil current_user

- app/models/concerns/procurement_validator.rb
- app/models/facilities_management/building.rb
- app/models/facilities_management/procurement_pension_fund.rb
- spec/models/facilities_management/building_spec.rb
> - Prevent building with the same names being saved
> - Add new method in other locations
> FMFR-401 - prevent buildings being saved with excess spaces

- app/helpers/facilities_management/procurements_helper.rb
- app/views/facilities_management/procurements/edit/_buildings.html.erb
- app/views/facilities_management/procurements/requirements/_contract_summary_table.html.erb
- config/locales/views/facilities_management.en.yml
> - Change for aria label to aria described by
> - Fix html validations for the page
> FMFR-420 - HTML validations and other accessibility issues

- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/building_spec.rb
> - Change error message
> - Add tests to make sure correct error messages are shown
> FMFR-414 change error copy for the address town

- app/views/facilities_management/procurement_buildings/_buildings_and_services.html.erb
- app/views/facilities_management/procurements/summary/_buildings_and_services.html.erb
- config/locales/views/facilities_management.en.yml
> - Add link on Assigning services to buildings summary
> - Add link on Assigning services to buildings
> FMFR-417 - Add links to help texts under 'Assigning services to buildings'

- app/models/facilities_management/procurement.rb
- app/services/procurement_csv_export.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-357
> Bug FMFR 357 Broaden scope of service codes and standards

- app/models/ccs/fm/service.rb
Ticket: https://crowncommercialservice.atlassian.net/browse/FMFR-376
> Bug FMFR 376 Remove horticultural services from list requiring GIA

- app/models/concerns/procurement_validator.rb
- app/models/concerns/service_questions_concern.rb
- app/models/concerns/working_days.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building.rb
- app/models/facilities_management/procurement_building_service.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/service_questions_concern_spec.rb
> - Small initial optimisations
> - Add concern for service questions
> - Further optimisation of the service question
> - Reduce number of DB queries
> - Add some optimisation on procurement buildings
> - Small refactor and address potential issue
> - Add test for the service_question_concern
> FMFR-438 - optimise requirements page 

- app/services/postcode/postcode_checker_v2.rb
- spec/services/postcode/postcode_checker_v2_spec.rb
> - Make sure invalid results are rejected
> - Add test to make sure result is processed properly
> FMFR-379 - Postcodes missing region data resolves to blank region 

- app/helpers/facilities_management/buildings_helper.rb
- app/views/facilities_management/buildings/_type.html.erb
- spec/helpers/facilities_management/buildings_helper_spec.rb
> - Fix method for checking if details should be open
> - Add tests for if the type details should be open
> FMFR-385 - Building Types details element

- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_supplier_spec.rb
> - Fix copy and refactor tests
> - Refactor tests for reasons for declining
> - Add tests for reason for closing
> FMFR-389 - Reason for closing error message

- app/controllers/facilities_management/supplier/dashboard_controller.rb
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/supplier/dashboard/_closed_contracts.html.erb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
> - Change the query to make sure sorting works
> - Make sure procurements are sorted properly
> - Add tests for closed date
> - Improve procurement supplier tests
> - Improve procurement spec
> FMFR-386 - Sorting of closed contracts on supplier dashboard

- app/models/facilities_management/procurement.rb
- app/services/facilities_management/assessed_value_calculator.rb
- spec/services/facilities_management/assessed_value_calculator_spec.rb
Applying the performance fixes from master to release/3.3.0
> Applying performance fixes

- app/calculators/fm_calculator/calculator.rb
- app/models/facilities_management/building.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_building.rb
- app/models/facilities_management/summary_report.rb
- app/services/facilities_management/spreadsheet_importer.rb
- db/migrate/20201015102942_remove_unused_building_attributes.rb
- db/schema.rb
- db/seeds.rb
- lib/tasks/facilities_management/fm.rake
- spec/factories/facilities_management_building.rb
- spec/factories/facilities_management_procurement_buildings.rb
- spec/models/facilities_management/building_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/summary_report_procurements_spec.rb
- spec/services/facilities_management/further_competition_spreadsheet_creator_spec.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
> - Mostly remove building json
> - Update factories
> - Remove unused json methods
> - Add migration to remove building_json
> - Update tests and factories
> - Remove user email
> - Change migration to remove all unused building attributes
> FMFR-445 - Remove building_json and other unused attributes

- app/services/facilities_management/spreadsheet_importer.rb
- spec/services/facilities_management/spreadsheet_importer_spec.rb
Update to allow for processing of building names
> FMFR-444 - issue with building names with spaces

- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/admin/management_report_spec.rb
> - Update the error messages for the management report
> FMFR-448 - Incorrect error messages for management report

- app/controllers/facilities_management/procurements/contracts_controller.rb
- app/controllers/facilities_management/supplier/contracts_controller.rb
- app/models/facilities_management/procurement.rb
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/procurements/contracts/edit.html.erb
- spec/controllers/facilities_management/procurements/contracts_controller_spec.rb
- spec/controllers/facilities_management/supplier/contracts_controller_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
> - Prevent user from sending to next supplier when the shouldn't
> - Add test for the model
> - Add test for contracts controller
> - Add some methods to reduce repetition
> - Add routing in controller to prevent pages being seen
> - Make sure price range comes from same value
> - Add test for new model methods
> - Add tests for the controller
> FMFR-456 - Prevent user editing contracts in the wrong state

- app/controllers/facilities_management/procurements/contracts_controller.rb
- app/models/facilities_management/procurement_supplier.rb
- app/views/facilities_management/procurements/contracts/edit.html.erb
- app/views/facilities_management/procurements/contracts/show.html.erb
- spec/controllers/facilities_management/procurements/contracts_controller_spec.rb
> - Disable JS validation on the page
> - Reduce complexity in the controller
> - Update tests for new update method
> - Add some test for before action in controller
> - Refactor method for checking if contract can be edited
> FMFR-390 - issues with contract edit pages

- .travis.yml
added cc test reporter key to global variables
added code climate test reporter before_script and after_script code
> changes to implement code climate

- .travis.yml
> update to ccs key

- app/models/facilities_management/procurement.rb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/procurement_spec.rb
> - Add additional validation for the file extension
> - Add tests for security policy document file extension
> FMFR-478 - additional validation on security policy document

- app/models/concerns/working_days.rb
- spec/controllers/facilities_management/procurements/contracts_controller_spec.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/procurement_supplier_spec.rb
- spec/models/facilities_management/working_days_spec.rb
- spec/rails_helper.rb
- spec/services/facilities_management/deliverable_matrix_spreadsheet_creator_spec.rb
- spec/support/api_request_stubs.rb
> - Change the code to use the api
> - Stub tests which use bank holiday JSON
> FMFR-33 Update working_days to use bank holiday api directly

- yarn.lock
Needed to run `yarn install` so the updates to the yarn.lock could be made for the changes in the package.json
> Run yarn install to update yarn.lock

- app/controllers/facilities_management/procurements_controller.rb
- app/helpers/facilities_management/procurements_helper.rb
- app/models/facilities_management/procurement.rb
- app/views/facilities_management/procurements/edit/_buildings.html.erb
- spec/controllers/facilities_management/procurements_controller_spec.rb
- spec/models/facilities_management/procurement_spec.rb
> - Update the methods so PBs are not created until save
> - Update specs to work with new pagination code
> FMFR-369 - Prevent many procurement buildings being created

- data/facilities_management/security_types.csv
- lib/tasks/facilities_management/db.rake
Reverts Crown-Commercial-Service/crown-marketplace#2740
> Revert "Update task so security types are wrong"

- app/helpers/application_helper.rb
- app/helpers/facilities_management/procurements/contract_details_helper.rb
- app/views/facilities_management/admin/management_reports/_completed.html.erb
- app/views/facilities_management/procurements/_spreadsheet.html.erb
- app/views/facilities_management/procurements/contract_details/da_journey/_important_information.erb
- app/views/facilities_management/procurements/contract_details/da_journey/_review.html.erb
- app/views/facilities_management/procurements/contract_details/da_journey/summary_pages/_contract_details_summary.html.erb
- app/views/facilities_management/procurements/contract_details/edit_partials/_governing_law.html.erb
- app/views/facilities_management/procurements/contract_details/edit_partials/_pension_funds.html.erb
- config/i18n-tasks.yml
- config/locales/views/facilities_management.en.yml
Create method to help with downloading public files
Add link for important information
Add link for contract details
Add links for the review and generate page
Add links for other public assets
> Change links so they don't use asset path with asset sync

- db/migrate/20201210141943_add_data_to_fm_suppliers.rb
- db/migrate/20210113092431_link_user_accounts_to_supplier_details.rb
Fix issues with migration
Make sure columns are reset before migrating the data
> FMFR-622 fix issues with migration

- db/migrate/20201210141943_add_data_to_fm_suppliers.rb
- db/migrate/20210113092431_link_user_accounts_to_supplier_details.rb
Fix issues with migration
Make sure columns are reset before migrating the data
> FMFR-624 - Fix issue for migration in CMP dev

- spec/models/facilities_management/admin/suppliers_admin_spec.rb
Reverts Crown-Commercial-Service/crown-marketplace#2774
> Revert "BUG - Fix flaky test"

- app/services/facilities_management/rake_modules/convert_supplier_names.rb
- spec/models/facilities_management/admin/suppliers_admin_spec.rb
> - Fix issue with flaky test
> - reduce the size of the batches
> BUG  - Fix issues for release 3.5.0

- app/services/facilities_management/rake_modules/supplier_data.rb
This will make it so all environments match what will happen in the production environment
> Update the rake module to remove environment variables

- app/views/facilities_management/admin/supplier_details/_additional_supplier_information.html.erb
- config/locales/views/facilities_management.en.yml
- spec/models/facilities_management/admin/suppliers_admin_spec.rb
> - Update error message for the DUNS number
> - Update the copy to explain the requirements for duns and CRN
> FMFR-673/674 - fix outstanding issues with the supplier details forms

- app/models/facilities_management/admin/rates.rb
- app/services/facilities_management/admin/sublot_services_validator.rb
- app/views/facilities_management/admin/service_rates/_average-framework-rates.html.erb
- app/views/facilities_management/admin/service_rates/_call-off-benchmark-rates.html.erb
- app/views/facilities_management/admin/service_rates/_variance_table.html.erb
- app/views/facilities_management/admin/service_rates/edit.html.erb
- app/views/facilities_management/admin/sublot_services/_services_prices_and_variances.html.erb
- config/locales/views/facilities_management.en.yml
- spec/controllers/facilities_management/admin/service_rates_controller_spec.rb
- spec/controllers/facilities_management/admin/sublot_services_controller_spec.rb
- spec/models/facilities_management/admin/rates_spec.rb
- spec/services/facilities_management/admin/sublot_services_validator_spec.rb
> - Add validation to limit to below 1
> - Add validations for service rates
> FMFR-688 - Limit percentages to 1 instead of 100

- app/assets/javascripts/facilities_management/beta/procurement/contract_extensions.js
- app/models/facilities_management/procurement/optional_call_off_extension.rb
- app/services/procurement_csv_export.rb
- app/views/facilities_management/procurements/contract_details/da_journey/summary_pages/_procurement_requirements.html.erb
- app/views/facilities_management/procurements/contracts/_procurement_requirements.html.erb
- app/views/facilities_management/procurements/edit/contract_period/_optional_call_off_extensions.html.erb
- app/views/facilities_management/procurements/summary/_contract_period.html.erb
- db/migrate/20210127131100_move_data_to_new_columns.rb
- spec/models/facilities_management/procurement/optional_call_off_extension_spec.rb
> - Update the JS for the contract period page
> - Add sorting scope
> - Add tests for the added scope
> FMFR-625 - Fix some issues with the optional extensions

- .travis.yml
- app/assets/stylesheets/components/ccs-global/_ccs-global.scss
- app/helpers/layout_helper.rb
- app/models/facilities_management/building.rb
- app/views/facilities_management/buildings/edit.html.erb
- app/views/facilities_management/procurements/_further_competition.html.erb
- app/views/facilities_management/procurements/_results.html.erb
- config/cucumber.yml
- config/locales/views/facilities_management.en.yml
- data/facilities_management/uk_addresses.csv
- features/facilities_management/buildings/buildings.feature
- features/facilities_management/buildings/review_completed_building.feature
- features/facilities_management/buildings/validations/add_a_building_validations.feature
- features/facilities_management/buildings/validations/building_type_validation.feature
- features/facilities_management/buildings/validations/internal_and_external_area_validations.feature
- features/facilities_management/buildings/validations/security_type_validations.feature
- features/helpers/facilities_management/find_address_helper.rb
- features/step_definitions/facilities_management/building_steps.rb
- features/step_definitions/facilities_management/common_steps.rb
- features/step_definitions/hooks.rb
- features/support/pages.rb
- features/support/pages/building.rb
- spec/models/facilities_management/building_spec.rb
> - Add test for building validations
> - Add feature tests for the buildings
> FMFR-696 - Part 2 - Add feature tests for buildings

- app/models/facilities_management/procurement_building_service.rb
- config/locales/views/facilities_management.en.yml
- features/facilities_management/procurements/create_a_procurement.feature
- features/facilities_management/procurements/direct_award/direct_award_procurement.feature
- features/facilities_management/service_requirements/internal_and_external_area.feature
- features/facilities_management/service_requirements/lifts.feature
- features/facilities_management/service_requirements/service_hours.feature
- features/facilities_management/service_requirements/service_standards.feature
- features/facilities_management/service_requirements/validations/internal_and_external_area_validations.feature
- features/facilities_management/service_requirements/validations/lift_validations.feature
- features/facilities_management/service_requirements/validations/service_hours_validations.feature
- features/facilities_management/service_requirements/validations/service_standard_validations.feature
- features/facilities_management/service_requirements/validations/volume_validations.feature
- features/facilities_management/service_requirements/volumes.feature
- features/step_definitions/facilities_management/common_steps.rb
- features/step_definitions/facilities_management/procurement_steps.rb
- features/step_definitions/facilities_management/service_requirement_steps.rb
- features/support/pages.rb
- features/support/pages/procurement.rb
- features/support/pages/service_requirement.rb
> - Add tests for adding lifts
> - Add feature tests for changing areas in service requirements
> - Add feature test for selecting the service standard
> - Add feature tests for the service hours
> - Add feature tests for the service volumes
> FMFR-696 - Part 3 - Add feature tests for service requirements

- features/facilities_management/procurements/direct_award/direct_award_procurement.feature
- features/facilities_management/quick_view_results/quick_view_results.feature
- features/facilities_management/quick_view_results/select_regions.feature
- features/facilities_management/quick_view_results/select_services.feature
- features/facilities_management/quick_view_results/validations/quick_view_results_validations.feature
- features/facilities_management/quick_view_results/validations/select_regions_validations.feature
- features/facilities_management/quick_view_results/validations/select_services_validations.feature
- features/step_definitions/facilities_management/common_steps.rb
- features/step_definitions/facilities_management/procurement_steps.rb
- features/step_definitions/facilities_management/quick_view_results_steps.rb
- features/step_definitions/facilities_management/service_requirement_steps.rb
- features/support/pages.rb
- features/support/pages/quick_view_results.rb
> - Add test for validations on quick view results
> - Add feature tests for selecting services
> - Add feature tests for selecting regions
> - Add feature tests for quick view results
> FMFR-696 - Part 4 - Add feature tests for quick view

- Gemfile
- Gemfile.lock
- app/views/facilities_management/buyer_details/edit_address.html.erb
- config/cucumber.yml
- features/accessibility/facilities_management/buildings/buildings_accessibility.feature
- features/accessibility/facilities_management/home/manage_my_details_accessibility.feature
- features/accessibility/facilities_management/home/start_pages_accessibility.feature
- features/accessibility/facilities_management/procurements/contract_details/completed_contract_details_accessibility.feature
- features/accessibility/facilities_management/procurements/contract_details/contract_details_accessibility.feature
- features/accessibility/facilities_management/procurements/create_a_procurement_accessibility.feature
- features/accessibility/facilities_management/procurements/procurements_dashboard_accessibility.feature
- features/accessibility/facilities_management/quick_view_results/quick_view_results_accessibility.feature
- features/accessibility/facilities_management/service_requirements/service_requirements_accessibility.feature
- features/facilities_management/procurements/create_a_procurement.feature
- features/facilities_management/procurements/validations/create_a_procurement_validations.feature
- features/step_definitions/facilities_management/building_steps.rb
- features/step_definitions/facilities_management/common_steps.rb
- features/step_definitions/facilities_management/contract_detail_steps.rb
- features/support/env.rb
- features/support/pages/building.rb
- features/support/pages/common.rb
- lib/tasks/cucumber.rake
- spec/factories/facilities_management_procurement_contact_detail.rb
> - Add accessibility features
> - Add more accessibility features
> - Add contract details accessibility features
> FMFR-696 - Part 6 - Add feature tests for accessibility

- config/cucumber.yml
- features/accessibility/facilities_management/procurements/building_missing_region.feature
- features/accessibility/facilities_management/procurements/entering_requirements/contract_details/contract_name_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/contract_details/contract_period_acessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/contract_details/estimated_annual_cost_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/contract_details/tupe_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/entering_requirements_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/services_and_building/add_a_building_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/services_and_building/assigning_services_to_buildings_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/services_and_building/buildings_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/services_and_building/service_requirements_accessibility.feature
- features/accessibility/facilities_management/procurements/entering_requirements/services_and_building/services_accessibility.feature
- features/accessibility/facilities_management/procurements/procurements_dashboard_accessibility.feature
- features/facilities_management/procurements/entering_requirements/building_missing_region.feature
- features/facilities_management/procurements/entering_requirements/contract_details/tupe.feature
- features/facilities_management/procurements/entering_requirements/validations/building_missing_region_validations.feature
- features/step_definitions/facilities_management/entering_requirements_steps.rb
> - Add accessibility test for entering requirements
> - Add accessibility tests for services and buildings
> FMFR-696 - Part 9 - Add more feature tests for accessibility

- Gemfile.lock
> FMFR-726 - update mimemagic gem to newer version

- lib/tasks/facilities_management/fm_supplier_rate_cards.rake
- lib/tasks/facilities_management/fm_suppliers.rake
- spec/models/facilities_management/summary_report_futher_competition_spec.rb
- spec/services/facilities_management/further_competition_spreadsheet_creator_spec.rb
> - Make sure supplier cards are added after supplier details
> - Update the tests to work
> FMFR-725 - Update the supplier prices

- app/helpers/facilities_management/procurement_buildings_services_helper.rb
- app/views/facilities_management/procurement_buildings/show.html.erb
- app/views/facilities_management/procurement_buildings_services/_service_hours.html.erb
- app/views/facilities_management/procurement_buildings_services/_volumes.html.erb
- config/locales/views/facilities_management.en.yml
- spec/helpers/facilities_management/procurement_buildings_services_helper_spec.rb
> - Add copy for less than 1 year on volumes
> - Add specs for the helper
> FMFR-596 - Add copy for volume questions

- app/assets/javascripts/facilities_management/fm-find-address.js
- app/views/facilities_management/procurements/edit/contract_period/_mobilisation_period.html.erb
- app/views/facilities_management/procurements/edit/contract_period/_optional_call_off_extensions.html.erb
> - Fix issue with the mobilisation period
> - Fix issue with optional extension
> Fix some issues with radio buttons

- app/views/facilities_management/procurements/_results.html.erb
- config/locales/views/facilities_management.en.yml
- features/step_definitions/facilities_management/common_steps.rb
- features/step_definitions/facilities_management/entering_requirements_steps.rb
- features/support/pages/entering_requirements.rb
- features/support/pages/procurement.rb
- spec/factories/facilities_management_building_for_assessed_value.rb
- spec/factories/facilities_management_procurement.rb
- spec/models/facilities_management/procurement_spec.rb
- spec/models/facilities_management/summary_report_procurements_spec.rb
- spec/services/facilities_management/assessed_value_calculator_scenario_0_spec.rb
- spec/services/facilities_management/assessed_value_calculator_scenario_1a_spec.rb
- spec/services/facilities_management/assessed_value_calculator_scenario_1b_spec.rb
- spec/services/facilities_management/assessed_value_calculator_scenario_3_spec.rb
- spec/services/facilities_management/assessed_value_calculator_scenario_4_spec.rb
> - Add scenarios for AV 1b
> - Create spec for the av scenario 1b
> - Create spec for the av scenario 1a
> - Create spec for the av scenario 3
> - Create spec for the av scenario 4
> - Update broken tests
> - Create spec for the av scenario 0
> - Remove unneeded feature test
> FMFR-723 - Move assessed value calculations into specs

- .travis.yml
- app/calculators/fm_calculator/calculator.rb
- app/services/facilities_management/direct_award_spreadsheet.rb
- lib/tasks/default.rake
- spec/services/facilities_management/direct_award_spreadsheet_spec.rb
> - Make sure tables are labeled correctly
> - Move the year factor to the front
> - Fix issue with spreadsheet test
> FMFR-793 - Fix issues with price matrix

- app/services/facilities_management/direct_award_spreadsheet.rb
> - Make sure monthly cost is correct
> - Make sure total cost is summed correctly
> FMFR-793 - Make sure monthly costs are correct

- app/assets/stylesheets/govuk-frontend.scss
> FMFR-812 - issue with page format

- app/helpers/facilities_management/admin/sublot_services_helper.rb
- app/models/facilities_management/admin/rates.rb
- app/services/facilities_management/admin/sublot_services_validator.rb
- app/views/facilities_management/admin/sublot_services/_services_prices_and_variances.html.erb
- config/locales/views/facilities_management.en.yml
- features/facilities_management/admin/supplier_data/supplier_framework_data/validations/prices_and_variance_validations.feature
- spec/controllers/facilities_management/admin/sublot_services_controller_spec.rb
- spec/models/facilities_management/admin/rates_spec.rb
- spec/services/facilities_management/admin/sublot_services_validator_spec.rb
> - Make sure the extra services are labeled correctly
> - Fix issue with validation
> - Update specs to account for the validator
> - Add feature test for the additional services
> - Update the validator to add relevant error messages
> - Update the specs for new error messages
> FMFR-806 - Fix issue with some services in the admin tool

- app/controllers/concerns/shared_buildings_controller_methods.rb
- app/controllers/facilities_management/buildings_controller.rb
- app/controllers/facilities_management/journey_controller.rb
- app/controllers/facilities_management/procurement_buildings_controller.rb
- app/controllers/facilities_management/procurement_buildings_services_controller.rb
- app/controllers/facilities_management/procurements/contract_details_controller.rb
- app/controllers/facilities_management/procurements/contracts_controller.rb
- app/controllers/facilities_management/procurements/edit_buildings_controller.rb
- app/controllers/facilities_management/procurements_controller.rb
- spec/controllers/facilities_management/buildings_controller_spec.rb
- spec/controllers/facilities_management/procurement_buildings_controller_spec.rb
- spec/controllers/facilities_management/procurement_buildings_services_controller_spec.rb
- spec/controllers/facilities_management/procurements/contract_details_controller_spec.rb
- spec/controllers/facilities_management/procurements/contracts_controller_spec.rb
- spec/controllers/facilities_management/procurements/edit_buildings_controller_spec.rb
- spec/controllers/facilities_management/procurements_controller_spec.rb
> - Catch error from journey controller
> - Redirect if page not valid
> - Add specs for new controller code
> FMFR-814 - Make sure we only allow recognised edit pages

- app/views/crown_marketplace/allow_list/index.html.erb
- config/locales/en.yml
> FMFR-867 - Update copy on Crown Marketplace

- app/services/cognito/sign_up_user.rb
- config/locales/en.yml
- spec/services/cognito/sign_up_user_spec.rb
- Add validation for number and email case
> FMFR-870 - Add validation for number and email case

- app/controllers/crown_marketplace/allow_list_controller.rb
- app/controllers/crown_marketplace/framework_controller.rb
- app/models/ability.rb
- app/views/crown_marketplace/allow_list/_allow_list_table.html.erb
- app/views/crown_marketplace/allow_list/index.html.erb
- spec/controllers/crown_marketplace/allow_list_controller_spec.rb
- spec/support/controller_macros.rb
> - Allow for read only access
> - Update tests for new rules
> FMFR-874 - Limit access to the allow list

- app/views/facilities_management/procurements/contracts/closed/_contract_signed.html.erb
- features/accessibility/facilities_management/contracts/contract_options.feature
- features/accessibility/facilities_management/contracts/contract_summary.feature
- features/accessibility/facilities_management/contracts/no_more_supplier.feature
- features/accessibility/facilities_management/home/accessibility_statement_accessibility.feature
- features/accessibility/facilities_management/home/cookie_pages_accessibility.feature
- features/accessibility/facilities_management/home/start_pages_accessibility.feature
- features/accessibility/facilities_management/supplier/contracts/contracts_accessibility.feature
- features/accessibility/facilities_management/supplier/dashboard_accessibility.feature
- features/facilities_management/contracts/sent_contract.feature
- features/helpers/facilities_management/step_helper.rb
- features/step_definitions/facilities_management/procurement_steps.rb
- features/step_definitions/facilities_management/supplier_steps.rb
> - Add accessibility tests for the supplier pages
> - Add accessibility for supplier and contract pages
> - Add accessibility tests for cookies and accessibility statement
> FMFR-626 - Accessibility on new pages

- features/facilities_management/admin/navigation_links/navigation_links_signed_in.feature
- features/facilities_management/admin/navigation_links/navigation_links_signed_out.feature
- features/facilities_management/home/navigation_links/navigation_links_signed_in.feature
- features/facilities_management/home/navigation_links/navigation_links_signed_in_without_details.feature
- features/facilities_management/home/navigation_links/navigation_links_signed_out.feature
- features/facilities_management/supplier/navigation_links/navigation_links_signed_in.feature
- features/facilities_management/supplier/navigation_links/navigation_links_signed_out.feature
- features/step_definitions/facilities_management/home_steps.rb
- features/support/pages.rb
- features/support/pages/home.rb
> - Add tests for when buyer signed out
> - Add tests for when buyer signed in
> - Add tests for when buyer signed in without details
> - Add tests for supplier links
> - Add navigation link tests for admin
> FMFR-626 - Add tests for the navigation links

- app/assets/javascripts/facilities_management/fm-admin-upload-prgress.js
- app/helpers/facilities_management/admin/sublot_services_helper.rb
- app/helpers/facilities_management/admin/uploads_helper.rb
- app/models/facilities_management/admin/upload.rb
- app/services/facilities_management/admin/rate_validator.rb
- app/services/facilities_management/admin/sublot_services_validator.rb
- app/services/facilities_management/admin/supplier_framework_data_importer.rb
- app/views/facilities_management/admin/sublot_services/_services_prices_and_variances.html.erb
- app/views/facilities_management/admin/uploads/_failed.html.erb
- app/views/facilities_management/admin/uploads/new.html.erb
- config/locales/views/facilities_management.en.yml
- db/migrate/20210624113607_update_import_errors.rb
- db/schema.rb
- features/facilities_management/admin/supplier_data/supplier_framework_data/validations/prices_and_variance_validations.feature
- spec/controllers/facilities_management/admin/sublot_services_controller_spec.rb
- spec/helpers/facilities_management/admin/uploads_helper_spec.rb
- spec/models/facilities_management/admin/upload_spec.rb
- spec/services/facilities_management/admin/rate_validator_spec.rb
- spec/services/facilities_management/admin/sublot_services_validator_spec.rb
- spec/services/facilities_management/admin/supplier_framework_data_importer_spec.rb
- spec/services/facilities_management/admin/supplier_framework_data_spreadsheet_spec.rb
- spec/support/facilities_management/admin/supplier_framework_data_helper.rb
> - Fix issue with blank discount
> - Add new rate validator model
> - Add validation of the imported rates
> - Make sure errors are displayed properly
> - Add tests for the admin uploads helper
> - Add tests for the spreadsheet generation
> - Add tests for the admin spreadsheet import
> - Change to using active model
> - Update the shown error messages
> - Update the tests for importing
> FMFR-871 - Add validations on admin upload

- app/controllers/facilities_management/procurements/contract_details_controller.rb
- app/models/concerns/procurement_validator.rb
- app/models/facilities_management/procurement.rb
- spec/models/facilities_management/procurement_spec.rb
> - Update the contract details controller
> - Update the procurement validator for contract details
> Refactor security policy document validations

- app/models/allowed_email_domain.rb
- app/services/cognito/sign_up_user.rb
- spec/services/cognito/sign_up_user_spec.rb
- Make sure the allow list domain validation is case insensitive
> FMFR-890 - Ignore case of email domain

- app/controllers/api/v2/nuts_controller.rb
- app/controllers/api/v2/postcodes_controller.rb
- app/controllers/application_controller.rb
- app/controllers/facilities_management/admin/framework_controller.rb
- app/controllers/facilities_management/admin/home_controller.rb
- app/controllers/facilities_management/framework_controller.rb
- app/controllers/facilities_management/home_controller.rb
- app/controllers/facilities_management/sessions_controller.rb
- app/controllers/facilities_management/supplier/framework_controller.rb
- app/controllers/facilities_management/supplier/home_controller.rb
- app/views/facilities_management/admin/home/unrecognised_framework.html.erb
- app/views/facilities_management/home/unrecognised_framework.html.erb
- app/views/facilities_management/supplier/home/unrecognised_framework.html.erb
- app/views/home/accessibility_statement.html.erb
- app/views/home/unrecognised_framework.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/facilities_management/admin/home_controller_spec.rb
- spec/controllers/facilities_management/buildings_controller_spec.rb
- spec/controllers/facilities_management/buyer_details_controller_spec.rb
- spec/controllers/facilities_management/home_controller_spec.rb
- spec/controllers/facilities_management/rm3830/admin/home_controller_spec.rb
- spec/controllers/facilities_management/rm3830/buyer_account_controller_spec.rb
- spec/controllers/facilities_management/rm3830/supplier/dashboard_controller_spec.rb
- spec/controllers/facilities_management/supplier/home_controller_spec.rb
- Add the unrecognised framework page
- Make the application controller raise an exception
- Update the test for unrecognised framework
> FMFR-1075 - Create unrecognised framework page

- app/controllers/facilities_management/rm3830/procurements/spreadsheet_imports_controller.rb
- spec/controllers/facilities_management/rm3830/procurements/spreadsheet_imports_controller_spec.rb
Fix issue where files could not be uploaded properly due to an issue in the controller
> Fix issue with bulk upload

- db/migrate/20210715113723_rename_facilities_management_indexes.rb
- db/migrate/20210715113726_rename_tables_to_add_rm3830.rb
- db/migrate/20210716112653_rename_unit_of_measure_table.rb
- Update the migrations to do some parts separately
https://crowncommercialservice.atlassian.net/browse/FMFR-1087
> BUG FMFR-1087 Fix issue with migrations on some environments

- app/controllers/facilities_management/rm3830/procurements/edit_buildings_controller.rb
- app/views/facilities_management/rm3830/buyer_account/index.html.erb
- config/locales/views/facilities_management.rm3830.en.yml
- config/routes.rb
- features/facilities_management/home/framework_links.feature
- features/facilities_management/rm3830/procurements/entering_requirements/services_and_buildings/add_a_building/review_completed_building.feature
- features/step_definitions/facilities_management/common_steps.rb
- Make sure the edit buildings has the right links
- Make sure start link still works
- Add test for the return links
- Add tests for the old start links
> FMFR-1088 - Fix issue with the 'Return to buildings' link in edit buildings

- app/services/facilities_management/rm3830/spreadsheet_importer.rb
- config/locales/views/facilities_management.rm3830.en.yml
- Update the links for downloading static files
> FMFR-1092 - Fix issue with file downloads

- app/controllers/api/v2/nuts_controller.rb
- app/controllers/api/v2/postcodes_controller.rb
- app/controllers/facilities_management/buyer_details_controller.rb
- app/controllers/facilities_management/framework_controller.rb
- app/controllers/facilities_management/home_controller.rb
- app/controllers/facilities_management/rm3830/home_controller.rb
Add the exceptions for buyer details and api
Add the exception for other paths
> FMFR-1090 - Change how we make sure buyers have contact details

- Gemfile.lock
> Fix issue where nokogiri could not upgrade properly

- app/helpers/application_helper.rb
- app/helpers/layout_helper.rb
- app/views/facilities_management/buildings/action_partials/_show.html.erb
- app/views/facilities_management/rm3830/procurements/contract_details/edit_partials/_governing_law.html.erb
- features/facilities_management/rm3830/admin/management_report/management_report.feature
- features/helpers/facilities_management/management_report.rb
- features/step_definitions/facilities_management/common_steps.rb
- features/step_definitions/hooks.rb
- Update the code to stop the depreciation warnings
- Fix management report tests
- Add a rescue to fix issue where the test sometimes fails
> Fix various issues with feature tests

- pipeline_pre_build_tests.sh
- Update the node version for the pipeline to v14 (This is the next oldest LTS version)
This should fix the issue with some of the deployments
> Update the node version for the pipeline to v14

- package.json
- yarn.lock
This is to revert a PR which was originally reverted in error
> Update Juice again to remove some security issues

- app/models/facilities_management/rm6232.rb
- app/models/facilities_management/rm6232/service.rb
- app/models/facilities_management/rm6232/work_package.rb
- app/views/facilities_management/rm6232/home/index.html.erb
- data/facilities_management/rm6232/services.csv
- data/facilities_management/rm6232/work_packages.csv
- db/migrate/20220405081851_create_facilities_management_work_packages.rb
- db/migrate/20220405082014_create_facilities_management_services.rb
- db/schema.rb
- lib/tasks/facilities_management/rm6232/services.rake
- spec/controllers/facilities_management/admin/frameworks_controller_spec.rb
- spec/models/facilities_management/rm6232/service_spec.rb
- spec/models/facilities_management/rm6232/work_package_spec.rb
Ticket: [FMFR-1001](https://crowncommercialservice.atlassian.net/browse/FMFR-1001)
This involved the following steps:
- Add the rm6232 work package and services table
- Add the data for the work packages and services
- Add the services and work packages model
- Add the rake task to import the services
- Add tests for the service and work packages
The following environment variables need to be changed:
Environment variable | New value
-- | --
`/Environment/ccs/cmp/APP_RUN_RAKE_TASKS` | `TRUE`
`/Environment/ccs/cmp/RAKE_TASK_LIST` | `db:rm6232:static`
> FMFR-1001 Add the new service data for RM6232

- app/helpers/gov_uk_helper/header.rb
- app/views/layouts/application.html.erb
- app/views/layouts/error.html.erb
- features/facilities_management/home/responsive_navigation_links.feature
- features/helpers/responsive_headers_helper.rb
- features/step_definitions/facilities_management/home_steps.rb
- features/step_definitions/hooks.rb
- features/support/pages/rm3830/home.rb
Make some small updates to fix some issues with GOV.UK Frontend. This includes:
- Fix issue with the header
- Add JS to skip link to improve accessibility
I also added to test to check the Javascript
> Make some small updates to fix some issues with GOV.UK Frontend

- app/models/facilities_management/rm6232/journey/choose_locations.rb
- app/models/facilities_management/rm6232/journey/choose_services.rb
- app/models/generic_journey.rb
- app/views/facilities_management/rm6232/journey/choose_locations.html.erb
- config/locales/views/facilities_management.rm6232.en.yml
- spec/models/facilities_management/rm6232/journey/choose_locations_spec.rb
- spec/models/facilities_management/rm6232/journey/choose_services_spec.rb
Part of [FMFR-1003](https://crowncommercialservice.atlassian.net/browse/FMFR-1003)
Add the choose locations section to the Quick view.
This is almost identical to the section in the previous framework
> FMFR-1003 - Quick view - Choose Locations

- app/models/facilities_management/rm6232/journey/annual_contract_value.rb
- app/models/facilities_management/rm6232/journey/choose_locations.rb
- app/models/generic_journey.rb
- app/views/facilities_management/rm6232/journey/annual_contract_value.html.erb
- config/locales/views/facilities_management.rm6232.en.yml
- spec/models/facilities_management/rm6232/journey/annual_contract_value_spec.rb
- spec/models/facilities_management/rm6232/journey/choose_locations_spec.rb
Part of [FMFR-1003](https://crowncommercialservice.atlassian.net/browse/FMFR-1003)
Add the annual contract value section for the quick view
> FMFR-1003 - Quick view - Annual Contract Value

- app/assets/stylesheets/ccs/facilities-management/_all.scss
- app/assets/stylesheets/ccs/facilities-management/_panel.scss
- app/controllers/facilities_management/rm6232/procurements_controller.rb
- app/models/ability.rb
- app/models/facilities_management/rm6232/procurement.rb
- app/services/facilities_management/contract_number_generator.rb
- app/views/facilities_management/rm6232/procurements/new.html.erb
- app/views/facilities_management/rm6232/procurements/show.html.erb
- app/views/facilities_management/rm6232/procurements/show_partial/_what_happens_next.html.erb
- config/locales/views/facilities_management.rm6232.en.yml
- config/routes.rb
- db/migrate/20220520144548_add_contract_number_row.rb
- db/migrate/20220523075127_add_index_to_proc_name_and_user.rb
- db/schema.rb
- features/facilities_management/rm3830/quick_view_results/validations/quick_view_results_validations.feature
- features/facilities_management/rm6232/quick_view/results.feature
- features/facilities_management/rm6232/quick_view/validations/results_validations.feature
- features/step_definitions/facilities_management/rm6232/procurement_steps.rb
- spec/controllers/facilities_management/rm6232/procurements_controller_spec.rb
- spec/factories/facilities_management/rm6232/procurement.rb
- spec/models/facilities_management/rm6232/procurement_spec.rb
- spec/services/facilities_management/contract_number_generator_spec.rb
Ticket: [FMFR-1167](https://crowncommercialservice.atlassian.net/browse/FMFR-1167)
Added the “What happens next?” page which is the start of the procurement journey. As part of this I added the validations to the contract name on the “Results” page. I also updated the contract number generator to generate numbers for the new RM6232 framework.
Note: some links will not work as they will be added in future PRs
> FMFR-1167 - Added the “What happens next?” page

- app/controllers/facilities_management/rm6232/service_specification_controller.rb
- app/models/facilities_management/rm6232/service.rb
- app/services/facilities_management/rm6232/service_specification_parser.rb
- app/views/facilities_management/procurement_details/edit_partials/_services.html.erb
- app/views/facilities_management/rm6232/journey/choose_services.html.erb
- app/views/facilities_management/rm6232/service_specification/_clause.html.erb
- app/views/facilities_management/rm6232/service_specification/show.html.erb
- config/locales/views/facilities_management.rm6232.en.yml
- config/routes.rb
- data/facilities_management/rm6232/service_specifications.csv
- data/facilities_management/rm6232/services.csv
- data/facilities_management/rm6232/work_packages.csv
- features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/service_specification.feature
- features/facilities_management/rm6232/quick_view/select_services.feature
- features/facilities_management/rm6232/quick_view/service_specification.feature
- features/step_definitions/facilities_management/quick_view_steps.rb
- features/step_definitions/facilities_management/rm3830/admin_steps.rb
- features/step_definitions/facilities_management/rm3830/quick_view_results_steps.rb
- features/step_definitions/facilities_management/rm6232/admin_steps.rb
- features/step_definitions/facilities_management/rm6232/quick_view_steps.rb
- features/support/pages.rb
- features/support/pages/quick_view.rb
- features/support/pages/rm3830/quick_view.rb
- features/support/pages/rm6232/quick_view.rb
- spec/controllers/facilities_management/rm6232/service_specification_controller_spec.rb
- spec/services/facilities_management/rm6232/service_specification_parser_spec.rb
Ticket: [FMFR-1004](https://crowncommercialservice.atlassian.net/browse/FMFR-1004)
Add the service specifications for the services in RM6232. This is very similar to what is in RM3830, only I have refactored it a little bit so that it is a bit more tidy. I got the service specifications from a word document and then converted it to a CSV file.
I’ve also added tests to make sure that the service specification for all services will render in the application.
> FMFR-1004 - Add service specification

- app/assets/stylesheets/components/supplier-record/_supplier-record.scss
- app/models/facilities_management/rm6232/procurement.rb
- app/views/facilities_management/rm6232/procurements/show.html.erb
- app/views/facilities_management/rm6232/procurements/show_partials/_further_information.html.erb
- config/locales/en.yml
- config/locales/views/facilities_management.rm6232.en.yml
- features/accessibility/facilities_management/rm6232/procurements/further_information_accessibility.feature
- features/accessibility/facilities_management/rm6232/procurements/results_accessibility.feature
- features/facilities_management/rm6232/procurements/further_information.feature
- features/facilities_management/rm6232/procurements/results/results.feature
- features/step_definitions/facilities_management/procurement_steps.rb
- spec/controllers/facilities_management/rm6232/procurements_controller_spec.rb
- spec/factories/facilities_management/rm6232/procurement.rb
- spec/models/facilities_management/rm6232/procurement_spec.rb
Ticket: [FMFR-1175](https://crowncommercialservice.atlassian.net/browse/FMFR-1175)
Added the final page for the RM6232 framework. The links for the document downloads do not yet work but they will be added in the future.
As always, I added specs and feature tests.
> FMFR-1175 - Add the final page

- app/helpers/application_helper.rb
- app/views/facilities_management/rm6232/journey/choose_locations.html.erb
- config/locales/views/facilities_management.rm6232.en.yml
- features/facilities_management/rm3830/procurements/procurements_dashboard.feature
- features/facilities_management/rm3830/quick_view_results/select_regions.feature
- features/facilities_management/rm3830/quick_view_results/validations/quick_view_results_validations.feature
- features/facilities_management/rm6232/quick_view/results.feature
- features/facilities_management/rm6232/quick_view/select_regions.feature
Ticket: [FMFR-1240](https://crowncommercialservice.atlassian.net/browse/FMFR-1240)
In this commit I have updated some of the copy on the choose regions page.
> FMFR-1240 - Updates to the regions page

- app/views/facilities_management/rm6232/procurements/new.html.erb
- config/locales/views/facilities_management.rm6232.en.yml
- features/facilities_management/rm6232/quick_view/results.feature
- features/facilities_management/rm6232/quick_view/validations/results_validations.feature
Ticket: [FMFR-1242](https://crowncommercialservice.atlassian.net/browse/FMFR-1242)
In this commit I have updated some of the copy on the ‘Results’ page.
> FMFR-1242 - Update the results page

- app/controllers/facilities_management/rm6232/procurements_controller.rb
- app/services/facilities_management/rm3830/supplier_shortlist_spreadsheet_creator.rb
- app/services/facilities_management/rm6232/supplier_shortlist_spreadsheet_creator.rb
- app/services/facilities_management/supplier_shortlist_spreadsheet.rb
- spec/controllers/facilities_management/rm6232/procurements_controller_spec.rb
- spec/services/facilities_management/rm3830/supplier_shortlist_spreadsheet_creator_spec.rb
- spec/services/facilities_management/rm6232/supplier_shortlist_spreadsheet_creator_spec.rb
Ticket: [FMFR-1244](https://crowncommercialservice.atlassian.net/browse/FMFR-1244)
In this commit I have updated the supplier shortlist copy and the associated tests. Note some of these changes affect the spreadsheet in RM3830 too (on the Regions sheet).
> FMFR-1244 - Update the supplier shortlist

- app/views/facilities_management/rm6232/home/index.html.erb
- config/locales/views/facilities_management.rm6232.en.yml
- features/facilities_management/home/framework_links.feature
Ticket: [FMFR-1234](https://crowncommercialservice.atlassian.net/browse/FMFR-1234)
In this commit I have updated the landing page which buyers see before they log in.
> FMFR-1234 - Update the landing page

- data/facilities_management/rm6232/service_specifications.csv
- data/facilities_management/rm6232/services.csv
Ticket: [FMFR-1252](https://crowncommercialservice.atlassian.net/browse/FMFR-1252)
Update the service names and descriptions now that the category have reviewed them all.
We need to set the following environment variables:
|Environment variable|value|
|-|-|
|`/Environment/ccs/cmp/RAKE_TASK_LIST`|`db:rm6232:import_services`|
|`/Environment/ccs/cmp/APP_RUN_RAKE_TASKS`|`TRUE`|
> FMFR-1252 - Update service descriptions

- app/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller.rb
- app/helpers/application_helper.rb
- app/models/nuts1_region.rb
- app/views/facilities_management/rm6232/admin/supplier_data/index.html.erb
- app/views/facilities_management/rm6232/journey/choose_locations.html.erb
- spec/models/nuts1_region_spec.rb
Ticket: [FMR-1272](https://crowncommercialservice.atlassian.net/browse/FMFR-1272)
Add the overseas option in the RM6232 framework
> FMFR-1272 - Add the overseas option in the RM6232 framework

- app/controllers/facilities_management/admin/supplier_details_controller.rb
- app/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller.rb
- app/services/facilities_management/rm6232/admin/files_importer/files_checker.rb
- app/services/facilities_management/rm6232/admin/files_importer/files_processor.rb
- spec/controllers/facilities_management/admin/supplier_details_controller_rm3830_spec.rb
- spec/controllers/facilities_management/admin/supplier_details_controller_rm6232_spec.rb
- spec/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller_spec.rb
- spec/models/facilities_management/rm6232/admin/supplier_data/edit_spec.rb
- spec/services/facilities_management/rm6232/admin/files_importer_spec.rb
- spec/services/facilities_management/rm6232/admin/supplier_data_snapshot_generator_spec.rb
- spec/support/facilities_management/rm6232/admin/file_importer_helper.rb
Ticket: [FMFR-1268](https://crowncommercialservice.atlassian.net/browse/FMFR-1268)
As we allow the  admin team to download the spreadsheets with the status in them, this commit adds the functionality to allow them to upload spreadsheets with the status as a column.
> FMFR-1268 - Allow spreadsheets with 'Status' column to be uploaded

- app/controllers/facilities_management/framework_controller.rb
This prevents an infinite loop occuring
> Make sure unrecognised framework is at the top of the call backs

- app/assets/stylesheets/components/header/_header.scss
Make small change to the header scss to fix some issues.
This fixes an issue with the focus on the header link not being correct:
> Make small change to the header scss to fix some issues.

- app/assets/javascripts/application.js
- app/controllers/concerns/cookie_settings_concern.rb
- app/helpers/application_helper.rb
- app/typescript/shared/cookieBanner.ts
- package.json
- spec/helpers/application_helper_spec.rb
- yarn.lock
Ticket: [FMFR-1310](https://crowncommercialservice.atlassian.net/browse/FMFR-1310)
Fix an issue where cookie is not removed when JS is enabled due to GA creating the cookie when the website is reloaded
> FMFR-1310 - Fix issue where cookie is not deleted properly

- app/controllers/crown_marketplace/manage_users_controller.rb
- app/helpers/crown_marketplace/manage_users_helper.rb
- app/helpers/gov_uk_helper.rb
- app/helpers/gov_uk_helper/error_message.rb
- app/helpers/gov_uk_helper/text_input.rb
- app/services/cognito/admin/user.rb
- app/views/crown_marketplace/home/index.html.erb
- app/views/crown_marketplace/manage_users/_users_table.html.erb
- app/views/crown_marketplace/manage_users/index.html.erb
- app/views/crown_marketplace/manage_users/index.js.erb
- config/locales/views/crown_marketplace.en.yml
- config/routes.rb
- features/accessibility/crown_marketplace/user_admin/find_users_accessibility.feature
- features/crown_marketplace/manage_users/user_admin/add_user.feature
- features/crown_marketplace/manage_users/user_admin/find_users.feature
- features/crown_marketplace/manage_users/user_admin/find_users_javascript_enabled.feature
- features/crown_marketplace/manage_users/user_admin/validations/find_users_javascript_enabled_validation.feature
- features/crown_marketplace/manage_users/user_admin/validations/find_users_validation.feature
- features/helpers/crown_marketplace/cognito_helper.rb
- features/step_definitions/crown_marketplace/cognito_steps.rb
- features/step_definitions/crown_marketplace/manage_users_steps.rb
- features/support/pages/manage_users.rb
- spec/controllers/crown_marketplace/manage_users_controller_spec.rb
Ticket: [FMFR-1319](https://crowncommercialservice.atlassian.net/browse/FMFR-1319)
We are going to give CSC the ability to manage users in the Digital Foundations project. In this commit I have added the ability to search for users.
In addition, I have (as always) added unit, feature and accessibility tests to account for the changes.
> FMFR-1319 - Add ability to search for users

- app/controllers/crown_marketplace/manage_users_controller.rb
- app/helpers/crown_marketplace/manage_users_helper.rb
- app/services/cognito/admin/roles.rb
- app/services/cognito/admin/user.rb
- app/views/crown_marketplace/manage_users/_users_table.html.erb
- app/views/crown_marketplace/manage_users/show.html.erb
- config/locales/views/crown_marketplace.en.yml
- config/routes.rb
- features/crown_marketplace/manage_users/super_admin/view_user/assorted_details.feature
- features/crown_marketplace/manage_users/super_admin/view_user/full_details.feature
- features/crown_marketplace/manage_users/super_admin/view_user/mixed_roles.feature
- features/crown_marketplace/manage_users/super_admin/view_user/something_went_wrong.feature
- features/crown_marketplace/manage_users/user_admin/view_user/assorted_details.feature
- features/crown_marketplace/manage_users/user_admin/view_user/full_details.feature
- features/crown_marketplace/manage_users/user_admin/view_user/mixed_roles.feature
- features/crown_marketplace/manage_users/user_admin/view_user/something_went_wrong.feature
- features/crown_marketplace/manage_users/user_support/view_user/assorted_details.feature
- features/crown_marketplace/manage_users/user_support/view_user/full_details.feature
- features/crown_marketplace/manage_users/user_support/view_user/mixed_roles.feature
- features/crown_marketplace/manage_users/user_support/view_user/something_went_wrong.feature
- features/helpers/crown_marketplace/cognito_helper.rb
- features/step_definitions/crown_marketplace/cognito_steps.rb
- features/step_definitions/crown_marketplace/manage_users_steps.rb
- features/support/pages/manage_users.rb
- spec/controllers/crown_marketplace/manage_users_controller_spec.rb
- spec/services/cognito/admin/roles_spec.rb
Ticket: https://crowncommercialservice.atlassian.net/jira/software/c/projects/FMFR/boards/71?modal=detail&selectedIssue=FMFR-1322
Added a show page which summarises the details of users of crown marketplace. Users will use this instead of the Cognito Web portal. Added Feature and RSpec tests to verify this.
> FMFR-1322-add-show-pages-to-manage-users

- app/views/crown_marketplace/manage_users/edit_partials/_roles.html.erb
- app/views/crown_marketplace/manage_users/edit_partials/_service_access.html.erb
- app/views/crown_marketplace/manage_users/show.html.erb
- config/locales/views/crown_marketplace.en.yml
- features/accessibility/crown_marketplace/super_admin/edit_user_accessibility.feature
- features/crown_marketplace/manage_users/super_admin/edit_user.feature
- features/crown_marketplace/manage_users/super_admin/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/user_admin/edit_user.feature
- features/crown_marketplace/manage_users/user_admin/validations/edit_user_validation.feature
- features/step_definitions/crown_marketplace/cognito_steps.rb
- features/step_definitions/crown_marketplace/manage_users_steps.rb
- spec/controllers/crown_marketplace/manage_users_controller_spec.rb
Ticket: [FMFR-1326](https://crowncommercialservice.atlassian.net/browse/FMFR-1326)
I have added/updated the specs and feature tests to reflect these changes
In this commit I have added the page to edit the roles.
[FMFR-1326]: https://crowncommercialservice.atlassian.net/browse/FMFR-1326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1326 - Add the roles page

- app/controllers/crown_marketplace/manage_users_controller.rb
- app/views/crown_marketplace/manage_users/edit_partials/_mfa_enabled.html.erb
- app/views/crown_marketplace/manage_users/show.html.erb
- config/locales/views/crown_marketplace.en.yml
- features/accessibility/crown_marketplace/super_admin/edit_user_accessibility.feature
- features/crown_marketplace/manage_users/super_admin/edit_user.feature
- features/crown_marketplace/manage_users/super_admin/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/user_admin/edit_user.feature
- features/crown_marketplace/manage_users/user_admin/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/user_support/edit_user.feature
- features/crown_marketplace/manage_users/user_support/validations/edit_user_validation.feature
- features/step_definitions/crown_marketplace/manage_users_steps.rb
- features/step_definitions/facilities_management/common_steps.rb
- features/support/pages/manage_users.rb
- spec/controllers/crown_marketplace/manage_users_controller_spec.rb
- spec/services/cognito/admin/user_spec.rb
Ticket: [FMFR-1325](https://crowncommercialservice.atlassian.net/browse/FMFR-1325)
In this commit I have added the page to edit the MFA status.
I have added/updated the specs and feature tests to reflect these changes
[FMFR-1325]: https://crowncommercialservice.atlassian.net/browse/FMFR-1325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1325 - Add the MFA status page

- app/controllers/crown_marketplace/manage_users_controller.rb
- app/views/crown_marketplace/manage_users/edit_partials/_mfa_enabled.html.erb
- app/views/crown_marketplace/manage_users/edit_partials/_roles.html.erb
- app/views/crown_marketplace/manage_users/edit_partials/_service_access.html.erb
- app/views/crown_marketplace/manage_users/edit_partials/_telephone_number.html.erb
- app/views/crown_marketplace/manage_users/show.html.erb
- config/locales/views/crown_marketplace.en.yml
- features/accessibility/crown_marketplace/super_admin/edit_user_accessibility.feature
- features/crown_marketplace/manage_users/super_admin/edit_user.feature
- features/crown_marketplace/manage_users/super_admin/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/user_admin/edit_user.feature
- features/crown_marketplace/manage_users/user_admin/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/user_support/edit_user.feature
- features/crown_marketplace/manage_users/user_support/validations/edit_user_validation.feature
- features/step_definitions/crown_marketplace/cognito_steps.rb
- features/step_definitions/crown_marketplace/manage_users_steps.rb
- features/step_definitions/facilities_management/common_steps.rb
- features/support/pages/manage_users.rb
- spec/controllers/crown_marketplace/manage_users_controller_spec.rb
- spec/services/cognito/admin/user_spec.rb
Ticket: [FMFR-1324](https://crowncommercialservice.atlassian.net/browse/FMFR-1324)
In this commit I have added the page to edit the telephone number.
I have added/updated the specs and feature tests to reflect these changes
[FMFR-1324]: https://crowncommercialservice.atlassian.net/browse/FMFR-1324?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1324 - Add the telephone number page

- app/controllers/crown_marketplace/manage_users_controller.rb
- app/helpers/crown_marketplace/manage_users_helper.rb
- app/services/cognito/admin/user.rb
- app/services/cognito/admin/user_client_interface.rb
- app/views/crown_marketplace/manage_users/edit_partials/_email_verified.html.erb
- app/views/crown_marketplace/manage_users/show.html.erb
- config/locales/views/crown_marketplace.en.yml
- features/accessibility/crown_marketplace/super_admin/edit_user_accessibility.feature
- features/accessibility/crown_marketplace/super_admin/view_user_accessibility.feature
- features/crown_marketplace/manage_users/super_admin/edit_user.feature
- features/crown_marketplace/manage_users/super_admin/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/super_admin/view_user/assorted_details.feature
- features/crown_marketplace/manage_users/super_admin/view_user/full_details.feature
- features/crown_marketplace/manage_users/super_admin/view_user/mixed_roles.feature
- features/crown_marketplace/manage_users/user_admin/edit_user.feature
- features/crown_marketplace/manage_users/user_admin/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/user_admin/view_user/assorted_details.feature
- features/crown_marketplace/manage_users/user_admin/view_user/full_details.feature
- features/crown_marketplace/manage_users/user_admin/view_user/mixed_roles.feature
- features/crown_marketplace/manage_users/user_support/edit_user.feature
- features/crown_marketplace/manage_users/user_support/validations/edit_user_validation.feature
- features/crown_marketplace/manage_users/user_support/view_user/assorted_details.feature
- features/crown_marketplace/manage_users/user_support/view_user/full_details.feature
- features/crown_marketplace/manage_users/user_support/view_user/mixed_roles.feature
- features/step_definitions/crown_marketplace/cognito_steps.rb
- features/step_definitions/crown_marketplace/manage_users_steps.rb
- features/support/pages/manage_users.rb
- spec/controllers/crown_marketplace/manage_users_controller_spec.rb
- spec/helpers/crown_marketplace/manage_users_helper_spec.rb
- spec/services/cognito/admin/user_spec.rb
Ticket: [FMFR-1341](https://crowncommercialservice.atlassian.net/browse/FMFR-1341)
In this commit I have added the page to edit the email status.
I have added/updated the specs and feature tests to reflect these changes
[FMFR-1341]: https://crowncommercialservice.atlassian.net/browse/FMFR-1341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1341 - Add ability edit email status

- README.md
- data/cognito/email_templates/invitation_message.html
- data/cognito/email_templates/verification_message.html
Ticket: [FMFR-1321](https://crowncommercialservice.atlassian.net/browse/FMFR-1321)
I've added the AWS Cognito email templates in the data folder so that we have a copy of them.
These templates are only used in AWS Cognito
[FMFR-1321]: https://crowncommercialservice.atlassian.net/browse/FMFR-1321?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1321 - Add the cognito email templates and update the README

- app/javascript/.eslintrc.json
- app/javascript/packs/application.js
- app/javascript/src/facilitiesManagement/buildings/buildingDetailsInStorage.ts
- app/javascript/src/facilitiesManagement/buildings/buildingType.ts
- app/javascript/src/facilitiesManagement/contactDetailsInStorage.ts
- app/javascript/src/facilitiesManagement/detailsLinks.ts
- app/javascript/src/facilitiesManagement/detailsStorage.ts
- app/javascript/src/facilitiesManagement/filterTable.ts
- app/javascript/src/facilitiesManagement/findAddress.ts
- app/javascript/src/facilitiesManagement/numberWithCommas.ts
- app/javascript/src/facilitiesManagement/procurements/chooseServicesForBuilding.ts
- app/javascript/src/facilitiesManagement/procurements/contractExtensions.ts
- app/javascript/src/facilitiesManagement/procurements/resultsToggle.ts
- app/javascript/src/facilitiesManagement/procurements/selectRegion.ts
- app/javascript/src/facilitiesManagement/rm3830/addNestedAttributes.ts
- app/javascript/src/facilitiesManagement/rm3830/admin/adminUploadProgress.ts
- app/javascript/src/facilitiesManagement/rm3830/admin/managementReport.ts
- app/javascript/src/facilitiesManagement/rm3830/bulkUploadProgress.ts
- app/javascript/src/facilitiesManagement/uploadProgress.ts
- app/javascript/src/shared/checkboxAccordion.ts
- app/javascript/src/shared/cookieBanner.ts
- app/javascript/src/shared/googleAnalytics.ts
- app/javascript/src/shared/passwordStrength.ts
- app/javascript/src/shared/stepByStepNav.ts
- app/views/home/cookie_settings.html.erb
- app/views/layouts/_cookie-banner.html.erb
- config/locales/en.yml
- package.json
- yarn.lock
Now that we have got webpack working and I have set up the TypeScript how I want it, I have decided to use standard typescript linting to maintain the quality of our TypeScript.
> Use `standard-with-typescript` for linting

- config/locales/views/facilities_management.rm3830.en.yml
Ticket: [FMFR-1359](https://crowncommercialservice.atlassian.net/browse/FMFR-1359)
Update the banner text to warn if the imminent closure
[FMFR-1359]: https://crowncommercialservice.atlassian.net/browse/FMFR-1359?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1359 - Update the banner for RM3830

- TAGS
Remove TAGS file, I am not sure why it exists in the first place
> Remove TAGS file

- app/controllers/facilities_management/rm3830/admin/uploads_controller.rb
- app/views/facilities_management/rm3830/admin/supplier_framework_data/index.html.erb
- app/views/facilities_management/rm3830/admin/uploads/index.html.erb
- spec/controllers/facilities_management/rm3830/admin/supplier_framework_data_controller_spec.rb
- spec/controllers/facilities_management/rm3830/admin/uploads_controller_spec.rb
Ticket: [FMFR-1366](https://crowncommercialservice.atlassian.net/browse/FMFR-1366)
Prevent file uploads on RM3830 now that the framework has expired
[FMFR-1366]: https://crowncommercialservice.atlassian.net/browse/FMFR-1366?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1366 - Prevent file uploads on RM3830 now that the framework has expired

- app/views/facilities_management/buyer_details/edit.html.erb
Ticket: [FMFR-1396](https://crowncommercialservice.atlassian.net/browse/FMFR-1396)
[FMFR-1396]: https://crowncommercialservice.atlassian.net/browse/FMFR-1396?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1396 - Make the telephone number a number input

- config/locales/en.yml
Ticket: [FMFR-1397](https://crowncommercialservice.atlassian.net/browse/FMFR-1397)
[FMFR-1397]: https://crowncommercialservice.atlassian.net/browse/FMFR-1397?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> FMFR-1397 - Update email from support@ to the correct info@

- CHANGELOG.md
- db/migrate/20231031103327_rename_tables_with_long_names.rb
I've run this in preview to make sure it fixes things.
> Update migration to avoid issue we have had on higher environments

- CHANGELOG.md
- Dockerfile
> Release v6.1.1

- CHANGELOG.md
- app/controllers/facilities_management/rm6378/procurements_controller.rb
- app/models/facilities_management/rm6378/procurement.rb
- app/models/jurisdiction.rb
- app/models/service.rb
- app/services/facilities_management/rm6378/supplier_shortlist_spreadsheet_creator.rb
- app/views/facilities_management/rm6378/procurements/show.html.erb
- config/locales/views/facilities_management.rm6378.en.yml
- config/routes.rb
- features/facilities_management/rm6378/procurements/saved_searches.feature
- features/facilities_management/rm6378/procurements/what_do_i_do_next.feature
- features/facilities_management/rm6378/quick_view/result_complex_scenario.feature
- features/facilities_management/rm6378/quick_view/results.feature
- features/step_definitions/facilities_management/rm6378/quick_view_steps.rb
- features/support/pages/quick_view.rb
- features/support/pages/rm6378/procurement.rb
- spec/controllers/facilities_management/rm6378/procurements_controller_spec.rb
- spec/models/facilities_management/rm6378/procurement_spec.rb
- spec/models/jurisdiction_spec.rb
- spec/models/service_spec.rb
- spec/services/facilities_management/rm6378/supplier_shortlist_spreadsheet_creator_spec.rb
Ticket: [NDF-85](https://crowncommercialservice.atlassian.net/browse/NDF-85)
[NDF-85]: https://crowncommercialservice.atlassian.net/browse/NDF-85?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> NDF-85 - Added the show page and spreadsheet download for the new FM framework
