Crown-Commercial-Service/crown-marketplace

Dockerfile

This adds a marker comment that the build process will use to add ENV variables, based upon entries within the Parameter Store, that will arrive in a later PR within the CMpDevEnvironment repository.

Add marker for Parameter Store variables

---

pipeline_pre_build_tests.sh
pipeline_run_build_tests.sh

This adds two scripts that can integrate with the AWS CodePipline and CodeBuild to run the same tests that Travis/CI is currrently executing.
They will not be used unless the deployment specifies running tests, via enable_tests within the terraform definition.

Add build test scripts

---

app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/error-message/_error-message.scss
app/assets/stylesheets/components/error-summary/_error-summary.scss
app/assets/stylesheets/components/label/_label.scss
app/assets/stylesheets/components/master-vendor-record/_master-vendor-record.scss
app/assets/stylesheets/components/supplier-record/_supplier-record.scss
app/assets/stylesheets/components/typography/_typography.scss
app/views/journey/_managed_service_providers_explanation.html.erb
config/locales/en.yml

Improved font-weight of Supply Teachers in general. Also fixed spacing problems of typography in the individual worker / managed service provider selection page.

Improve typography for supply teachers

---

app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/master-vendor-record/_master-vendor-record.scss
app/assets/stylesheets/components/table/_table.scss
app/models/supply_teachers/rate.rb
app/views/supply_teachers/suppliers/_master_vendor.html.erb
spec/features/managed_service_providers.features_spec.rb
spec/views/supply_teachers/suppliers/_master_vendor.html.erb_spec.rb

- `features/managed_service_providers.features_spec.rb:38` fails. We believe this is because the `with_terms` parameter of `have_rates` is now obsolete because every row has a value?
- We fixed `_master_vendor.html.erb_spec.rb` by removing the `terms` from `expect(rendered).to have_text(/11\.0%\s/)`. Please confirm if this is the correct way.
https://trello.com/c/pyhVSZIJ/167-clean-up-repeating-labels-on-master-service-provider-page
- Mark-up label moved to the top
- govuk-table introduced
- New styling for supplier records
- Fixed term / Nominated workers rates repeated 3 times

styling the master vendor page

---

app/assets/stylesheets/components/supplier-record/_supplier-record.scss

https://trello.com/c/GLvM4Gf7/210-fix-download-icons
- Added back the green colour for download icons

fixed download icons

---

app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/footer/_footer.scss
app/helpers/application_helper.rb
app/views/facilities_management/suppliers/_supplier.html.erb
app/views/home/gateway.html.erb
app/views/layouts/application.html.erb
app/views/management_consultancy/suppliers/_supplier.html.erb
app/views/supply_teachers/branches/_branch.html.erb
app/views/supply_teachers/branches/index.html.erb
config/locales/en.yml

https://trello.com/c/XAG2HyLk/161-accessibility
- Changed background-color for the grey part of footer for accessibility
- Added aria-label for accessibility

161 accessibility

---

app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/inset-text/_inset-text.scss
app/views/supply_teachers/branches/index.html.erb
spec/views/supply_teachers/branches/index.html.erb_spec.rb

60-buyers-can-see-the-selections-theyve-made-to-refine-the-shortlist-of-suppliers
- Use inset-text and list instead of table for the Buyers Selection section

Buyers selection section redesigned

---

app/assets/stylesheets/components/_all.scss
app/assets/stylesheets/components/st-supplier-page/_st-supplier-page.scss
app/views/supply_teachers/branches/index.html.erb
config/locales/en.yml

https://trello.com/c/xTQuNtzq/226-buyers-can-refine-the-search-results-by-location-search-radius
- Styled the distance switcher

(feature) styling the distance switcher

---

app/views/supply_teachers/home/index.html.erb
config/locales/en.yml

https://trello.com/c/l4hycEA2/257-change-service-name
- Change service name from 'Find supply teachers and non-teaching staff' to 'Find supply teachers and agency workers'

(fix) Change service name for Supply Teachers

---

app/views/temp_to_perm_calculator/home/fee.html.erb
config/locales/en.yml

https://trello.com/c/I94H6lGo/253-temp-to-perm-calculator-results-page-styling
- Changed the label from `Fee` to `Temp-to-perm fee`
- Put all content into the full width container
- Put the content below the panel into the 2/3 container

(fix) styling the temp-to-perm results page

---

app/views/supply_teachers/journey/looking_for.html.erb

275-visually-distinguish-the-calculator-option-from-the-options-to-continue-the-primary-journey
- Added "or" to visually distinguish the calculator option from others.

(fix) visually distinguished the calculator option

---

app/views/supply_teachers/home/index.html.erb

https://trello.com/c/61z7N0qv/278-amend-start-page-content-to-remove-reference-to-saving
- Update bullet point content of homepage of Supply Teachers

(fix) ST homepage bullet point updated

---

app/assets/stylesheets/components/typography/_typography.scss
app/views/supply_teachers/home/index.html.erb

https://trello.com/c/6P7FatyC/264-explain-what-accreditation-these-suppliers-have-and-what-it-tells-buyers-about-them
- Added the explanation of accreditation suppliers to the bottom of Start page

(fix) added accreditation message to start page

---

app/views/supply_teachers/journey/contract_start.html.erb
config/locales/en.yml

https://trello.com/c/ZFEIIHXN/209-iterate-the-content-for-temp-to-perm-calculation
- Re-wording the 5 questions
- Re-ordering the questions
- Changed the hint of day rate

(fix) re-wording and re-writing calculator questions

---

app/views/supply_teachers/home/index.html.erb

https://trello.com/c/JUqFTkut/294-add-information-about-calculator-to-supply-teachers-start-page
- Add a bullet point to the Start page of Supply Teachers to provide information about the calculator.

(fix) add information about calculator to Start page of Supply Teachers

---

app/assets/stylesheets/components/calculator-form/_calculator-form.scss
app/views/supply_teachers/journey/temp_to_perm_calculator.html.erb
config/locales/en.yml

https://trello.com/c/uLV1yMSF/252-update-mark-up-question-on-temp-to-perm-calculator
- Added % sign to the mark-up input box
- Changed the example of mark-up from 40 to 20

(fix) update styling of mark-up input of calculator

---

app/views/supply_teachers/home/index.html.erb

81-buyers-understand-their-obligations-for-using-supplier-data
- Added obligations of using supplier data to the bottom of the page.

(feature) Obligations of using supplier data added

---

app/views/supply_teachers/home/index.html.erb

316-minor-content-change-to-start-page
- Move the DfE sign-in notice to above the start button
- Change the copy of below the start button

(fix) move DfE sign-in notice above the start button

---

app/views/supply_teachers/suppliers/neutral_vendors.html.erb
config/locales/en.yml
spec/features/supply_teachers/managed_service_providers.features_spec.rb

https://trello.com/c/5fLXI9XF/289-improve-content-on-neutral-vendor-supplier-list
- Removed the table layout for supplier records in neutral vendor page
- Used paragraphs to supplier records
- Added `There is only one neutral vendor on this framework.` to the top when there's only one supplier
@chrisroos as discussed please help to see if you can fix the test. In `managed_service_providers.features_spec.rb` there are 2 lines checking the mark-up and daily fee but table label `job_type` is removed so we need to change it in spec too.

(fix) update the layout of neutral vendor page

---

app/views/supply_teachers/suppliers/neutral_vendors.html.erb
config/locales/en.yml

https://trello.com/c/5fLXI9XF/289-improve-content-on-neutral-vendor-supplier-list
- Combine the last 2 paragraphs for neutral vendor page

(fix) combine the last 2 paragraphs

---

app/assets/stylesheets/components/fieldset/_fieldset.scss

https://trello.com/c/dpM6Smiv/308-browser-testing-legend-margins
- Set margin of the questions `legend` to 0
- Set padding-bottom of the question `legend` to 15

(fix) fixed legend margins on Samsung Internet browser

---

app/views/supply_teachers/suppliers/master_vendors.html.erb
config/locales/en.yml

https://trello.com/c/lGpj9c4N/325-change-guidance-for-user-on-what-to-do-with-supplier-list-master-vendor-route
- Added link for information of further competition
- Added esourcing link
- Updated link of full version order form

(fix) updated what to do next section for master vendor page

---

config/locales/en.yml

In keeping with the language on the supply teacher landing page on GOV.UK, change from `An agency to manage an individual worker` to `An agency who can provide your school with an individual worker`.

(chore) Change wording of looking for individual worker answer

---

config/locales/en.yml

This is now in line with the supply teachers landing page on GOV.UK

(chore) Temp-to-perm calculator heading better reflects DfE policy

---

app/assets/stylesheets/components/inset-text/_inset-text.scss
config/locales/en.yml

- Make the text in line with the supply teachers landing page on GOV.UK
- Increase the font size slightly

Changes to the mark-up explanation text

---

README.md
config/environments/production.rb

The production CMp application was showing a lot of unneeded logging. The `log_level` in `production.rb` is set to `:debug` which is too low for production (normally)
This change means the log level can be set on deployment (via Terraform etc). If the log level param is not set, it defaults to `:info`
If the log level needs to be changed for whatever reason, it can be done via ops.

(chore) Set logging level in production environments via an env variable

---

app/assets/stylesheets/components/footer/_footer.scss

https://trello.com/c/YjSHwvEH/961-footer-logo-need-to-be-resized-also
- Fixed size of footer logo

(fix) Footer logo size fixed

---

app/models/login/dfe_login.rb
spec/models/login/dfe_login_spec.rb

Suspect that the issue with https://trello.com/c/iWC1sXTr/971-allow-multi-academy-trusts-to-login is that the school type ID is being cast to a number after MAT's choose their desired school on DfE login.
Even if this is not the case, this is still a nice belt-and-braces solution

(bugfix) Cast school type ids to strings

---

.rubocop.yml
app/assets/stylesheets/components/supplier-record/_supplier-record.scss
app/calculators/temp_to_perm_calculator/calculator.rb
app/controllers/supply_teachers/branches_controller.rb
app/models/generic_journey.rb
app/models/supply_teachers/branch_search_result.rb
app/models/supply_teachers/journey/results.rb
app/models/supply_teachers/supplier_mark_up.rb
app/views/supply_teachers/branches/_branch.html.erb
app/views/supply_teachers/branches/index.html.erb
config/locales/en.yml
spec/factories/supply_teachers_branch_search_result.rb
spec/features/supply_teachers/supplier_markup_calculator.features_spec.rb
spec/models/generic_journey_spec.rb
spec/models/supply_teachers/supplier_mark_up_spec.rb
spec/views/supply_teachers/branches/_branch.html.erb_spec.rb
spec/views/supply_teachers/branches/index.html.erb_spec.rb

We need to allow the supplier mark-up calculation to happen on-screen in a way that the buyer can meaningfully compare the calculations for the quotes from the different suppliers
Allow the calculations to be done without submitting the form, via Ajax

Supplier mark-up calculation on results page

---

app/models/supply_teachers/journey/temp_to_perm_calculator.rb
spec/models/supply_teachers/journey/temp_to_perm_calculator_spec.rb

We had an issue with using `Date.parse("YYYY-MM-DD")`, if you leave the year off it defaults to this year. Our tests that check for the presence of 'year' were passing incorrectly because they were using a single digit month for the day, which combined with the absence of the year produced an ArgumentError as expected. eg. `Date.parse("-1-1")` is invalid as our tests expected but `Date.parse("-1-11")` is valid
To get the tests failing in the right way we had to change the day used for each fixture to double digits.
We then fixed the check for the presence of year by telling the `Date` object which format we expect the date string to be in. Now if you omit the year you get an ArgumentError as expected.

(fix) Temp-to-perm calculator dates now require a year

---

app/models/supply_teachers/spreadsheet.rb
spec/models/supply_teachers/spreadsheet_spec.rb

https://trello.com/c/fJpIkAHZ/935-change-downloadable-calculator-to-have-clearer-instructions
- Insert an extra header to the spreadsheets
- Updated the header copy of mark-up calculator
- Added a fixed width for the fields of mark-up calculator
- Do not display the leading 0 if the mark-up percentage is in single digit

(chore) add extra header to the downloadable calculator

---

app/views/supply_teachers/branches/index.html.erb

https://trello.com/c/WiatSrp6/963-print-page-content
- Show distance selectors when printing the supplier list
- Show sidebar options when printing the supplier list

(fix) show distance selectors when printing supplier list

---

app/assets/stylesheets/components/sidebar/_sidebar.scss
app/assets/stylesheets/components/st-supplier-page/_st-supplier-page.scss

https://trello.com/c/WiatSrp6/963-print-page-content
- Removed URLs from distance selectors and download items when printing pages

(fix) remove url from distance and download items when printing

---

app/assets/stylesheets/components/supplier-record/_supplier-record.scss
app/models/supply_teachers/branch_search_result.rb
app/models/supply_teachers/journey/results.rb
app/models/supply_teachers/supplier_mark_up.rb
app/views/supply_teachers/branches/_branch.html.erb
app/views/supply_teachers/branches/index.html.erb
config/locales/en.yml
spec/features/supply_teachers/supplier_markup_calculator.features_spec.rb
spec/models/supply_teachers/supplier_mark_up_spec.rb
spec/views/supply_teachers/branches/index.html.erb_spec.rb

https://trello.com/c/rEDidMZB/958-content-about-online-calculator
- Update online calculator heading
- Change `supplier fee` to `agency fee`
- Change the heading of the calculate mark-up section at the sidebar
- Change copy of the calculate mark-up section at the sidebar
- Change button label of the calculate mark-up section sidebar

(chore) online calculator content update

---

app/models/login/base_login.rb
app/models/login/cognito_login.rb
app/models/login/dfe_login.rb
spec/models/login/cognito_login_spec.rb
spec/models/login/dfe_login_spec.rb

As the school type ID is sometimes nil, the existing log lines didn't look great, e.g.
`I, [2019-01-28T16:21:54.802929 #10] INFO -- : [8539db90-4ebe-4481-af6d-51f15a010248] Login attempt from dfe > email: <email>@deferrerstrust.com, school type id: , result: successful`
This commit removes the logging on the school type ID. This information can be obtained for DfE logins at https://github.com/Crown-Commercial-Service/crown-marketplace/blob/master/app/models/login/dfe_login.rb#L4
I have also added the framework to the login log lines to make it obvious which framework the user is trying to log in to.

(chore) Tidy up login log lines

---

app/models/supply_teachers/spreadsheet.rb
spec/models/supply_teachers/spreadsheet_spec.rb

https://trello.com/c/OOEJNiMO/982-update-downloadable-calculator-content
- Change the content of instructions for spreadsheets
- Change `Supplier name` to `Agency name` for spreadsheets
- Change `Supplier fee` to `Agency fee` for spreadsheets

(chore) update spreadsheet headings

---

app/views/supply_teachers/home/index.html.erb
config/locales/en.yml

https://trello.com/c/V6x5MtPB/973-revisit-guidance-for-accessing-to-agreement-without-existing-dfe-account
- Content changes made according to this document: https://docs.google.com/document/d/1xgE7svtK-ZzYZZA2HtB6K0DwTxj3-KrqHULQORUqefk/edit

(chore) content update for the start page

---

app/controllers/supply_teachers/branches_controller.rb
app/views/supply_teachers/branches/index.html.erb
spec/features/supply_teachers/supplier_markup_calculator.features_spec.rb

Only show notice when the rates are updated by the user.
Because the form is submitted via GET request if a user sends the URL to someone else, the other person will also see the notice. I think this ok though, because the goal of the notice is just to let the submitting user know that the content has changed.

(feature) Add notice to agency mark-up results page

---

app/views/supply_teachers/home/_between_9_and_12_weeks_and_enough_notice.html.erb
app/views/supply_teachers/home/_between_9_and_12_weeks_and_no_notice_date.html.erb
app/views/supply_teachers/home/_between_9_and_12_weeks_and_not_enough_notice.html.erb
app/views/supply_teachers/home/_within_first_8_weeks.html.erb
spec/views/supply_teachers/home/temp_to_perm_fee.html.erb_spec.rb

Trello: https://trello.com/c/WfFMLfun/991-correct-wording-for-scenario-4-5-6-and-7-for-temp-to-perm-calculator
Do not show the wording which advises how to avoid fees if the user is hiring the worker after 12 weeks.

(chore) Correct wording in temp-to-perm calculator

---

app/views/supply_teachers/home/_avoid_paying_fees.html.erb
spec/views/supply_teachers/home/_avoid_paying_fees.html.erb_spec.rb

ST-11 Results page content change
[DfE's request]
I’ve also noticed that the last paragraph of the results page for the TTP calculator still needs to be changed. We would like the statement to make it clear that by taking particular actions the school can pay 0.00 for taking the agency worker on. The current statement of:
Give notice to the agency on Thursday 28 February 2019 and make the worker permanent on Thursday 28 March 2019 so they've been in post for over 12 weeks and you provide 4 weeks’ notice.
Should be changed to:
If you give notice to the agency on Thursday 28 February 2019, and make the worker permanent on Thursday 28 March 2019 you will be charged £0.00 and avoid paying any temp­ to ­perm fee.
The £0.00 is important as it is immediately noticeable by the user and self­ …

https://pushback.atlassian.net/browse/ST-11

---

app/calculators/temp_to_perm_calculator/calculator.rb
app/controllers/supply_teachers/suppliers_controller.rb
app/views/supply_teachers/home/_avoid_paying_fees.html.erb
spec/calculators/temp_to_perm_calculator/calculator_spec.rb
spec/controllers/supply_teachers/suppliers_controller_spec.rb
spec/views/supply_teachers/home/_avoid_paying_fees.html.erb_spec.rb

On the Results page of the calculator:
Give notice to the agency on Thursday 28 February 2019 and make the worker permanent on Thursday 28 March 2019 so they've been in post for over 12 weeks and you provide 4 weeks’ notice.
Changed to:
If you give notice to the agency on Thursday 28 February 2019, and make the worker permanent on Thursday 28 March 2019 you will be charged £0.00 and avoid paying any temp-to-perm fee.
Also found a couple of bugs:
- number of chargeable days based on hire date would be < 0 if there are more than 60 days between contract start date and hire date
This was fixed and new tests were added.
- back button on all suppliers didn't redirect back

Results page content change

---

app/views/supply_teachers/home/index.html.erb

Problem: Currently, users aren't aware that there is more guidance content below the start button. This means they aren't aware what accreditation suppliers have, or what their obligations are for using the data contained in the service.
Solution: move start button to bottom of the page (below "before you start" and accreditation section)

Feature/ST-40 Start now button change

---

config/locales/en.yml

Added a full stop on the second phrase and removed 'will' from 'You will need to:'

Small copy fixes on legal-services start page. 

---

Gemfile.lock

If we update bundler version it brakes the AWS build

Switched bundler back

---

app/helpers/application_helper.rb
app/views/apprenticeships/home/download_provider.html.erb
app/views/facilities_management/gateway/index.html.erb
app/views/facilities_management/summary/index.html.erb
app/views/management_consultancy/gateway/index.html.erb
app/views/shared/_google_analytics.html.erb
spec/spec_helper.rb
spec/views/shared/_google_analytics.html.erb_spec.rb

Separated all GA tracking for SupplyTeachers. The only ones that are across platform now are: ga-crown-logo, ga-feedback-mailto, ga-support-mailto

feature/CP-73 GA only for ST

---

app/views/layouts/application.html.erb
config/locales/en.yml
public/404.html
public/422.html
public/500.html
public/maintenance.html

en,yml had brackets around the feedback link.
Also, code for IE versions less than 9 is now breaking - so that has been removed...

Remove brackets from feedback links - also remove <IE9 specific JS

---

app/controllers/facilities_management/beta/procurements_controller.rb
app/views/facilities_management/beta/procurements/edit.html.erb
app/views/facilities_management/beta/procurements/edit/_contract_name.html.erb
app/views/facilities_management/beta/procurements/edit/_estimated_annual_cost.html.erb
app/views/facilities_management/beta/procurements/edit/_tupe.html.erb

Procurements controller edit action - removed the now redundant and error-causing redirect.
Also fixed-up the title banner and made consistent for the new edit pages....

FM-275 Bug - Procurements editing problem

---

Gemfile
Gemfile.lock

The latest version of omniauth_openid_connect tries to decode id_token even if `response_type: :code`
Updating Gemfile to use the fix: https://github.com/m0n9oose/omniauth_openid_connect/issues/40

Dfe Sign in fix

---

app/controllers/facilities_management/beta/spreadsheet_test_controller.rb
app/services/facilities_management/deliverable_matrix_spreadsheet_creator.rb

Added a second sheet to the deliverable matrix spreadsheet. For the QA work, I've alternated the services that each building needs to show how services appear when they've been selected vs not selected.

Add services_matrix sheet on FM DM spreadsheet

---

db/migrate/20190724080344_change_timestamp_defaults_fm_regions.rb
db/schema.rb

On cmp-dev some migrations have been edited after being run so we are missing timestamps on fm_regions. Attempting to fix this by checking if the timestamps exist and adding them to the table if they don't

Hotfix migrations

---

app/models/facilities_management/procurement_building_service.rb
spec/models/facilities_management/procurement_building_service_spec.rb

Fixed validations on context - otherwise all standards are validated in the same time. 
Also, fixed volume validation which should only be validated if volume is present

FM-409 fix validations

---

app/views/facilities_management/journey/choose_services.html.erb
config/locales/views/facilities_management.en.yml

Added a header to the 'Start a new procurement page' to bring it in line with the other pages. I placed the text for the heading in the 'facilities_management.en.yml'.

Adding a heading to 'start a new precurment'

---

app/assets/javascripts/facilities_management/beta/building_management/building.js
app/assets/javascripts/facilities_management/beta/building_management/building_gross_internal_area.js
app/assets/javascripts/facilities_management/beta/building_management/building_security_type.js
app/views/facilities_management/beta/buildings_management/building.html.erb
app/views/facilities_management/beta/buildings_management/building_gross_internal_area.html.erb

I have updated the char count JavaScript so that it works when the page is reloaded. This affected the building 'name' and 'description' in the building details, the building GIA input and the 'other' security text box. I also change the HTML so that didn't need hardcoded text so that only the JavaScript would put it in. I also refactored my previous solution to reduce the lines of code.

JavaScripts changed for building char counts

---

app/views/facilities_management/beta/procurement_buildings/_building_standards.html.erb
app/views/facilities_management/beta/procurement_buildings/_cleaning_standards.html.erb
app/views/facilities_management/beta/procurement_buildings/_ppm_standards.html.erb

CSI-42 On the services information page, as selecting 'change' on different services led to different standard pages (PPM standards, Cleaning standards and building fabric standards) users may be confused by the inconsistency of numbering. I have removed the numbering from the standards pages so only the service title remains.

removed numbering from services pages

---

app/assets/javascripts/facilities_management/beta/procurement/FormValidationComponent.js
app/models/concerns/procurement_validator.rb
app/views/facilities_management/beta/procurements/_quick_search_form.html.erb
config/locales/views/facilities_management.en.yml

As part of this ticket I also completed the work on CSI-48 as it was related to the validation of the quick search name.
I added the regex pattern to the view so that it would only allow alphanumeric characters, spaces and these characters: '-_'. For the part on CSI-48 I added the same regex but removed the space character so that only the permitted characters  can be used at the start and end to prevent the quick search name from having preceding or trailing spaces. This prevents the issue of someone being able to save the same quick search name twice by putting a space at the start or end of the name.
I added a validation to the model so that both the front and back end are secure from a user putting in invalid characters. I also added an invalid message into the `.yml` file.

Added a regex pattern in view and added validation in the model

---

app/controllers/facilities_management/beta/procurements_controller.rb
app/models/concerns/procurement_validator.rb
app/views/facilities_management/beta/procurements/_quick_search_form.html.erb
spec/models/facilities_management/procurement_spec.rb

I created a simple method that takes the quick search name and gets rid of the excess spaces. This prevents a user from creating basically identical search names (like "Test 1" and "Test    1"). 
This also meant that I could update the regex for the name pattern as the splitting of the name automatically removes leading and trailing spaces.
Overall, this solution prevents the user from putting in names that would appear identical when viewed on the page.

Added method to remove excess spaces from name and refactored regex

---

app/views/facilities_management/beta/procurements/_procurement_building_services.html.erb

Detailed summary page services for building should all now be lower case, as is in line with ticket CSI-53.

bullet points on detailed summary page now all lowercase.

---

app/models/facilities_management/procurement.rb
app/models/facilities_management/procurement_building.rb
spec/factories/facilities_management_procurement.rb
spec/factories/facilities_management_procurement_building_services.rb
spec/models/facilities_management/procurement_spec.rb

@Chee-Ng's ticket, so he will pick up any changes that need to be made.

Remove ProcurementBuildingServices with codes not in the procurement service_codes

---

app/helpers/application_helper.rb
app/views/layouts/_header-banner.html.erb

Fixed formatting issues for rubocop
Renamed constant to make it more descriptive
The main fix for this solution was to add 'facilities_management/beta/home' to the 'PLATFORM_LANDINGPAGES'. This did remove back to start from the landing page but then resulted in other issues. Because the landing pages for FM now look different from the other landing pages (they say 'Find a facilities management supplier' rather than 'Crown Marketplace') exceptions needed to be added for the FM landing pages. This means that these pages require a different logic, so this needed to be added.
I created a new constant with the two landing pages path in them and created a new method `fm_landing_page`. This enabled me to use the correct logic and the right point so that the pages where consistent with the new …

Page now displays the correct content by making exception for fm

---

config/locales/views/facilities_management.en.yml

Reworded the "Estimated annual cost should be an amount of money like 12000 or 1200.45" to "The estimated annual cost should be an amount of money, such as £12,000 or £1200.45"

added £ signs and commas in the estimated annual cost error

---

app/services/cognito/forgot_password.rb
app/services/cognito/sign_in_user.rb
app/views/ccs_patterns/home/cog_forgot_password_reset.html.erb
app/views/facilities_management/passwords/edit.html.erb
app/views/legal_services/passwords/edit.html.erb
app/views/management_consultancy/admin/passwords/edit.html.erb
app/views/management_consultancy/passwords/edit.html.erb
app/views/supply_teachers/admin/passwords/edit.html.erb
app/views/supply_teachers/passwords/edit.html.erb
config/locales/en.yml
config/locales/views/facilities_management.en.yml
spec/services/cognito/forgot_password_spec.rb
spec/services/cognito/sign_in_user_spec.rb

User Account Enumeration - The application was found to present error messages that facilitated the enumeration of valid user accounts.
Recommendation: BSI recommends that the application be configured to return generic error messages to ensure that they do not indicate whether a valid user account has been provided or not.
Current validation messages display the following: -
When password is wrong: Incorrect username or password.
When user email is wrong: User does not exist.
When resetting password and putting the wrong email in: Username/client id combination not found.
First two have been amended to always say 'Incorrect username or password'
The second one has been amended so it does not show an error message, but it now redirects to the password reset page where you see a message …

MC & LS & ST & FM ITHC Remediation - User Account Enumeration changes

---

app/assets/javascripts/facilities_management/beta/building_management/building_security_type.js
app/controllers/facilities_management/beta/buildings_management_controller.rb
app/views/facilities_management/beta/buildings_management/_buildings_steps_header.html.erb
app/views/facilities_management/beta/buildings_management/building_security_type.html.erb

Updated the Javascript to prevent the user from leaving the 'other' security description blank, which originally made the description say other. This also needed an additional error message for when the was no description so this was also added. Finally I changed the other message in the controller to be blank ("") by default as the JS would immediately change it being so on the page loading anyway.

Adjusted the javascript and added error message for no description (FM-624)

---

app/views/facilities_management/beta/supplier/offer/accepted.html.erb
app/views/facilities_management/beta/supplier/offer/declined.html.erb

- Removed the gap between the green banner and the back button
- Made the text stay on one line

Formatting fixes on offer declined page (HTML)

---

app/controllers/facilities_management/beta/procurements_controller.rb
app/helpers/layout_helper.rb
app/views/facilities_management/beta/procurements/_continue_button_footer.html.erb
app/views/facilities_management/beta/procurements/direct_award_pricing.html.erb
app/views/facilities_management/beta/procurements/further_competition.html.erb
app/views/facilities_management/beta/procurements/results.html.erb
app/views/facilities_management/beta/procurements/show.html.erb
config/routes.rb
db/migrate/20200115160444_add_eligible_for_da_to_facilities_management_procurements.rb
db/schema.rb

There are changes here in the layout helper
Also, procurements controller and the associated views
And a migration to run

Refactor Results page continuation to use CRUD routes

---

app/controllers/facilities_management/beta/summary_controller.rb
app/models/facilities_management/summary_report.rb
app/services/facilities_management/direct_award_spreadsheet.rb
spec/models/facilities_management/summary_report2_spec.rb
spec/models/facilities_management/summary_report_spec.rb

Needed to add a row in the direct_award excel ,contract rate card worksheet, table 2 for cafm and help. a requirement was to not add a row for cafm if no service selected cafm, same for help ; this functionality took most of the code changes.

FM-682 add cafm, help to table 2 in contract rate card worksheet

---

app/controllers/facilities_management/beta/procurements_controller.rb
app/models/facilities_management/procurement.rb
app/models/facilities_management/summary_report.rb
app/services/facilities_management/direct_award_eligible_suppliers.rb
spec/models/facilities_management/procurement_spec.rb

- rewritten save_eligible_suppliers to save state and other attributes needed on the next step
- fixed assessed value calculator to take into account tupe and estimated cost

Assessed value bug

---

app/controllers/application_controller.rb

signing out from cookies page redirected user to supply teachers as opposed to FM page. 
- this will be a problem in the future, as it will now default to FM (as opposed to a more general page - maybe homepage?) but fixes bug to meet acceptance criteria.

bug fix - changed gateway url to default to fm gateway

---

app/views/shared/_google_analytics.html.erb
spec/views/shared/_google_analytics.html.erb_spec.rb

Google Analytics now runs on all pages as we're filtering the views through GA based on path

Google analytics now runs on all pages

---

app/views/facilities_management/beta/admin/supplier_rates/supplier_benchmark_rates.erb
app/views/facilities_management/beta/admin/supplier_rates/supplier_framework_rates.erb
app/views/layouts/admin/_header-banner.html.erb
app/views/layouts/admin/_header-dashboard-link.html.erb

Fixes for spacing issues and admin header link appearing even if user is logged out.

FM-811-fix-for-dashboard-link-and-breadcrum

---

app/models/facilities_management/procurement_supplier.rb
app/workers/facilities_management/contract_sent_reminder.rb
spec/models/facilities_management/procurement_spec.rb
spec/models/facilities_management/procurement_supplier_spec.rb

- Create worker to send reminder email
- Add method to trigger worker in the procurement_supplier model
- Create tests for the time_delta_in_days
- Add stup to procurement_spec
- Update the method to us perform_at
- Update the method so that it works
- Added method to check worker is called

FM-874 Trigger Contract Sent Reminder

---

app/assets/javascripts/facilities_management/beta/procurement/QuickSearchResultsAssistant.js
app/models/ccs/fm/supplier.rb
spec/models/ccs/fm/supplier_spec.rb

Fetch suppliers having ANY of the selected regions and services rather than ALL. Filter displayed suppliers having ALL selected regions and services rather than ANY. Apply this filter on page load as well as filter change.

FM-857: Fix supplier query and filter

---

Gemfile
Gemfile.lock
app/assets/javascripts/facilities_management/beta/contract/contract_forms.js
app/assets/javascripts/facilities_management/beta/contract/copy_procurement.js
app/controllers/facilities_management/beta/procurements/copy_procurement_controller.rb
app/helpers/facilities_management/beta/procurements/copy_procurement_helper.rb
app/models/facilities_management/procurement.rb
app/models/facilities_management/procurement_building.rb
app/views/ccs_patterns/prototype/create_a_copy.html.erb
app/views/facilities_management/beta/procurements/_about_the_work.html.erb
app/views/facilities_management/beta/procurements/_results.html.erb
app/views/facilities_management/beta/procurements/contracts/_closing_direct_award_offer.html.erb
app/views/facilities_management/beta/procurements/contracts/_create_a_copy.html.erb
app/views/facilities_management/beta/procurements/contracts/show.html.erb
app/views/facilities_management/beta/procurements/copy_procurement/new.html.erb
app/views/facilities_management/beta/procurements/da_buyer/_did_you_know.html.erb
app/views/facilities_management/beta/supplier/contracts/edit.html.erb
config/routes.rb
spec/factories/facilities_management_procurement.rb
spec/factories/facilities_management_procurement_contact_detail.rb
spec/factories/facilities_management_procurement_pension_funds.rb
spec/models/facilities_management/procurement_copy_spec.rb

- Add the ability to copy procurements
- Add pages and routes for copying of the procurement
- Update pages to remove JS error
- Create view for the create a copy page
- Changed routes
- Routing for controllers
- Javascript for the character counts
- Finish creating a copy page
- fix some errors
- Fix issue with alignment
- Fix layout of page
- Move creation of procurement to model
- Set up factories for tests
- Create initial tests for the copying of a procurement
- Update the copying in the model
- Create tests for copying the procurement

Create a copy of a procurement

---

app/controllers/facilities_management/beta/procurements/contracts_controller.rb
app/controllers/facilities_management/beta/supplier/contracts_controller.rb
app/models/ability.rb
app/models/facilities_management/procurement_supplier.rb
spec/controllers/facilities_management/beta/procurements/contracts_controller_spec.rb
spec/controllers/facilities_management/beta/supplier/contracts_controller_spec.rb

- Add authorisation for when the user clicks on the link
- Create tests for the authenticate user buyer side
- Add tests for authentication on the supplier side
To do this I created a method in the controller which checks that the contract they're trying to view through the link belongs to them

FM-891-Authenticate-Supplier-And-Buyer-Dashboard-Link

---

app/helpers/application_helper.rb
app/views/layouts/_cookie-banner.html.erb

The cookie page will now render with the header-banner it was requested from.
If it can't do that then it renders the header banner for supply teachers which is the default header-banner.
The most important thing is that it should no longer crash

Fix issue with cookie page where it would not load

---

app/views/layouts/_cookie-banner.html.erb

Cookie banner now takes into account where it comes from

Cookie page has correct header banner

---

app/services/procurement_csv_export.rb

A bug was discovered where nil lot numbers cause an error on the Procurements CSV export. This resolves it.
Ticket: https://pushback.atlassian.net/browse/FM-895?atlOrigin=eyJpIjoiOTAxNjAzZDk3YTU2NGYwYzhiODViNTkzMmQ1ZmE4YTUiLCJwIjoiaiJ9

FM 895: Bug - Handle nil lot number

---

app/models/facilities_management/procurement.rb
app/services/facilities_management/assessed_value_calculator.rb
config/locales/views/facilities_management.en.yml
spec/models/facilities_management/procurement_spec.rb
spec/models/facilities_management/procurement_supplier_spec.rb

- Rates should be frozen before the assessed value is calculated
- Changed eligible_suppliers service name because it does a lot more than that
- Some refactoring of procurement.rb so it creates only one instance of the new assessed_value_calculator service
- Copy changes because the copy has changed

Assessed value fix

---

app/views/facilities_management/beta/buyer_details/edit.html.erb
app/views/facilities_management/beta/procurements/_quick_search_form.html.erb
app/views/facilities_management/beta/procurements/further_competition/_further_competition_partial.html.erb
app/views/facilities_management/beta/procurements/new.html.erb

removed display_potential_errors and replace with display_errors as well as disable JavaScript on new procurement page
Overall, this should have no impact to the user

FM-986-HTML-Validation

---

app/assets/stylesheets/facilities_management/beta/building_services.scss
app/views/facilities_management/beta/procurements/long_list/_lot1a.html.erb
app/views/facilities_management/beta/procurements/long_list/_lot1b.html.erb
app/views/facilities_management/beta/procurements/long_list/_lot1c.html.erb

- Remove unnecessary labels and inputs as no Quick Search filter
- Add CSS for when the element is focused over

FM-981/Focus Visible – Visible Tab Focus Indicator

---

app/models/facilities_management/procurement.rb
app/models/facilities_management/summary_report.rb
spec/models/facilities_management/procurement_spec.rb

Logic fixed for FM-567 as we need to check if any service has FW price missing and any has BM price missing, instead of any service having FW and BM missing

FM-567 logic fix

---

app/models/facilities_management/procurement.rb
spec/models/facilities_management/procurement_spec.rb

Services not taken into account are the ones that are missing both FW and BM pricing. Also service standard should be sent through when checking for pricing.

FM-567 fix

---

app/assets/stylesheets/application.css

Fix for now removes bottom-border.

Fix for border-bottom for table now only removes isolated tr not all cells

---

app/controllers/application_controller.rb
app/controllers/facilities_management/sessions_controller.rb
app/controllers/facilities_management/supplier/sessions_controller.rb
app/views/facilities_management/procurements/contracts/sent/_sent.html.erb
app/views/facilities_management/procurements/edit/_procurement_buildings.html.erb
app/views/facilities_management/procurements/edit/_services.html.erb

fix the layout on contract sent page, select building and checkbox for select service
buyer sign out button go to the sign in page and not start page
supplier clicking email link should get them to the right page

clicking link on email will now go to the right place for supplier

---

app/assets/javascripts/facilities_management/beta/procurement/FormValidationComponent.js
app/helpers/application_helper.rb
app/helpers/errors_helper.rb
app/views/facilities_management/procurement_buildings_services/_day_section.html.erb

- Change display potential errors back end component
- Update form validator for display_potential_errors
Display potential errors created many error labels that had the same ID. Under the rules for accessibility this is not allowed. Therefore I have updated this method so that the ID's are uniq. This also required a change to the form validator to make sure it gets the right message when in use. This change should lead to no noticeable difference from before.

Change display potential errors for html accessibility

---

config/locales/views/facilities_management.en.yml
spec/models/facilities_management/procurement_pension_fund_spec.rb

when user enters 0 for initial start date, correct error message is shown

FM-1178 Contract start date error message

---

app/assets/javascripts/facilities_management/beta/buildings/buildings.js

buildings.js syntax error for querySelector commands which have resolved the Safari12 issues.

FM-1091 Lift button issue

---

app/assets/javascripts/common/common.js
app/assets/javascripts/facilities_management/beta/buyer/buyer_details.js
app/assets/javascripts/facilities_management/beta/procurement/ContractDetails.js
app/controllers/facilities_management/procurements_controller.rb
app/views/facilities_management/buyer_details/edit.html.erb
app/views/facilities_management/procurements/edit/_new_authorised_representative_address.html.erb
app/views/facilities_management/procurements/edit/_new_contact_details.html.erb
app/views/facilities_management/procurements/edit/_new_invoicing_address.html.erb
app/views/facilities_management/procurements/edit/_new_notices_address.html.erb

The main focus of this is the tabbing and changing of the focus when entering an address on the Buyer details and the Contact Details changes (Invoice, Authorised and Notice). The main changes are:
- get the focus and tabIndex values to be correct depending on the state of the page
- Update buyer details page so that it has the matching (and hopefully correct) logic
- Fix misspelling of _adress_ to _address_

FM-1165 Part 2: Buyer & Contact Details Tabbing and Accessibility

---

app/services/cognito/sign_in_user.rb
config/locales/views/facilities_management.en.yml
spec/services/cognito/sign_in_user_spec.rb

> I did not share code for
rescue Aws::CognitoIdentityProvider::Errors::UserNotFoundException
rescue Aws::CognitoIdentityProvider::Errors::ServiceError
as robocop complained about hidden exception order.   
>I ignored the serviceError exception message text  assumed it is a username/password issue as the requirement was for a fixed message.

login error message changes

---

app/controllers/facilities_management/procurements_controller.rb
config/routes.rb
spec/controllers/facilities_management/procurements_controller_spec.rb
spec/factories/facilities_management_procurement_authorised_contact_detail.rb
spec/factories/facilities_management_procurement_contact_detail.rb
spec/factories/facilities_management_procurement_invoice_contact_detail.rb
spec/factories/facilities_management_procurement_notices_contact_detail.rb
spec/factories/facilities_management_procurement_pension_funds.rb

Before this work was done the coverage was 46.12%
After finishing the work the coverage is now 94.36%
- Add tests for the show pages
- Added tests for updates concerning results
- testing that the determination of state changes is implemented correctly from the results page
- Tests for continue of da
- Fix bug when user goes to procurement url in sent state
- Add tests for the routing on da_draft show pages
- Add tests for the invoice details in the controller
- Add tests for the authorised and notice  details in the controller
- Update methods in controller
- Test for saving new address on contact details pages
- Refactored controller to remove excess code
- Add tests for saving new contact details
- Refactor controller and remove redundant methods
- Add tests for update pension funds
- …

FM-1266- improving test coverage for the procurements_controller

---

app/controllers/auth_controller.rb
app/services/cognito/update_user.rb

Also update user should look for user.email if cognito_uuid is not present (that's in case the user is created from Dfe, but also has a Cognito account)

Finding user for auth rather than initialising by email

---

app/views/facilities_management/procurements/_choose_contract_value.html.erb
config/locales/views/facilities_management.en.yml

warning text wasn't shown except in one case, added additional description text above continuation buttons.

updates copy changes to reflect sketch

---

spec/features/supply_teachers/fta_to_perm_calculator.features_spec.rb

There were a couple of tests that were failing because they were expecting the wrong dates, eg:
Today's date: 31st July 2020
Today's date minus 5 months: 29th February 2020 (according to Ruby, other languages might put it as the 1st March 2020)
Today's date plus 1 month: 31st August 2020
Today's date minus 5 months plus 6 months: 29th August 2020
The specs have now been fixed so that they are using dates relative to the start of the contract rather than relative to today's date. There have been no functional code changes.

Ensure FTP calculator tests are expecting the correct dates

---

app/services/management_consultancy/supplier_spreadsheet_creator.rb

The issue lay with the regex to identify if the spreadsheet was dealing
with a service or a subservice, eg MCF2.3.1 is a service but MCF2.3.1.1
is a subservice. Unfortunately the regex ending for checking ended with a d
rather than a d+ so it was only checking for single digits. The check
can now check for subservices ending with double digits as well

ensure that services ending with double digit codes can be found

---

app/services/management_consultancy/supplier_spreadsheet_creator.rb

The issue lay with the regex to identify if the spreadsheet was dealing
with a service or a subservice, eg MCF2.3.1 is a service but MCF2.3.1.1
is a subservice. Unfortunately the regex ending for checking ended with a d
rather than a d+ so it was only checking for single digits. The check
can now check for subservices ending with double digits as well

ensure that services ending with double digit codes can be found [Production PR]

---

app/controllers/facilities_management/procurement_buildings_controller.rb
app/helpers/facilities_management/procurement_buildings_helper.rb
app/models/facilities_management/procurement.rb
app/models/facilities_management/procurement_building.rb
app/models/facilities_management/procurement_building_service.rb
app/services/facilities_management/services_and_questions.rb
app/views/facilities_management/procurement_buildings/show.html.erb
app/views/facilities_management/procurements/summary/_service_requirements.html.erb
config/locales/views/facilities_management.en.yml
spec/controllers/facilities_management/procurement_buildings_controller_spec.rb
spec/helpers/facilities_management/procurement_buildings_helper_spec.rb
spec/models/facilities_management/procurement_building_service_spec.rb
spec/models/facilities_management/procurement_building_spec.rb
spec/models/facilities_management/procurement_spec.rb

> - Initial layout for the service standard questions
> - Add the service volumes table
> - Sort the services by there workpackage code
> - Complete copy of the page
> - Move the text to a translation file
> - Add tests for the procurement controller
> - Add tests for procurement_buildings_helper
> - Update tests for new method
> - Add tests for the required_volume_contexts
> - Add tests for the completeness of the procurement_building
> - Refactor tests for complete method
> - Update summary page so can link to procurement_buildings

FMFR-177 -  progress summary of procurement's Service 

---

app/models/facilities_management/procurement_building.rb
app/views/facilities_management/procurements/summary/_service_requirements.html.erb

I realised from my last PR just after I merged it that we were showing buildings that didn't require service questions in the summery. This commit changes it so only buildings that need a service requirement are shown in the list.

Only show buildings that require questions in summary

---

app/controllers/facilities_management/procurements/spreadsheet_imports_controller.rb
app/helpers/facilities_management/procurements/spreadsheet_imports_helper.rb
app/models/facilities_management/procurement_building.rb
app/models/facilities_management/spreadsheet_import.rb
app/services/facilities_management/spreadsheet_importer.rb
app/views/facilities_management/procurements/spreadsheet_imports/_failed.html.erb
app/views/facilities_management/procurements/spreadsheet_imports/error_partials/_building_errors.html.erb
app/views/facilities_management/procurements/spreadsheet_imports/error_partials/_lift_errors.html.erb
app/views/facilities_management/procurements/spreadsheet_imports/error_partials/_other_errors.html.erb
app/views/facilities_management/procurements/spreadsheet_imports/error_partials/_service_hour_errors.html.erb
app/views/facilities_management/procurements/spreadsheet_imports/error_partials/_service_matrix_errors.html.erb
app/views/facilities_management/procurements/spreadsheet_imports/error_partials/_service_volume_errors.html.erb
app/workers/facilities_management/upload_spreadsheet_worker.rb
config/locales/views/facilities_management.en.yml
config/routes.rb
db/migrate/20200914124411_add_errors_on_spreadsheet_import.rb
db/schema.rb
spec/models/facilities_management/building_spec.rb
spec/models/facilities_management/procurement_building_spec.rb
spec/models/facilities_management/spreadsheet_import_spec.rb
spec/services/facilities_management/spreadsheet_importer_spec.rb

> - Think about how to collect errors
> - Update methods which collect errors
> - Add new column for import errors
> - Add methods to process the building errors
> - Add methods to process the procurement_building errors
> - Add methods to process the volume errors
> - Add methods to process the lift errors
> - Add methods to process the service hour errors
> - Add the page copy and put in translation file
> - Add the initial layout for the error tables
> - Add partials and layout ready for errors
> - Change from using an array to a hash
> - Add the error table for buildings
> - Add error constructions for the service matrix
> - Add error constructions for the first service volume
> - Add error constructions for the service hours
> - Move all text to translation file
> - Update tests for …

FMFR-201 - Spreadsheet data import - failed

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/controllers/base/sessions_controller.rb
app/views/layouts/application.html.erb
app/views/shared/sessions/_new.html.erb
config/initializers/ext.rb
config/locales/en.yml
config/routes.rb
lib/ext/ruby/auto_session_timeout_helper.rb
spec/rails_helper.rb
spec/views/layouts/application.html.erb_spec.rb

> - Add gem to check for session timeout
> - Refreshes page of user has timed out
> - Add copy for the page when session expires
> - Make it redirect to correct sign in url
> - Adjust the code to work better
> - Small fix for tests
For the issue of auto logging out, googling lead me to the 'auto-session-timeout' gem which does almost everything we need. The only issue was for when it times out we want it to return the user to the correct log in and tell them that the session has expired and when they log in again they should be redirected to where they were. To do this I added a monkey patch which sends the current url as param to the timeout request. The controller can then extract the relevant information it needs from the request to redirect the user to the correct page.

FMFR-399 - automatically log out user when session expires

---

app/models/facilities_management/procurement.rb
app/services/facilities_management/assessed_value_calculator.rb

The contract value page was timing out because the method for checking which services were unpriced was checking every procurement building service. For 1000 buildings with all services selected, this meant checking 112 000 services, just to get 33 service names. By plucking out the codes, service standards and names first, and then condensing them down to the unique ones, we get down to 112 services to check. This method then creates new ProcurementBuildingService objects in memory so we can use the methods on them to check which are unpriced. The objects do not get saved, so they don't need to be valid.

FMFR-437 Reduce time taken to check for unpriced services for procurement

---

pipeline_pre_build_tests.sh

- Add key in script so Nodejs can install
One of the dependancies used in the instillation for nodejs had an update on Friday 19th March which caused the issue. I added this line to the script as it added the missing key which was stopping the instillation. I've tested this in sandbox and it deploys successfully.

FMFR-726 - Fix issue with failing deployments

---

app/helpers/application_helper.rb
config/application.rb
spec/views/layouts/application.html.erb_spec.rb

- Show the survey link
The following environment variable needs to be created:
`/Environment/ccs/cmp/FM_SURVEY_LINK=https://crowncommercial.qualtrics.com/jfe/form/SV_50aDjt8zNRa47Cm`

FMFR-872 - Update the survey links

---

db/migrate/20210715113720_drop_facilities_management_regions.rb

This fixes an issue with deployments. Some tables in the production environments have the table `:facilities_management_regions`. This table is not present in the dev environment so we need to add an extra migration which will delete the table if it is present.

FMFR-990 - Fix issue with migrations

---

app/controllers/base/registrations_controller.rb
app/controllers/base/sessions_controller.rb
app/controllers/base/users_controller.rb
app/controllers/crown_marketplace/sessions_controller.rb
app/controllers/crown_marketplace/users_controller.rb
app/controllers/facilities_management/rm3830/admin/sessions_controller.rb
app/controllers/facilities_management/rm3830/admin/users_controller.rb
app/controllers/facilities_management/rm3830/registrations_controller.rb
app/controllers/facilities_management/rm3830/sessions_controller.rb
app/controllers/facilities_management/rm3830/supplier/sessions_controller.rb
app/controllers/facilities_management/rm3830/supplier/users_controller.rb
app/controllers/facilities_management/rm3830/users_controller.rb
app/views/home/cookie_policy.html.erb
app/views/shared/users/_confirm_new.html.erb
config/locales/en.yml

- Move shared logic into shared controller
- Hide email param from URL by putting it in the cookies
- Move shared logic into shared controller (again)
From an ITHC, we had already changed the email in one place to be stored in the browser cookies.
I have extended this to the email that is still shown too.
I will do tests in sandbox first before merging this branch.

FMFR-1129 - Remove email from URL

---

app/assets/stylesheets/ccs/facilities-management/_buyer-account.scss
app/helpers/facilities_management/admin/framework_helper.rb
app/helpers/layout_helper.rb
app/views/facilities_management/rm3830/admin/home/index.html.erb
app/views/facilities_management/rm3830/buyer_account/index.html.erb
app/views/facilities_management/rm6232/buyer_account/index.html.erb
config/locales/views/facilities_management.rm3830.en.yml
config/locales/views/facilities_management.rm6232.en.yml

Ticket: [FMFR-1000](https://crowncommercialservice.atlassian.net/browse/FMFR-1000)
Because of the work done in https://github.com/Crown-Commercial-Service/crown-marketplace/pull/3026, the buyer details and the buildings section form RM6232 are already working. The changes in this PR fix some of the CSS so that the panels remain consistant.
Before:
After:

FMFR-1000 - Update the buyer account page

---

app/models/facilities_management/rm6232/service.rb
app/models/facilities_management/rm6232/supplier.rb
app/services/facilities_management/rm6232/suppliers_selector.rb
spec/factories/facilities_management/rm6232/supplier.rb
spec/factories/facilities_management/rm6232/supplier/lot_data.rb
spec/models/facilities_management/rm6232/service_spec.rb
spec/models/facilities_management/rm6232/supplier_spec.rb
spec/services/facilities_management/rm6232/suppliers_selector_spec.rb

Ticket: [FMFR-1159](https://crowncommercialservice.atlassian.net/browse/FMFR-1159)
As the user testing will mainly deal with the frontend, I thought it would be worth developing the service to select the services based on the potential user input.
As part of this I:
- added methods to the service model to determine the lot number
- added a method to the supplier model to search for the suppliers who meet the requirements
- added the `SuppliersSelector` which deals with the logic of getting the lot number and suppliers

FMFR-1159 - Add logic for determining the lot and selecting the suppliers

---

app/controllers/facilities_management/rm6232/admin/home_controller.rb
app/controllers/facilities_management/rm6232/admin/passwords_controller.rb
app/controllers/facilities_management/rm6232/admin/sessions_controller.rb
app/controllers/facilities_management/rm6232/admin/users_controller.rb
app/views/facilities_management/rm6232/admin/home/index.html.erb
app/views/facilities_management/rm6232/admin/passwords/edit.html.erb
app/views/facilities_management/rm6232/admin/passwords/forgot_password_confirmation.html.erb
app/views/facilities_management/rm6232/admin/passwords/new.html.erb
app/views/facilities_management/rm6232/admin/passwords/password_reset_success.html.erb
app/views/facilities_management/rm6232/admin/sessions/new.html.erb
app/views/facilities_management/rm6232/admin/users/_new_password_required.html.erb
app/views/facilities_management/rm6232/admin/users/_sms_mfa.html.erb
app/views/facilities_management/rm6232/admin/users/challenge_new.html.erb
app/views/facilities_management/rm6232/admin/users/confirm_new.html.erb
config/locales/views/facilities_management.rm6232.en.yml
config/routes.rb
spec/controllers/facilities_management/rm6232/admin/home_controller_spec.rb
spec/controllers/facilities_management/rm6232/admin/passwords_controller_spec.rb
spec/controllers/facilities_management/rm6232/admin/sessions_controller_spec.rb
spec/controllers/facilities_management/rm6232/admin/users_controller_spec.rb

Ticket: [FMFR-1005](https://crowncommercialservice.atlassian.net/browse/FMFR-1005)
Add the base admin pages for the new RM6232 framework.
This includes:
- Sign in and sign up pages
- Cookie setting, Cookie policy and Accessibility Statement page
- The home page for the admin
In addition, I added the controller tests to make sure everything is working properly

FMFR-1005 - Add the basic pages for the admin section

---

app/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller.rb
app/models/facilities_management/rm6232/supplier/lot_data.rb
app/views/facilities_management/rm6232/admin/supplier_lot_data/_region_codes.html.erb
app/views/facilities_management/rm6232/admin/supplier_lot_data/edit.html.erb
app/views/facilities_management/rm6232/admin/supplier_lot_data/show.html.erb
config/locales/views/facilities_management.rm6232.en.yml
config/routes.rb
features/accessibility/facilities_management/rm6232/admin/view_lot_data_accessibility.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/region_codes.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/validations/region_codes_validations.feature
features/step_definitions/facilities_management/common_steps.rb
features/step_definitions/facilities_management/rm3830/quick_view_results_steps.rb
features/step_definitions/facilities_management/rm6232/admin_steps.rb
features/support/pages/rm6232/admin.rb
spec/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller_spec.rb
spec/factories/facilities_management/rm6232/supplier/lot_data.rb
spec/models/facilities_management/rm6232/supplier/lot_data_spec.rb

Ticket: [FMFR-1012](https://crowncommercialservice.atlassian.net/browse/FMFR-1012)
Add the ability to edit the suppliers regions in the admin tool
To do this I:
- Add the routes for editing and updating lot data
- Created a base edit page and then the region codes page
- add validation to the lot data model
- Add controller and model specs
- Add feature and accessibility tests

FMFR-1012 - Add the ability to edit the suppliers regions in the admin tool

---

app/assets/stylesheets/ccs/facilities-management/_all.scss
app/assets/stylesheets/ccs/facilities-management/_supplier_lot_data.scss
app/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller.rb
app/models/facilities_management/rm6232/service.rb
app/views/facilities_management/rm6232/admin/supplier_lot_data/_service_codes.html.erb
app/views/facilities_management/rm6232/admin/supplier_lot_data/edit.html.erb
config/locales/views/facilities_management.rm6232.en.yml
features/accessibility/facilities_management/rm6232/admin/view_lot_data_accessibility.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/region_codes.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/service_codes.feature
features/step_definitions/facilities_management/rm6232/admin_steps.rb
spec/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller_spec.rb

Ticket: [FMFR-1011](https://crowncommercialservice.atlassian.net/browse/FMFR-1011)
Add the ability to edit the suppliers services in the admin tool
To do this I:
- Add some config for the services to the controller
- Add the service codes page
- Add controller specs
- Add feature and accessibility tests

FMFR-1011 - Add the ability to edit the suppliers services in the admin tool

---

app/controllers/facilities_management/admin/supplier_details_controller.rb
app/models/facilities_management/rm3830/admin/suppliers_admin.rb
app/models/facilities_management/rm6232/admin/suppliers_admin.rb
app/models/facilities_management/rm6232/supplier.rb
app/views/facilities_management/admin/supplier_details/_supplier_status.html.erb
app/views/facilities_management/admin/supplier_details/edit.html.erb
app/views/facilities_management/admin/supplier_details/show.html.erb
config/locales/views/facilities_management.en.yml
config/locales/views/facilities_management.rm6232.en.yml
features/accessibility/facilities_management/rm6232/admin/supplier_details_accessibility.feature
features/facilities_management/rm3830/admin/supplier_data/supplier_details/supplier_details.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_details/supplier_details.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_details/supplier_status.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_details/validations/supplier_status_validations.feature
features/step_definitions/facilities_management/rm6232/admin_steps.rb
features/support/pages/admin.rb
features/support/pages/rm6232/admin.rb
spec/controllers/facilities_management/admin/supplier_details_controller_rm6232_spec.rb
spec/models/facilities_management/rm3830/admin/suppliers_admin_spec.rb
spec/models/facilities_management/rm6232/admin/suppliers_admin_spec.rb
spec/models/facilities_management/rm6232/supplier_spec.rb
spec/services/facilities_management/rm6232/suppliers_selector_spec.rb

Ticket: [FMFR-1008](https://crowncommercialservice.atlassian.net/browse/FMFR-1008)
The supplier status can be changed between active and inactive.
If the status is inactive then the supplier will not appear in search results.
To do this I:
- Added the Supplier status sections to the show and edit pages
- Added specs, feature and accessibility tests for changing the status
- Added the active condition to the `select_suppliers` method in the suppliers model
- Added tests to make sure the supplier does not appear if it is inactive

FMFR-1008 - Add the ability to change the supplier status

---

config/environments/production.rb

Ticket: [FMFR-1126](https://crowncommercialservice.atlassian.net/browse/FMFR-1126)
See [actiondispatch-hostauthorization](https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization) for details.
This should prevents against DNS rebinding and other `Host` header attacks.
The following environment variables need to be set:
Environment | `/Environment/global/ENVIRONMENT_HOST` value
-- | --
cmpdev | `.cmp.cmpdev.crowncommercial.gov.uk`
sandbox | `.cmp.cmp-sandbox.crowncommercial.gov.uk`
preview | `.marketplace.preview.crowncommercial.gov.uk`
production | `.marketplace.service.crowncommercial.gov.uk`

FMFR-1126 - Add config to limit the name of hosts in production

---

app/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller.rb
app/helpers/application_helper.rb
app/models/facilities_management/rm6232/journey/choose_services.rb
app/models/facilities_management/rm6232/journey/start_a_procurement.rb
app/models/facilities_management/rm6232/work_package.rb
app/models/generic_journey.rb
app/views/facilities_management/rm6232/journey/choose_services.html.erb
app/views/facilities_management/rm6232/journey/start_a_procurement.html.erb
config/locales/views/facilities_management.rm6232.en.yml
data/facilities_management/rm6232/services.csv
spec/models/facilities_management/rm6232/journey/choose_services_spec.rb
spec/models/facilities_management/rm6232/journey/start_a_procurement_spec.rb
spec/models/facilities_management/rm6232/work_package_spec.rb

Part of [FMFR-1003](https://crowncommercialservice.atlassian.net/browse/FMFR-1003)
This is the choose services section of quick view.
I think the only additional point of note is with regards to CAFM. This has a bit more of an impact later on but for now we have just added a third generic CAFM service that we allow the user to select. More information can be found in [Why we only show one CAFM service to suppliers](https://crowncommercialservice.atlassian.net/l/c/XW2DSi72)

FMFR-1003 - Quick view - Choose Services

---

app/assets/stylesheets/ccs/facilities-management/_all.scss
app/assets/stylesheets/ccs/facilities-management/_summary-box.scss
app/controllers/facilities_management/rm3830/procurements/contract_details_controller.rb
app/controllers/facilities_management/rm3830/procurements/contracts/closed_controller.rb
app/controllers/facilities_management/rm3830/procurements/contracts/sent_controller.rb
app/controllers/facilities_management/rm3830/procurements/copy_procurement_controller.rb
app/controllers/facilities_management/rm3830/procurements_controller.rb
app/controllers/facilities_management/rm6232/procurements_controller.rb
app/helpers/facilities_management/rm6232/procurements_helper.rb
app/models/facilities_management/rm3830/procurement.rb
app/models/facilities_management/rm6232/journey/annual_contract_value.rb
app/models/facilities_management/rm6232/journey/procurement.rb
app/models/facilities_management/rm6232/procurement.rb
app/models/user.rb
app/views/facilities_management/rm6232/procurements/new.html.erb
config/locales/views/facilities_management.rm6232.en.yml
config/routes.rb
db/migrate/20220517142407_create_rm6232_procurement.rb
db/schema.rb
spec/controllers/facilities_management/rm6232/procurements_controller_spec.rb
spec/factories/facilities_management/rm6232/procurement.rb
spec/helpers/facilities_management/rm6232/procurements_helper_spec.rb
spec/models/facilities_management/rm6232/journey/annual_contract_value_spec.rb
spec/models/facilities_management/rm6232/journey/procurement_spec.rb
spec/models/facilities_management/rm6232/procurement_spec.rb

Part of [FMFR-1003](https://crowncommercialservice.atlassian.net/browse/FMFR-1003)
This adds the results page to the journey. On this page a user can see their results (sub lot and the suppliers who can provide the services) and go back and change them.
The main thing of note is that we have additional logic to determine what version of CAFM should be selected. There is more information on this in [Why we only show one CAFM service to suppliers](https://crowncommercialservice.atlassian.net/l/c/XW2DSi72)

FMFR-1003 - Quick view - Results

---

app/controllers/facilities_management/rm3830/admin/uploads_controller.rb
app/controllers/facilities_management/rm3830/procurements_controller.rb
app/controllers/facilities_management/rm6232/procurements_controller.rb
app/services/facilities_management/rm3830/supplier_shortlist_spreadsheet_creator.rb
app/services/facilities_management/rm6232/supplier_shortlist_spreadsheet_creator.rb
app/services/facilities_management/supplier_shortlist_spreadsheet.rb
app/views/facilities_management/rm6232/procurements/show_partial/_what_happens_next.html.erb
config/locales/en.yml
config/routes.rb
features/facilities_management/rm6232/procurements/what_happens_next.feature
features/step_definitions/facilities_management/common_steps.rb
features/step_definitions/facilities_management/rm6232/procurement_steps.rb
spec/controllers/facilities_management/rm6232/procurements_controller_spec.rb
spec/factories/facilities_management/rm6232/procurement.rb
spec/models/facilities_management/rm6232/procurement_spec.rb
spec/services/facilities_management/rm3830/supplier_shortlist_spreadsheet_creator_spec.rb
spec/services/facilities_management/rm6232/supplier_shortlist_spreadsheet_creator_spec.rb

Ticket: [FMFR-1168](https://crowncommercialservice.atlassian.net/browse/FMFR-1168)
Add the functionality to download the ‘Selected suppliers’ on the ‘What happens next page’. As this shares a lot of the functionality with the ‘Quick view spreadsheet’ so I refactored both spreadsheet creators to share the code. I also added tests for the spreadsheet download.

FMFR-1168 - Create the functionality to download the 'Selected suppliers' spreadsheet

---

app/controllers/concerns/facilities_management/procurement_details_concern.rb
app/controllers/facilities_management/rm6232/details_controller.rb
app/helpers/facilities_management/rm6232/procurements_helper.rb
app/views/facilities_management/rm6232/procurements/show.html.erb
config/routes.rb
features/facilities_management/rm3830/procurements/direct_award/direct_award_procurement.feature
spec/controllers/facilities_management/rm6232/details_controller_spec.rb
spec/helpers/facilities_management/rm6232/procurements_helper_spec.rb

Part of ticket: [FMFR-1170](https://crowncommercialservice.atlassian.net/browse/FMFR-1170)
Because this section is going to be a lot of work and require a lot of changes, I’ve decided to split the PRs up into more manageable sections.
For the contract details I have added a new controller/concern in order to deal with editing and showing the summary of the sections. This allows us to move a lot of the clutter out of the procurements controller and will allow code to be more easily shared.
I also added the specs for the work I have done so far which will need to be updated when further development is done

FMFR-1170 - Create the controller for the Contract Details section

---

app/controllers/concerns/facilities_management/procurement_details_concern.rb
app/controllers/facilities_management/rm6232/details_controller.rb
app/helpers/facilities_management/rm6232/details_helper.rb
app/helpers/facilities_management/rm6232/procurements_helper.rb
app/helpers/gov_uk_helper.rb
app/helpers/gov_uk_helper/text_input.rb
app/helpers/layout_helper.rb
app/models/concerns/facilities_management/rm6232/procurement_validator.rb
app/views/facilities_management/buildings/_area.html.erb
app/views/facilities_management/rm3830/supplier/contracts/edit.html.erb
app/views/facilities_management/rm6232/procurements/show.html.erb
app/views/facilities_management/shared/details/edit.html.erb
app/views/facilities_management/shared/details/edit_partials/_annual_contract_value.html.erb
app/views/facilities_management/shared/details/edit_partials/_contract_name.html.erb
config/locales/views/facilities_management.en.yml
config/locales/views/facilities_management.rm6232.en.yml
features/step_definitions/facilities_management/rm6232/procurement_steps.rb
spec/controllers/facilities_management/rm6232/details_controller_spec.rb
spec/factories/facilities_management/rm6232/procurement.rb
spec/models/facilities_management/rm6232/procurement_validations_spec.rb

Part of ticket: [FMFR-1170](https://crowncommercialservice.atlassian.net/browse/FMFR-1170)
This commit contains the first working edit pages for the contract details:
- The contract name
- Annual contract value
To prevent the commits getting too large, I am splitting them up for each page that is added.
I will add the feature tests for this work in a later PR dedicated to adding them.

FMFR-1170 - Add edit pages for 'contract name' and 'annual contract value'

---

app/controllers/concerns/facilities_management/procurement_details_concern.rb
app/controllers/facilities_management/rm6232/details_controller.rb
app/models/concerns/facilities_management/rm6232/procurement_validator.rb
app/models/facilities_management/rm6232/procurement.rb
app/views/facilities_management/shared/details/edit_partials/_tupe.html.erb
config/locales/views/facilities_management.en.yml
config/locales/views/facilities_management.rm6232.en.yml
db/migrate/20220526114902_add_tupe_to_rm6232_procurement.rb
db/schema.rb
spec/controllers/facilities_management/rm6232/details_controller_spec.rb
spec/factories/facilities_management/rm6232/procurement.rb
spec/models/facilities_management/rm6232/procurement_spec.rb
spec/models/facilities_management/rm6232/procurement_validations_spec.rb

Part of ticket: [FMFR-1170](https://crowncommercialservice.atlassian.net/browse/FMFR-1170)
This commit contains the working edit pages in contract details for:
- tupe
To prevent the commits getting too large, I am splitting them up for each page that is added.
I will add the feature tests for this work in a later PR dedicated to adding them.

FMFR-1170 - Add edit page for 'tupe'

---

app/controllers/concerns/facilities_management/procurement_details_concern.rb
app/controllers/facilities_management/rm6232/buildings_controller.rb
app/controllers/facilities_management/rm6232/details_controller.rb
app/controllers/facilities_management/rm6232/edit_buildings_controller.rb
app/helpers/facilities_management/details_helper.rb
app/views/facilities_management/shared/details/edit_partials/_buildings.html.erb
app/views/facilities_management/shared/details/kaminari/_first_page.html.erb
app/views/facilities_management/shared/details/kaminari/_gap.html.erb
app/views/facilities_management/shared/details/kaminari/_last_page.html.erb
app/views/facilities_management/shared/details/kaminari/_next_page.html.erb
app/views/facilities_management/shared/details/kaminari/_page.html.erb
app/views/facilities_management/shared/details/kaminari/_paginator.html.erb
app/views/facilities_management/shared/details/kaminari/_prev_page.html.erb
config/locales/views/facilities_management.en.yml
config/routes.rb
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/add_a_building/buildings.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/add_a_building/review_completed_building.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/validations/add_a_building/add_a_building_validations.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/validations/add_a_building/add_address_manually_validations.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/validations/add_a_building/building_type_validation.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/validations/add_a_building/internal_and_external_area_validations.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/validations/add_a_building/security_type_validations.feature
spec/controllers/facilities_management/rm3830/edit_buildings_controller_spec.rb
spec/controllers/facilities_management/rm6232/buildings_controller_spec.rb
spec/controllers/facilities_management/rm6232/details_controller_spec.rb
spec/controllers/facilities_management/rm6232/edit_buildings_controller_spec.rb
spec/helpers/facilities_management/rm6232/details_helper_spec.rb

Ticket: [FMFR-1172](https://crowncommercialservice.atlassian.net/browse/FMFR-1172)
As this is a rather complex section of the application, I’ve split it up into parts so that the PRs/commits do not get too large.
This commit concerns the adding of the ‘edit buildings’ section within the procurement for the new FM framework. I’ve done the minimum to get the ‘buildings’ page working in the details section and then added the ‘edit buildings’ section.
Included in this commit are tests for the ‘edit buildings’ section (both specs and feature tests) to make sure it works as expected.

FMFR-1172 - Edit buildings in the procurement

---

app/controllers/concerns/facilities_management/procurement_details_concern.rb
app/models/facilities_management/rm6232/procurement_building.rb
app/views/facilities_management/shared/details/show_partials/_buildings.html.erb
config/locales/views/facilities_management.en.yml
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/buildings.feature
features/support/pages/rm6232/entering_requirements.rb
spec/controllers/facilities_management/rm6232/details_controller_spec.rb
spec/helpers/facilities_management/rm6232/details_helper_spec.rb

Ticket: [FMFR-1172](https://crowncommercialservice.atlassian.net/browse/FMFR-1172)
Added the summary page for buildings so that we can see the selected buildings by the user.
I was also able to update the feature tests for both the show and edit pages for ‘buildings’ to show how they worked.

FMFR-1172 - Add summary page for buildings

---

app/controllers/concerns/facilities_management/procurement_details_concern.rb
app/controllers/facilities_management/rm6232/details_controller.rb
app/models/concerns/facilities_management/procurement_concern.rb
app/models/facilities_management/rm3830/procurement.rb
app/models/facilities_management/rm6232/procurement.rb
app/models/facilities_management/rm6232/procurement_building.rb
app/views/facilities_management/shared/details/show_partials/_buildings.html.erb
app/views/facilities_management/shared/details/show_partials/_buildings_and_services.html.erb
config/locales/views/facilities_management.en.yml
spec/controllers/facilities_management/rm6232/details_controller_spec.rb
spec/helpers/facilities_management/rm6232/details_helper_spec.rb
spec/models/facilities_management/rm6232/procurement_spec.rb

Ticket: [FMFR-1173](https://crowncommercialservice.atlassian.net/browse/FMFR-1173)
This is part of the work to add the ‘Assign services to buildings’ section of the application. Like with other parts, I’ve split it up so that the changes do not get too large.
This specific commit adds the summary page for the ‘Assign services to buildings section’ and some specs for that section.
I’ve not added any feature tests yet and will do that when all the parts of this section are complete.

FMFR-1173 - Assign services to buildings summary page

---

app/controllers/facilities_management/rm6232/procurement_buildings_controller.rb
app/helpers/facilities_management/rm6232/procurement_buildings_helper.rb
app/models/facilities_management/rm6232/procurement_building.rb
app/views/facilities_management/rm6232/procurement_buildings/edit.html.erb
app/views/facilities_management/shared/details/show_partials/_buildings_and_services.html.erb
config/locales/views/facilities_management.rm6232.en.yml
config/routes.rb
features/accessibility/facilities_management/rm6232/procurements/entering_requirements/services_and_building/assigning_services_to_buildings_accessibility.feature
features/accessibility/facilities_management/rm6232/procurements/entering_requirements/services_and_building/buildings_accessibility.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/assigning_services_to_buildings.feature
features/facilities_management/rm6232/procurements/entering_requirements/services_and_buildings/validations/assigning_services_to_buildings_validations.feature
features/step_definitions/facilities_management/buyer_detail_steps.rb
features/step_definitions/facilities_management/entering_requirements_steps.rb
features/step_definitions/facilities_management/procurement_steps.rb
features/step_definitions/facilities_management/quick_view_steps.rb
features/step_definitions/facilities_management/rm3830/contract_detail_steps.rb
features/step_definitions/facilities_management/rm3830/entering_requirements_steps.rb
features/step_definitions/facilities_management/rm3830/procurement_steps.rb
features/step_definitions/facilities_management/rm3830/quick_view_results_steps.rb
features/support/pages/buyer_detail.rb
features/support/pages/rm6232/entering_requirements.rb
spec/controllers/facilities_management/rm6232/details_controller_spec.rb
spec/controllers/facilities_management/rm6232/procurement_buildings_controller_spec.rb
spec/models/facilities_management/rm6232/journey/choose_services_spec.rb
spec/models/facilities_management/rm6232/procurement_building_spec.rb
spec/models/facilities_management/rm6232/procurement_spec.rb
spec/models/facilities_management/rm6232/procurement_validations_spec.rb

Add the ability to add services to a building in a procurement. This includes the validation of the service selection which should match the validation in the previous framework.
I also added the method to check the service selection so that part is complete. In the next PR I will add the code to make sure all the statuses are complete before continuing from the further service requirements page.
As well as adding some more specs, I also added some feature tests and some accessibility tests for the ‘Assigning services to buildings’ section. I also moved some of the step definitions about to make sure any that are shared between frameworks are in a neutral file.

FMFR-1173 - Add ability to add services to a building in a procurement

---

config/locales/views/facilities_management.rm6232.en.yml
features/.cut_pages/accessibility/facilities_management/rm6232/procurements/entering_requirements/contract_details/annual_contract_value_accessibility.feature
features/.cut_pages/facilities_management/rm6232/procurements/entering_requirements/contract_details/annual_contract_value.feature
features/.cut_pages/facilities_management/rm6232/procurements/entering_requirements/contract_details/validations/annual_contract_value_validations.feature
features/.cut_pages/facilities_management/rm6232/procurements/results/results_are_correct.feature
features/.cut_pages/facilities_management/rm6232/quick_view/results.feature
features/accessibility/facilities_management/rm6232/quick_view/quick_view_accessibility.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_details/supplier_name.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_details/supplier_status.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/quick_view/region_selection_adding.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/quick_view/region_selection_removing.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/quick_view/service_selection_adding.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/quick_view/service_selection_removing.feature
features/facilities_management/rm6232/quick_view/lot_selection.feature
features/facilities_management/rm6232/quick_view/results.feature
features/facilities_management/rm6232/quick_view/select_regions.feature
features/facilities_management/rm6232/quick_view/validations/annual_contract_value_validations.feature
features/facilities_management/rm6232/quick_view/validations/results_validations.feature
features/step_definitions/facilities_management/rm6232/admin_steps.rb
features/step_definitions/facilities_management/rm6232/entering_requirements_steps.rb
features/step_definitions/facilities_management/rm6232/quick_view_steps.rb
features/support/pages/rm6232/quick_view.rb
spec/controllers/facilities_management/rm6232/procurement_details_controller_spec.rb
spec/controllers/facilities_management/rm6232/procurements_controller_spec.rb
spec/helpers/facilities_management/rm6232/procurements_helper_spec.rb
spec/models/facilities_management/rm6232/journey/annual_contract_value_spec.rb
spec/models/facilities_management/rm6232/procurement_spec.rb
spec/models/facilities_management/rm6232/procurement_validations_spec.rb

Ticket: [FMFR-1241](https://crowncommercialservice.atlassian.net/browse/FMFR-1241)
In this commit I have updated some of the copy on the ‘Annual contract value’ page, changing it to ‘Annual contract cost’ (hence the high number of changes).

FMFR-1241 - Update annual contract value pages

---

app/controllers/facilities_management/rm6232/buildings_controller.rb
app/controllers/facilities_management/rm6232/edit_buildings_controller.rb
app/models/facilities_management/journey.rb
app/models/facilities_management/rm6232/journey/start_a_search.rb
app/models/generic_journey.rb
app/views/facilities_management/rm6232/buyer_account/index.html.erb
app/views/facilities_management/rm6232/journey/start_a_search.html.erb
config/locales/views/facilities_management.rm6232.en.yml
features/.cut_pages/facilities_management/rm6232/procurements/results/results_are_correct.feature
features/.cut_pages/facilities_management/rm6232/quick_view/results.feature
features/accessibility/facilities_management/rm6232/quick_view/quick_view_accessibility.feature
features/facilities_management/rm6232/procurements/what_do_i_do_next.feature
features/facilities_management/rm6232/quick_view/lot_selection.feature
features/facilities_management/rm6232/quick_view/results.feature
features/facilities_management/rm6232/quick_view/select_regions.feature
features/facilities_management/rm6232/quick_view/select_services.feature
features/facilities_management/rm6232/quick_view/service_specification.feature
features/facilities_management/rm6232/quick_view/validations/annual_contract_value_validations.feature
features/facilities_management/rm6232/quick_view/validations/results_validations.feature
features/facilities_management/rm6232/quick_view/validations/select_regions_validations.feature
features/facilities_management/rm6232/quick_view/validations/select_services_validations.feature
spec/models/facilities_management/rm6232/journey/start_a_search_spec.rb

Ticket: [FMFR-1238](https://crowncommercialservice.atlassian.net/browse/FMFR-1238)
In this commit I have updated the ‘Start a procurement page’ and have changed it to the ‘Search for suppliers’ page.

FMFR-1238 - Update the start a procurement page

---

.github/workflows/rubyonrails.yml
features/facilities_management/home/framework_links.feature
features/facilities_management/rm3830/admin/assessed_value/assessed_value.feature

I’ve updated the GitHub actions so that when we do a release to preview/production we run the full feature test suite instead of just a smaller set of tests.
We run a smaller set of feature tests to save time on development, but before we do a release we should check that everything is working as these feature test cover nearly all of the application.

Run all feature tests on release

---

app/controllers/facilities_management/admin/uploads_controller.rb
app/controllers/facilities_management/rm3830/admin/uploads_controller.rb
app/controllers/facilities_management/rm6232/admin/uploads_controller.rb
app/models/facilities_management/rm3830/admin/upload.rb
app/models/facilities_management/rm6232/admin/upload.rb
app/models/user.rb
db/migrate/20220629111720_add_user_to_admin_uploads.rb
db/schema.rb

Ticket: [FMFR-1248](https://crowncommercialservice.atlassian.net/browse/FMFR-1248)
Update the admin upload models so that they can have a user attached to them. This is for auditing purposes.

FMFR-1248 - Add user to admin uploads

---

app/controllers/facilities_management/admin/supplier_details_controller.rb
app/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller.rb
app/models/facilities_management/rm6232/admin/supplier_data.rb
app/models/facilities_management/rm6232/admin/supplier_data/edit.rb
app/models/facilities_management/rm6232/admin/suppliers_admin.rb
app/models/facilities_management/rm6232/admin/upload.rb
app/models/facilities_management/rm6232/supplier/lot_data.rb
app/models/user.rb
app/services/facilities_management/rm6232/admin/files_importer.rb
app/services/facilities_management/rm6232/admin/files_importer/data_uploader.rb
db/migrate/20220629115809_add_rm6232_rate_card.rb
db/migrate/20220629123952_add_rm6232_supplier_data_edit.rb
db/schema.rb
spec/controllers/facilities_management/admin/supplier_details_controller_rm6232_spec.rb
spec/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller_spec.rb
spec/models/facilities_management/rm6232/admin/supplier_data/edit_spec.rb
spec/models/facilities_management/rm6232/admin/supplier_data_spec.rb
spec/models/facilities_management/rm6232/admin/suppliers_admin_spec.rb
spec/models/facilities_management/rm6232/supplier/lot_data_spec.rb
spec/services/facilities_management/rm6232/admin/files_importer_spec.rb

Ticket: [FMFR-1249](https://crowncommercialservice.atlassian.net/browse/FMFR-1249)
There is a requirement from the admin team that all changes that are made to the supplier data are logged. In this commit I have added the models which will store these changes along with who made them.
The first model is the `Admin::SupplierData`. This has a JSON of the full supplier data before it is imported into the database after a user uploads the data. We then have the `Admin::SupplierData::Edit` model which contains all the changes made since the most recent `Admin::SupplierData` was created.
As always I have added specs to make sure everything is working as expected. In a future commit I will add a section to view who made the changes.

FMFR-1249 - Add logging of the changes by the admin

---

app/controllers/facilities_management/rm6232/admin/change_logs_controller.rb
app/helpers/facilities_management/rm6232/admin/change_logs_helper.rb
app/models/facilities_management/rm6232/admin/supplier_data.rb
app/models/facilities_management/rm6232/admin/supplier_data/edit.rb
app/views/facilities_management/rm6232/admin/change_logs/_change_log_details.html.erb
app/views/facilities_management/rm6232/admin/change_logs/_details.html.erb
app/views/facilities_management/rm6232/admin/change_logs/_lot_data.html.erb
app/views/facilities_management/rm6232/admin/change_logs/_upload.html.erb
app/views/facilities_management/rm6232/admin/change_logs/index.html.erb
app/views/facilities_management/rm6232/admin/change_logs/show.html.erb
app/views/facilities_management/rm6232/admin/home/index.html.erb
app/views/facilities_management/rm6232/admin/uploads/show.html.erb
config/locales/views/facilities_management.rm6232.en.yml
config/routes.rb
features/facilities_management/rm6232/admin/change_logs/changes_to_details.feature
features/facilities_management/rm6232/admin/change_logs/changes_to_regions.feature
features/facilities_management/rm6232/admin/change_logs/changes_to_services.feature
features/facilities_management/rm6232/admin/change_logs/data_uploaded.feature
features/step_definitions/facilities_management/admin_steps.rb
features/step_definitions/facilities_management/rm3830/admin_steps.rb
features/step_definitions/facilities_management/rm6232/admin_steps.rb
features/support/pages.rb
features/support/pages/rm3830/admin.rb
features/support/pages/rm6232/admin.rb
spec/controllers/facilities_management/rm6232/admin/change_logs_controller_spec.rb
spec/factories/facilities_management/rm6232/admin/supplier_data/edit.rb
spec/factories/facilities_management/rm6232/admin/upload.rb
spec/helpers/facilities_management/rm6232/admin/change_logs_helper_spec.rb
spec/models/facilities_management/rm6232/admin/supplier_data/edit_spec.rb
spec/models/facilities_management/rm6232/admin/supplier_data_spec.rb

Ticket: [FMFR-1249](https://crowncommercialservice.atlassian.net/browse/FMFR-1249)
There is a requirement from the admin team that all changes that are made to the supplier data are logged. In this commit I have added views which will allow the admin users to view all the changes that have been made.
As always I have added specs to make sure everything is working as expected. In a future commit I will add a section to view who made the changes.

FMFR-1249 - Add views for the audit logs

---

app/controllers/facilities_management/rm6232/admin/change_logs_controller.rb
app/services/facilities_management/rm6232/admin/change_logs_csv_generator.rb
app/views/facilities_management/rm6232/admin/change_logs/index.html.erb
config/locales/views/facilities_management.rm6232.en.yml
spec/controllers/facilities_management/rm6232/admin/change_logs_controller_spec.rb
spec/services/facilities_management/rm6232/admin/change_logs_csv_generator_spec.rb

There is a requirement from the admin team that all changes that are made to the supplier data are logged. In this commit I have added the ability to download the complete change log in a CSV.
As always I have added specs to make sure everything is working as expected.

FMFR-1249 - Add ability to download full audit log

---

app/assets/javascripts/facilities-management/rm6232/admin/supplier-data-snapshot.js
app/controllers/facilities_management/rm6232/admin/supplier_data_snapshots_controller.rb
app/models/facilities_management/rm6232/admin/supplier_data.rb
app/models/facilities_management/rm6232/admin/supplier_data/snapshot.rb
app/services/facilities_management/rm6232/admin/supplier_data_snapshot_generator.rb
app/services/facilities_management/rm6232/admin/supplier_spreadsheet.rb
app/services/facilities_management/rm6232/admin/supplier_spreadsheet/details.rb
app/services/facilities_management/rm6232/admin/supplier_spreadsheet/regions.rb
app/services/facilities_management/rm6232/admin/supplier_spreadsheet/services.rb
app/views/facilities_management/rm6232/admin/change_logs/index.html.erb
app/views/facilities_management/rm6232/admin/supplier_data_snapshots/new.html.erb
config/locales/views/facilities_management.rm6232.en.yml
config/routes.rb
lib/tasks/facilities_management/rm6232/generate_supplier_details.rake
lib/tasks/facilities_management/rm6232/generate_supplier_lot_data.rake
spec/controllers/facilities_management/rm6232/admin/supplier_data_snapshots_controller_spec.rb
spec/models/facilities_management/rm6232/admin/supplier_data/snapshot_spec.rb
spec/models/facilities_management/rm6232/admin/supplier_data_spec.rb
spec/services/facilities_management/rm6232/admin/change_logs_csv_generator_spec.rb
spec/services/facilities_management/rm6232/admin/supplier_data_snapshot_generator_spec.rb

Ticket: [FMFR-1249](https://crowncommercialservice.atlassian.net/browse/FMFR-1249)
There is a requirement from the admin team that all changes that are made to the supplier data are logged.
In this commit I have added the ability to download the supplier data at any instant in time. This may be needed for auditing purposes if, for example, a supplier complained that they were not being included in any searches.
As always I have added specs to make sure everything is working as expected.

FMFR-1249 - Download snapshot of supplier data

---

app/helpers/application_helper.rb
app/helpers/gov_uk_helper/notification_banner.rb
app/views/crown_marketplace/allow_list/index.html.erb
app/views/facilities_management/rm3830/_new_framework_banner.html.erb
app/views/facilities_management/rm3830/buyer_account/index.html.erb
app/views/facilities_management/rm3830/home/index.html.erb
app/views/facilities_management/rm3830/sessions/new.html.erb
config/application.rb
config/locales/views/facilities_management.rm3830.en.yml
features/facilities_management/rm6232/quick_view/service_specification.feature
features/step_definitions/facilities_management/rm3830/procurement_steps.rb
spec/helpers/application_helper_spec.rb

Ticket: [FMFR-1253](https://crowncommercialservice.atlassian.net/browse/FMFR-1253)
Add banner for when the new framework goes live.
You can view the banner by adding `?show_new_framework_banner=true` to the URL.

FMFR-1253 - Add new framework banner

---

app/controllers/active_storage/blobs_controller.rb
app/controllers/facilities_management/admin/frameworks_controller.rb
app/controllers/facilities_management/admin/uploads_controller.rb
app/models/ability.rb
app/models/user.rb
config/routes.rb
spec/controllers/facilities_management/admin/frameworks_controller_spec.rb
spec/support/controller_macros.rb

Ticket: [FMR-1271](https://crowncommercialservice.atlassian.net/browse/FMFR-1271)
To make it easier to change the framework dates in production, i.e. without the need for a deployment, I have added the new role `ccs_developer` which gives limited access to change the framework dates.

FMFR-1271 - Allow special access to change framework dates

---

pipeline_pre_build_tests.sh

Update how we download PhantomJS for the tests that use it when deploying to the legacy applications.

Update how we download PhantomJS for the tests in AWS

---

app/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller.rb
app/models/facilities_management/rm6232/admin/supplier_data/edit.rb
app/models/facilities_management/rm6232/supplier.rb
app/models/facilities_management/rm6232/supplier/lot_data.rb
app/services/facilities_management/rm6232/admin/change_logs_csv_generator.rb
app/services/facilities_management/rm6232/admin/supplier_data_snapshot_generator.rb
app/views/facilities_management/rm6232/admin/change_logs/_lot_data.html.erb
app/views/facilities_management/rm6232/admin/supplier_lot_data/_lot_status.html.erb
app/views/facilities_management/rm6232/admin/supplier_lot_data/edit.html.erb
app/views/facilities_management/rm6232/admin/supplier_lot_data/show.html.erb
config/locales/views/facilities_management.rm6232.en.yml
db/migrate/20220815090054_add_status_to_supplier_lot_data.rb
db/schema.rb
features/facilities_management/rm6232/admin/change_logs/changes_to_lot_status.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/lot_status.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/quick_view/lot_status_selection.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/region_codes.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_lot_data/validations/lot_status_validations.feature
features/step_definitions/facilities_management/rm6232/admin_steps.rb
features/support/pages/rm6232/admin.rb
spec/controllers/facilities_management/rm6232/admin/supplier_lot_data_controller_spec.rb
spec/factories/facilities_management/rm6232/admin/supplier_data/edit.rb
spec/models/facilities_management/rm6232/admin/supplier_data/edit_spec.rb
spec/models/facilities_management/rm6232/supplier/lot_data_spec.rb
spec/models/facilities_management/rm6232/supplier_spec.rb
spec/services/facilities_management/rm6232/admin/change_logs_csv_generator_spec.rb
spec/services/facilities_management/rm6232/suppliers_selector_spec.rb

Ticket: [FMFR-1269](https://crowncommercialservice.atlassian.net/browse/FMFR-1269)
We have been asked by the category team to add the ability to suspend a supplier in certain lots. There is a de facto way of doing this already where they can upload the lot data without that supplier's data in that lot.
This change adds a toggle on all the lot data which allows the status to be changed. As part of this there are also updates to the logging functionality for when an admin user makes changes.
I have added specs and feature tests for these changes as well.

FMFR-1269 - Allow supplier to suspended on a lot by lot basis

---

spec/helpers/facilities_management/contract_dates_helper_spec.rb

Because the date we are adding adds the 18 months as 6 months plus one year, we need to do the same to prevent the following issue.
If the date is 30 August 2022, if we add 18 months we will get to 29th Feb 2024. However, if we add 6 months we will get the 28th Feb 2023 and then add a year we will get the 28th of Feb 2024.
By adding the date in this way for the result of this test, we can prevent this potential issue.

Split up date addition to account for months with shorter lengths

---

app/services/cognito/confirm_sign_up.rb
app/services/cognito/sign_in_user.rb
app/services/cognito/sign_up_user.rb
config/locales/en.yml
features/helpers/facilities_management/logging_in_helper.rb
spec/controllers/crown_marketplace/passwords_controller_spec.rb
spec/controllers/crown_marketplace/sessions_controller_spec.rb
spec/controllers/facilities_management/rm3830/admin/passwords_controller_spec.rb
spec/controllers/facilities_management/rm3830/admin/sessions_controller_spec.rb
spec/controllers/facilities_management/rm3830/passwords_controller_spec.rb
spec/controllers/facilities_management/rm3830/registrations_controller_spec.rb
spec/controllers/facilities_management/rm3830/sessions_controller_spec.rb
spec/controllers/facilities_management/rm3830/supplier/passwords_controller_spec.rb
spec/controllers/facilities_management/rm3830/supplier/sessions_controller_spec.rb
spec/controllers/facilities_management/rm3830/users_controller_spec.rb
spec/controllers/facilities_management/rm6232/admin/passwords_controller_spec.rb
spec/controllers/facilities_management/rm6232/admin/sessions_controller_spec.rb
spec/controllers/facilities_management/rm6232/passwords_controller_spec.rb
spec/controllers/facilities_management/rm6232/registrations_controller_spec.rb
spec/controllers/facilities_management/rm6232/sessions_controller_spec.rb
spec/controllers/facilities_management/rm6232/users_controller_spec.rb
spec/features/authentication.feature_spec.rb
spec/services/cognito/confirm_sign_up_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/cognito/sign_up_user_spec.rb

Ticket: [FMFR-1194](https://crowncommercialservice.atlassian.net/browse/FMFR-1194)
I have made updates to the code to prevent user enumeration which were raised in a recent IT Health Check. The changes I have made address the following issues:
- Make response times for sign in identical
- Allow users with accounts already to pass through sign up
- Make sure error message on the next page (confirm sign up)  does not inform of users existence
I have then updated the tests to make sure we are testing these changes and they don’t have any negative effects.

FMFR-1194 - Address username enumeration concerns

---

app/models/ability.rb

Ticket: [FMFR-1306](https://crowncommercialservice.atlassian.net/browse/FMFR-1306)
Update the ability config to better reflect the abilities different roles should have.

FMFR-1306 - Refactor ability so roles match better

---

app/models/ability.rb
app/models/user.rb
app/services/cognito/admin/roles.rb
app/services/cognito/admin/user.rb
app/services/cognito/admin/user_client_interface.rb
config/locales/en.yml
config/locales/views/crown_marketplace.en.yml
spec/services/cognito/admin/roles_spec.rb
spec/services/cognito/admin/user_spec.rb
spec/support/controller_macros.rb

Ticket: [FMFR-1314](https://crowncommercialservice.atlassian.net/browse/FMFR-1314)
We are adding the ability for the CSC team to manage users through the application rather than in cognito. This commit contains the code that, once the frontend has been developed, will allow them to do so.
I have created the `Cognito::Admin::User` model to handle the users we find in a more rails way. I have created the `Cognito::Admin::UserClientInterface` as an interface to handle the Cognito API, and keep some of the complexity out of the `Cognito::Admin::User` model. This interface allows us to:
- Create users
- Search users
- Find a single user
- Update the users attributes
In addition to these, I have created the  `Cognito::Admin::Roles` class which handles the logic for the roles that can be …

FMFR-1314 - Add backend for managing users

---

app/views/crown_marketplace/manage_users/edit_partials/_account_status.html.erb
app/views/crown_marketplace/manage_users/show.html.erb
config/locales/views/crown_marketplace.en.yml
features/crown_marketplace/manage_users/super_admin/edit_user.feature
features/crown_marketplace/manage_users/user_admin/edit_user.feature
features/crown_marketplace/manage_users/user_support/edit_user.feature
features/step_definitions/crown_marketplace/manage_users_steps.rb
features/support/pages/manage_users.rb
spec/controllers/crown_marketplace/manage_users_controller_spec.rb

https://crowncommercialservice.atlassian.net/jira/software/c/projects/FMFR/boards/71?modal=detail&selectedIssue=FMFR-1323

FMFR-1323-allow-update-of-the-account-status

---

app/services/cognito/admin/user.rb
features/crown_marketplace/manage_users/super_admin/edit_user.feature
features/crown_marketplace/manage_users/super_admin/validations/edit_user_validation.feature
features/crown_marketplace/manage_users/user_admin/edit_user.feature
features/crown_marketplace/manage_users/user_admin/validations/edit_user_validation.feature
features/crown_marketplace/manage_users/user_support/validations/edit_user_validation.feature
features/step_definitions/crown_marketplace/cognito_steps.rb
spec/services/cognito/admin/user_spec.rb

Link to issue: https://crowncommercialservice.atlassian.net/browse/FMFR-1343
Fixed bug where all users could not leave service access empty. 
Only should have been the case for buyers and service admins.

Fixed bug where all users could not leave service access empty. 

---

app/views/crown_marketplace/manage_users/_users_table.html.erb
app/views/crown_marketplace/manage_users/index.html.erb
features/crown_marketplace/manage_users/super_admin/edit_user.feature
features/crown_marketplace/manage_users/super_admin/resend_temporary_password.feature
features/crown_marketplace/manage_users/super_admin/validations/edit_user_validation.feature
features/crown_marketplace/manage_users/super_admin/view_user/assorted_details.feature
features/crown_marketplace/manage_users/super_admin/view_user/full_details.feature
features/crown_marketplace/manage_users/super_admin/view_user/mixed_roles.feature
features/crown_marketplace/manage_users/super_admin/view_user/something_went_wrong.feature
features/crown_marketplace/manage_users/user_admin/edit_user.feature
features/crown_marketplace/manage_users/user_admin/find_users.feature
features/crown_marketplace/manage_users/user_admin/find_users_javascript_enabled.feature
features/crown_marketplace/manage_users/user_admin/resend_temporary_password.feature
features/crown_marketplace/manage_users/user_admin/validations/edit_user_validation.feature
features/crown_marketplace/manage_users/user_admin/validations/find_users_javascript_enabled_validation.feature
features/crown_marketplace/manage_users/user_admin/validations/find_users_validation.feature
features/crown_marketplace/manage_users/user_admin/view_user/assorted_details.feature
features/crown_marketplace/manage_users/user_admin/view_user/full_details.feature
features/crown_marketplace/manage_users/user_admin/view_user/mixed_roles.feature
features/crown_marketplace/manage_users/user_admin/view_user/something_went_wrong.feature
features/crown_marketplace/manage_users/user_support/edit_user.feature
features/crown_marketplace/manage_users/user_support/resend_temporary_password.feature
features/crown_marketplace/manage_users/user_support/validations/edit_user_validation.feature
features/crown_marketplace/manage_users/user_support/view_user/assorted_details.feature
features/crown_marketplace/manage_users/user_support/view_user/full_details.feature
features/crown_marketplace/manage_users/user_support/view_user/mixed_roles.feature
features/crown_marketplace/manage_users/user_support/view_user/something_went_wrong.feature
features/step_definitions/crown_marketplace/manage_users_steps.rb

Issue: https://crowncommercialservice.atlassian.net/jira/software/c/projects/FMFR/boards/71?modal=detail&selectedIssue=FMFR-1338
I have included an additional line in the background of a feature test, to reflect the new behaviour.

Added a feature where the user table only renders when a string is present in the search box

---

app/controllers/facilities_management/admin/framework_controller.rb
app/controllers/facilities_management/admin/supplier_details_controller.rb
app/controllers/facilities_management/rm3830/admin/service_rates_controller.rb
app/controllers/facilities_management/rm3830/admin/sublot_regions_controller.rb
app/controllers/facilities_management/rm3830/admin/sublot_services_controller.rb
app/helpers/facilities_management/admin/framework_helper.rb
app/views/facilities_management/admin/supplier_details/show.html.erb
app/views/facilities_management/rm3830/admin/service_rates/_average-framework-rates.html.erb
app/views/facilities_management/rm3830/admin/service_rates/_call-off-benchmark-rates.html.erb
app/views/facilities_management/rm3830/admin/service_rates/_variance_table.html.erb
app/views/facilities_management/rm3830/admin/service_rates/edit.html.erb
app/views/facilities_management/rm3830/admin/sublot_regions/edit.html.erb
app/views/facilities_management/rm3830/admin/sublot_services/_services.html.erb
app/views/facilities_management/rm3830/admin/sublot_services/_services_prices_and_variances.html.erb
config/locales/views/facilities_management.rm3830.en.yml
config/locales/views/facilities_management.rm6232.en.yml
features/facilities_management/rm3830/admin/assessed_value/service_rates_framework_expired.feature
features/facilities_management/rm3830/admin/supplier_data/supplier_details/supplier_details_framework_expired.feature
features/facilities_management/rm3830/admin/supplier_data/supplier_framework_data/supplier_framework_data_framework_expired.feature
features/facilities_management/rm6232/admin/supplier_data/supplier_details/supplier_details_framework_expired.feature
features/step_definitions/facilities_management/rm3830/framework_status_steps.rb
features/support/pages/admin.rb
spec/controllers/facilities_management/admin/supplier_details_controller_rm3830_spec.rb
spec/controllers/facilities_management/admin/supplier_details_controller_rm6232_spec.rb
spec/controllers/facilities_management/rm3830/admin/service_rates_controller_spec.rb
spec/controllers/facilities_management/rm3830/admin/sublot_regions_controller_spec.rb
spec/controllers/facilities_management/rm3830/admin/sublot_services_controller_spec.rb
spec/helpers/facilities_management/admin/framework_helper_spec.rb

Ticket: [FMFR-1358](https://crowncommercialservice.atlassian.net/browse/FMFR-1358)
I have updated the RM3830 admin section so that when the framework has expired, admins will be unable to edit/update any of the service/supplier data in the system.
I’ve also added specs to validate these changes.
[FMFR-1358]: https://crowncommercialservice.atlassian.net/browse/FMFR-1358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FMFR-1358 - Freeze data when RM3830 has expired

---

app/services/cognito/confirm_sign_up.rb
app/services/cognito/forgot_password.rb
spec/services/cognito/confirm_password_reset_spec.rb
spec/services/cognito/confirm_sign_up_spec.rb
spec/services/cognito/create_user_from_cognito_spec.rb
spec/services/cognito/forgot_password_spec.rb
spec/services/cognito/resend_confirmation_code_spec.rb
spec/services/cognito/respond_to_challenge_spec.rb
spec/services/cognito/sign_in_user_spec.rb
spec/services/cognito/sign_up_user_spec.rb
spec/services/cognito/update_user_spec.rb

Ticket: [FMFR-1360](https://crowncommercialservice.atlassian.net/browse/FMFR-1360)
I have made sure that the email is lowercased for the forgot password and confirm sign up routes (where the user has to enter an email).
In addition, I have refactored all of the cognito service unit tests.
[FMFR-1360]: https://crowncommercialservice.atlassian.net/browse/FMFR-1360?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FMFR-1360 - Make sure user entered emails are downcased

---

app/controllers/base/sessions_controller.rb
app/views/base/sessions/new.html.erb
app/views/layouts/application.html.erb
lib/ext/ruby/auto_session_timeout_helper.rb
spec/controllers/base/sessions_controller_spec.rb

Ticket: [FMFR-1365](https://crowncommercialservice.atlassian.net/browse/FMFR-1365)
I have updated the `timeout` path in the sessions controller so that we can determine the sign in url from the current page URL
[FMFR-1365]: https://crowncommercialservice.atlassian.net/browse/FMFR-1365?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FMFR-1365 - Make sure auto timeout goes to the correct location

---

app/controllers/facilities_management/buyer_details_controller.rb
app/javascript/src/facilitiesManagement/contactDetailsInStorage.ts
app/models/facilities_management/buyer_detail.rb
app/views/facilities_management/buyer_details/edit.html.erb
config/locales/views/facilities_management.en.yml
db/migrate/20230425075107_add_contact_opt_in_for_buyer_details.rb
db/schema.rb
features/facilities_management/rm3830/buyer_details/buyer_details.feature
features/facilities_management/rm3830/buyer_details/validations/buyer_details_validations.feature
features/facilities_management/rm6232/buyer_details/buyer_details.feature
features/facilities_management/rm6232/buyer_details/validations/buyer_details_validations.feature
features/step_definitions/facilities_management/buyer_detail_steps.rb
features/support/pages/buyer_detail.rb
spec/factories/buyer_details.rb
spec/models/facilities_management/buyer_detail_spec.rb
spec/models/user_spec.rb

Ticket: [FMFR-1368](https://crowncommercialservice.atlassian.net/browse/FMFR-1368)
I have added the new field for buyer details where buyers now have to opt in to be contacted by the category,
If the buyer has not answered this new question, they will be forced to before they can do any actions within the service (for example, start a search).
[FMFR-1368]: https://crowncommercialservice.atlassian.net/browse/FMFR-1368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FMFR-1368 - Add question to opt into being contacted

---

app/controllers/concerns/cookie_settings_concern.rb
app/javascript/packs/ccs.ts
app/javascript/src/shared/cookieBanner.ts
app/javascript/src/shared/googleAnalyticsDataLayer.ts
app/views/home/cookie_policy.html.erb
app/views/home/cookie_settings.html.erb
config/application.rb
config/initializers/content_security_policy.rb
config/locales/en.yml
features/helpers/facilities_management/cookies_helper.rb
features/step_definitions/facilities_management/home_steps.rb
features/step_definitions/hooks.rb
spec/controllers/crown_marketplace/home_controller_spec.rb
spec/controllers/facilities_management/rm3830/admin/home_controller_spec.rb
spec/controllers/facilities_management/rm3830/home_controller_spec.rb
spec/controllers/facilities_management/rm3830/supplier/home_controller_spec.rb
spec/controllers/facilities_management/rm6232/admin/home_controller_spec.rb
spec/controllers/facilities_management/rm6232/home_controller_spec.rb
spec/helpers/application_helper_spec.rb
spec/views/layouts/application.html.erb_spec.rb

Ticket: [FMFR-1389](https://crowncommercialservice.atlassian.net/browse/FMFR-1389)
Update the cookie names to match the unified approach.
Add the data layer push for the GA consent mode.
[FMFR-1389]: https://crowncommercialservice.atlassian.net/browse/FMFR-1389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FMFR-1389 - Update the cookie names to match the unified approach

---

.env.test
app/controllers/home_controller.rb
app/views/home/status.html.erb
config/environments/production.rb
config/routes.rb
spec/controllers/home_controller_spec.rb

This is so the ECS tasks can check for the health of the container (it is currently being blocked)
The health check path needs to be updated to: `/healthcheck`

Update the healthcheck route to check for the apps status
